// src/components/Pagination/Pagination.vue
<script setup lang="ts">
import { computed, nextTick, ref, watch } from "vue";
import { useOptionalModel } from "#composables";

const props = withDefaults(
  defineProps<{
    modelValue: number;
    length?: number;
    disabled?: boolean;
  }>(),
  {
    modelValue: 1,
    length: 1,
    disabled: false,
  }
);

const emit = defineEmits<{
  "update:modelValue": [value: number];
}>();

const [model, setModel] = useOptionalModel<any>(
  props,
  "modelValue",
  emit,
  null
);

const pagination = ref<HTMLElement>();
const pageLength = computed(() => props.length < 1 ? 1 : props.length);

const options = computed(() => {
  const result: any = [];
  if (props.length < 1) return result;

  for (let i = 1; i <= props.length; i++) {
    if (
      i === 1 ||
      i === props.length ||
      (model.value === 1 && i < 4) ||
      (model.value === props.length && i >= props.length - 2) ||
      model.value - 1 === i ||
      model.value + 1 === i ||
      model.value === i
    ) {
      result.push(i);
    } else if (
      (model.value <= props.length - 2 &&
        i === props.length - 1 &&
        props.length > 3) ||
      (model.value > 2 && props.length > 3 && i === 2)
    ) {
      result.push(-1);
    }
  }

  for (let pass = 0; pass < 2; pass++) {
    const index = result.findIndex((value: number) => value == -1);
    if (index !== -1 && result[index + 1] - result[index - 1] == 2) {
      result[index] = result[index - 1] + 1;
    }
  }

  return result;
});

watch(() => props.length, () => {
  setModel(1);
});

watch(() => props.modelValue, (newVal) => {
  if (newVal < 1) setModel(1);
  else if (newVal > props.length && props.length > 0) setModel(props.length);
});

function changePage(page: number) {
  if (props.disabled) return;
  setModel(page, { page });
}

async function onKeyDown(event: KeyboardEvent) {
  const pages: Record<string, number> = {
    ArrowLeft: model.value - 1,
    ArrowRight: model.value + 1,
    Home: 1,
    End: pageLength.value,
  };
  const page = pages[event.key];
  if (props.disabled || page === undefined) return;

  event.preventDefault();
  if (page >= 1 && page <= pageLength.value && page !== model.value)
    changePage(page);
  await nextTick();
  pagination.value?.querySelector<HTMLElement>(".page-number.active")?.focus();
}
</script>

<template>
  <div
    ref="pagination"
    class="pagination"
    :class="{ disabled }"
    :aria-disabled="disabled"
    @keydown="onKeyDown"
  >
    <div
      class="page-icon"
      :tabindex="disabled || model == 1 ? -1 : 0"
      :class="{ disabled: model == 1 }"
      @click="changePage(model - 1)"
      @keyup.enter.space="changePage(model - 1)"
    >
      <Icon name="chevron_left" />
    </div>
    <div class="flex">
      <div v-for="page in options" :key="page" class="flex gap-xs">
        <div class="dots" v-if="page == -1">...</div>
        <div
          v-else
          @click="changePage(page as number)"
          @keyup.enter.space="changePage(page as number)"
          :tabindex="disabled ? -1 : 0"
          class="page-number"
          :class="{ active: page === model }"
        >
          {{ page }}
        </div>
      </div>
    </div>
    <div
      class="page-icon"
      :tabindex="disabled || model == pageLength ? -1 : 0"
      :class="{ disabled: model == pageLength }"
      @click="changePage(model + 1)"
      @keyup.enter.space="changePage(model + 1)"
    >
      <Icon name="chevron_right" />
    </div>
  </div>
</template>

<style scoped>
@reference "../../assets/main.css";

.pagination {
  @apply flex items-center gap-xs;
}

.page-icon {
  @apply h-fit w-fit flex items-center cursor-pointer text-neutral-interaction-default text-2xl leading-xs hover:text-primary-interaction-hover;
}

.disabled {
  @apply pointer-events-none text-neutral-interaction-disabled;
}

.page-number {
  @apply text-sm border-xxs border-transparent flex items-end rounded-sm font-medium cursor-pointer px-base py-xs text-neutral-interaction-default hover:text-primary-interaction-hover;
}

.page-number.active {
  @apply border-neutral-default text-neutral-foreground-high hover:text-neutral-foreground-high;
}

.pagination.disabled {
  @apply pointer-events-none text-neutral-interaction-disabled;

  .page-icon,
  .page-number {
    @apply text-neutral-interaction-disabled;
  }

  .page-number.active {
    @apply border-neutral-disabled;
  }
}

.dots {
  @apply flex items-end py-xxs;
}
</style>

// src/components/Pagination/Pagination.tsx
import { useEffect, useRef } from 'react';
import clsx from 'clsx';
import { useControllable } from '../../hooks/useControllable';
import { Icon } from '../Icon/Icon';
import styles from './Pagination.module.css';

export interface PaginationProps {
  value?: number;
  onChange?: (value: number) => void;
  length: number;
  visiblePages?: number;
  disabled?: boolean;
  className?: string;
}

function buildPages(current: number, length: number): number[] {
  const result: number[] = [];
  if (length < 1) return result;

  for (let i = 1; i <= length; i++) {
    if (
      i === 1 ||
      i === length ||
      (current === 1 && i < 4) ||
      (current === length && i >= length - 2) ||
      current - 1 === i ||
      current + 1 === i ||
      current === i
    ) {
      result.push(i);
    } else if (
      (current <= length - 2 && i === length - 1 && length > 3) ||
      (current > 2 && length > 3 && i === 2)
    ) {
      result.push(-1);
    }
  }

  for (let pass = 0; pass < 2; pass++) {
    const index = result.findIndex((v) => v === -1);
    if (index !== -1 && result[index + 1] - result[index - 1] === 2) {
      result[index] = result[index - 1] + 1;
    }
  }

  return result;
}

export function Pagination({
  value,
  onChange,
  length,
  disabled = false,
  className,
}: PaginationProps) {
  const [model, setModel] = useControllable<number>({
    value,
    defaultValue: 1,
    onChange,
  });
  const containerRef = useRef<HTMLDivElement>(null);
  const focusActivePage = useRef(false);
  const pageLength = length < 1 ? 1 : length;

  useEffect(() => {
    if (model !== undefined && length >= 1 && model > length) {
      setModel(length);
    }
  }, [length]);

  useEffect(() => {
    if (!focusActivePage.current) return;
    focusActivePage.current = false;
    containerRef.current?.querySelector<HTMLButtonElement>(`.${styles.active}`)?.focus();
  }, [model]);

  const changePage = (page: number) => {
    if (disabled) return;
    setModel(page);
  };

  const handleKeyDown = (event: React.KeyboardEvent<HTMLDivElement>) => {
    const pageMap: Record<string, number> = {
      ArrowLeft: (model ?? 1) - 1,
      ArrowRight: (model ?? 1) + 1,
      Home: 1,
      End: pageLength,
    };
    const nextPage = pageMap[event.key];

    if (disabled || nextPage === undefined) return;
    event.preventDefault();

    if (nextPage >= 1 && nextPage <= pageLength && nextPage !== model) {
      focusActivePage.current = true;
      changePage(nextPage);
    }
  };

  if (length < 1) return null;

  const pages = buildPages(model ?? 1, length);
  const currentPage = model ?? 1;

  return (
    <div
      ref={containerRef}
      className={clsx(styles.pagination, 'pagination', disabled && styles.disabled, className)}
      aria-disabled={disabled}
      onKeyDown={handleKeyDown}
    >
      <button
        className={styles.navButton}
        disabled={disabled || currentPage === 1}
        onClick={() => changePage(currentPage - 1)}
        aria-label="Previous page"
      >
        <Icon name="chevron_left" className={styles.navIcon} />
      </button>
      <div className="flex">
        {pages.map((page, idx) => (
          <div key={page === -1 ? `ellipsis-${idx}` : page} className="flex gap-xs">
            {page === -1 ? (
              <button className={clsx(styles.pageButton, styles.ellipsis)} disabled>
                ...
              </button>
            ) : (
              <button
                className={clsx(styles.pageButton, 'page-number', page === currentPage && styles.active)}
                disabled={disabled}
                onClick={() => changePage(page)}
                tabIndex={disabled ? -1 : 0}
              >
                {page}
              </button>
            )}
          </div>
        ))}
      </div>
      <button
        className={styles.navButton}
        disabled={disabled || currentPage === length}
        onClick={() => changePage(currentPage + 1)}
        aria-label="Next page"
      >
        <Icon name="chevron_right" className={styles.navIcon} />
      </button>
    </div>
  );
}
