// src/components/FloatCard/FloatCard.tsx
import { useRef, useEffect, useCallback } from 'react';
import { createPortal } from 'react-dom';
import clsx from 'clsx';
import { useControllable } from '../../hooks/useControllable';
import { useTransition } from '../../hooks/useTransition';
import { Card } from '../Card/Card';
import styles from './FloatCard.module.css';

export interface FloatCardProps {
  value?: boolean;
  onChange?: (open: boolean) => void;
  mode?: 'click' | 'hover';
  disabled?: boolean;
  manualFocus?: boolean;
  children?: React.ReactNode;
  card?: React.ReactNode;
  className?: string;
}

export function FloatCard({
  value,
  onChange,
  mode = 'click',
  disabled = false,
  manualFocus = false,
  children,
  card,
  className,
}: FloatCardProps) {
  const [isOpen, setIsOpen] = useControllable({
    value: value,
    defaultValue: false,
    onChange: onChange,
  });

  const contentRef = useRef<HTMLDivElement>(null);
  const cardRef = useRef<HTMLDivElement>(null);
  const previousFocusRef = useRef<HTMLElement | null>(null);

  const { isMounted, isActive } = useTransition(!!isOpen, { duration: 200 });

  const closeCard = useCallback(() => {
    setIsOpen(false);
  }, [setIsOpen]);

  const showCard = useCallback(() => {
    if (disabled) return;

    if (!contentRef.current || !cardRef.current) return;

    const cardContent = cardRef.current.firstElementChild as HTMLElement;
    if (!cardContent) return;

    const rect = (
      contentRef.current.firstElementChild || contentRef.current
    ).getBoundingClientRect();
    const viewportHeight = window.innerHeight;
    const viewportWidth = window.innerWidth;
    const padding = 4;

    if (rect.left + cardContent.offsetWidth > viewportWidth) {
      cardContent.style.left = `${rect.right - cardContent.offsetWidth}px`;
    } else {
      cardContent.style.left = `${rect.left}px`;
    }

    if (rect.bottom + cardContent.offsetHeight > viewportHeight) {
      cardContent.style.top = `${rect.top - cardContent.offsetHeight - padding}px`;
    } else {
      cardContent.style.top = `${rect.bottom + padding}px`;
    }

    if (mode === 'click' && !manualFocus) focusCard();
  }, [mode, manualFocus]);

  function focusCard() {
    const cardContent = cardRef.current?.firstElementChild as HTMLElement | null;
    if (!cardContent) return;

    previousFocusRef.current = document.activeElement as HTMLElement | null;
    cardContent.tabIndex = -1;
    cardContent.focus({ preventScroll: true });
  }

  function handleKeyDown(e: React.KeyboardEvent) {
    if (!isOpen || e.key !== 'Tab' || e.shiftKey) return;
    if (!contentRef.current?.contains(e.target as Node)) return;

    e.preventDefault();
    focusCard();
  }

  useEffect(() => {
    if (isOpen) {
      if (contentRef.current?.contains(document.activeElement))
        previousFocusRef.current = document.activeElement as HTMLElement;
      return;
    }

    const previousFocus = previousFocusRef.current;
    previousFocusRef.current = null;
    const activeElement = document.activeElement;
    if (
      previousFocus &&
      (activeElement === document.body || cardRef.current?.contains(activeElement))
    ) {
      previousFocus.focus({ preventScroll: true });
      if (document.activeElement !== previousFocus) {
        contentRef.current
          ?.querySelector<HTMLElement>('[tabindex="0"], button:not([disabled]), input:not([disabled]), a[href]')
          ?.focus({ preventScroll: true });
      }
    }
  }, [isOpen]);

  useEffect(() => {
    if (!isMounted) return;

    requestAnimationFrame(() => showCard());

    const closeHandler = (e: MouseEvent | WheelEvent) => {
      if (!cardRef.current) return;

      const cardContent = cardRef.current.firstElementChild as HTMLElement;
      if (!cardContent) return;

      const isWheel = e.type === 'wheel';
      const rect = cardContent.getBoundingClientRect();
      const clientX = 'clientX' in e ? e.clientX : 0;
      const clientY = 'clientY' in e ? e.clientY : 0;
      const isInsideCard =
        clientX >= rect.left &&
        clientX <= rect.right &&
        clientY >= rect.top &&
        clientY <= rect.bottom;

      if (isWheel && isInsideCard) {
        let current = e.target as HTMLElement;
        while (current && cardContent.contains(current)) {
          if (current.scrollHeight > current.clientHeight) return;
          if (current === cardContent) break;
          current = current.parentElement as HTMLElement;
        }
        closeCard();
      } else if (!isInsideCard) {
        closeCard();
      }
    };

    const timerId = setTimeout(() => {
      document.addEventListener('click', closeHandler);
      document.addEventListener('wheel', closeHandler);
    }, 200);

    return () => {
      clearTimeout(timerId);
      document.removeEventListener('click', closeHandler);
      document.removeEventListener('wheel', closeHandler);
    };
  }, [isMounted, showCard, closeCard]);

  return (
    <div
      ref={contentRef}
      onClick={mode === 'click' ? (e) => {
        if (disabled) return;
        if (contentRef.current?.contains(e.target as Node)) {
          setIsOpen(true);
        }
      } : undefined}
      onMouseEnter={mode === 'hover' && !disabled ? () => setIsOpen(true) : undefined}
      onMouseLeave={mode === 'hover' && !disabled ? closeCard : undefined}
      onKeyDown={handleKeyDown}
      className={clsx('float-card-container', className)}
    >
      {isMounted &&
        createPortal(
          <div ref={cardRef}>
            <Card
              className={clsx(
                styles.floatCard,
                'float-card',
                isActive && styles.active
              )}
            >
              {card}
            </Card>
          </div>,
          document.body
        )}
      {children}
    </div>
  );
}

// src/components/FloatCard/FloatCard.vue
<script setup lang="ts">
import { nextTick, ref, computed, watch, onBeforeUnmount } from "vue";

const props = withDefaults(
  defineProps<{
    modelValue: boolean;
    mode?: "click" | "hover";
    disabled?: boolean;
    manualFocus?: boolean;
  }>(),
  {
    modelValue: false,
    mode: "click",
    disabled: false,
    manualFocus: false,
  }
);

const emit = defineEmits<{
  "update:modelValue": [value: any];
}>();

const model = ref(props.modelValue);
const content = ref<HTMLElement>();
const card = ref<HTMLElement>();
let openTimer: ReturnType<typeof setTimeout> | undefined;
let previousFocus: HTMLElement | null = null;

const computedPadding = computed((): number => {
  if (
    document.readyState === "complete" ||
    document.readyState === "interactive"
  ) {
    return Number(
      (
        (content.value as any)
          ?.computedStyleMap()
          .get("--spacing-xxs")
          ?.toString() || "4px"
      ).replace("px", "")
    );
  }
  return 4;
});

watch(
  () => props.modelValue,
  (value) => {
    model.value = value;
    if (value) {
      if (content.value?.contains(document.activeElement))
        previousFocus = document.activeElement as HTMLElement;
      showCard();
    } else removeCloseListeners();
  }
);

watch(model, (value) => {
  if (!value) restoreFocus();
});

function focusCard() {
  const cardContent = card.value?.querySelector(".float-card") as HTMLElement;
  if (!cardContent) return;

  previousFocus = document.activeElement as HTMLElement | null;
  cardContent.focus({ preventScroll: true });
}

function restoreFocus() {
  const lastFocus = previousFocus;
  previousFocus = null;
  const activeElement = document.activeElement;
  if (
    !lastFocus ||
    (activeElement !== document.body && !card.value?.contains(activeElement))
  )
    return;

  lastFocus.focus({ preventScroll: true });
  if (document.activeElement !== lastFocus)
    content.value
      ?.querySelector<HTMLElement>(
        '[tabindex="0"], button:not([disabled]), input:not([disabled]), a[href]'
      )
      ?.focus({ preventScroll: true });
}

function onTriggerKeyDown(e: KeyboardEvent) {
  if (!model.value || e.key !== "Tab" || e.shiftKey) return;
  if (!content.value?.contains(e.target as Node)) return;

  e.preventDefault();
  focusCard();
}

function updateModel(value: boolean) {
  if (props.disabled) return;

  model.value = value;
  emit("update:modelValue", value);
}

function onTriggerClick(e: MouseEvent) {
  if (props.mode !== "click" || props.disabled) return;
  if (content.value?.contains(e.target as Node)) updateModel(true);
}

function closeCard() {
  updateModel(false);
  removeCloseListeners();
}

function removeCloseListeners() {
  if (openTimer) {
    clearTimeout(openTimer);
    openTimer = undefined;
  }
  document.removeEventListener("click", closeHandler);
  document.removeEventListener("wheel", closeHandler);
}

function closeHandler(e: MouseEvent | WheelEvent) {
  if (!card.value) return;

  let cardContent = card.value.querySelector(".float-card") as HTMLElement;
  if (!cardContent)
    cardContent = (card.value.firstElementChild || card.value) as HTMLElement;

  const isWheel = e.type === "wheel";
  const isInsideCard = isClickInsideElement(e, cardContent);

  if (isWheel && isInsideCard) {
    const scrollableElement = findScrollableParent(
      e.target as HTMLElement,
      cardContent
    );
    if (scrollableElement) return;

    closeCard();
  } else if (!isInsideCard) closeCard();
}

function isClickInsideElement(
  e: MouseEvent | WheelEvent,
  element: HTMLElement
): boolean {
  if (!element) return false;

  const rect = element.getBoundingClientRect();
  
  const clientX = "clientX" in e ? e.clientX : 0;
  const clientY = "clientY" in e ? e.clientY : 0;

  return (
    clientX >= rect.left &&
    clientX <= rect.right &&
    clientY >= rect.top &&
    clientY <= rect.bottom
  );
}

function findScrollableParent(
  element: HTMLElement,
  container: HTMLElement
): HTMLElement | null {
  let current = element;

  while (current && container.contains(current)) {
    if (current.scrollHeight > current.clientHeight) return current;

    current = current.parentElement as HTMLElement;
    if (current === container) break;
  }

  return null;
}

async function showCard() {
  await nextTick();

  if (!content.value || !card.value) return;

  let cardContent = card.value.querySelector(".float-card") as HTMLElement;
  if (!cardContent) return;

  cardContent = (card.value.firstElementChild || card.value) as HTMLElement;
  const rect = (
    content.value.firstElementChild || content.value
  ).getBoundingClientRect();
  const viewportHeight = window.innerHeight;
  const viewportWidth = window.innerWidth;

  if (rect.left + cardContent.offsetWidth > viewportWidth)
    cardContent.style.left = `${rect.right - cardContent.offsetWidth}px`;
  else cardContent.style.left = `${rect.left}px`;

  if (rect.bottom + cardContent.offsetHeight > viewportHeight)
    cardContent.style.top = `${rect.top - cardContent.offsetHeight - computedPadding.value}px`;
  else cardContent.style.top = `${rect.bottom + computedPadding.value}px`;

  if (props.mode === "click" && !props.manualFocus) focusCard();

  if (openTimer) clearTimeout(openTimer);
  openTimer = setTimeout(() => {
    document.addEventListener("click", closeHandler);
    document.addEventListener("wheel", closeHandler);
  }, 200);
}

onBeforeUnmount(removeCloseListeners);
</script>

<template>
  <div
    ref="content"
    class="float-card-container"
    @click="onTriggerClick"
    @mouseenter="mode == 'hover' ? updateModel(true) : null"
    @mouseleave="mode == 'hover' ? closeCard() : null"
    @keydown="onTriggerKeyDown"
  >
    <Teleport to="body">
      <div ref="card">
        <Transition name="fade">
          <Card v-if="model" class="float-card" tabindex="-1">
            <slot name="card" />
          </Card>
        </Transition>
      </div>
    </Teleport>
    <slot />
  </div>
</template>

<style scoped>
@reference "../../assets/main.css";

.float-card {
  @apply z-[1004] fixed outline-none;
}

.fade-enter-active,
.fade-leave-active {
  @apply transition-opacity duration-200;
}

.fade-enter-from,
.fade-leave-to {
  @apply opacity-0;
}
</style>
