// src/components/AutoComplete/AutoComplete.vue
<script setup lang="ts">
import { ref, computed, watch } from "vue";
import { useOptionalModel } from "#composables";
import SelectContainer from "../../utils/components/SelectContainer.vue";
import Option from "@/utils/components/Option.vue";

const props = withDefaults(
  defineProps<{
    modelValue?: number | string;
    expanded?: boolean;
    labelValue?: string;
    options?: number[] | string[];
    disabled?: boolean;
    isError?: boolean;
    errorMessage?: string;
    infoMessage?: string;
    required?: boolean;
    placeholder?: string;
    maxHeight?: string;
    minWidth?: string;
  }>(),
  {
    modelValue: undefined,
    expanded: false,
    labelValue: "",
    disabled: false,
    isError: false,
    errorMessage: "",
    infoMessage: "",
    required: false,
    placeholder: "Search...",
    maxHeight: "40px",
    minWidth: "15em",
  }
);

const emit = defineEmits<{
  "update:modelValue": [value: number | string];
  "update:expanded": [value: boolean];
}>();

const [model, setModel] = useOptionalModel<number | string>(
  props,
  "modelValue",
  emit,
  ""
);
const [expanded, setExpanded] = useOptionalModel<boolean>(
  props,
  "expanded",
  emit,
  false
);

// Track input focus so close attempts triggered by interacting with the input
// (the trigger lives outside the teleported card, so FloatCard would otherwise
// treat clicking/typing in it as an "outside" click) keep the dropdown open.
const focus = ref(false);
const selectedIndex = ref<number | null>(null);
const optionRefs = ref<HTMLElement[]>([]);

const filteredOptions = computed(() => {
  if (!model.value) return props.options ?? [];
  return (props.options ?? []).filter((option: any) =>
    option
      .toString()
      .toLowerCase()
      .includes(model.value?.toString().toLowerCase())
  );
});

watch(expanded, (value) => {
  if (!value) selectedIndex.value = null;
});

watch(model, () => {
  selectedIndex.value = null;
});

watch(
  selectedIndex,
  (index) => {
    if (index == null) return;
    optionRefs.value[index]?.focus();
  },
  { flush: "post" }
);

function handleExpanded(value: boolean, extra?: any) {
  if (extra?.source === "blur") setExpanded(value && focus.value);
  else if (focus.value) setExpanded(true);
  else setExpanded(value);
}

function handleFocus(value: boolean) {
  focus.value = value;
}

function onRootClick() {
  // Defer so it runs after FloatCard's own close handling; while the input is
  // focused this re-opens the card that an input click would otherwise close.
  setTimeout(() => handleExpanded(focus.value));
}

function selectOption(option: number | string) {
  if (props.disabled) return;
  setModel(option);
  setExpanded(false);
}

function onKeyDown(e: KeyboardEvent) {
  const last = filteredOptions.value.length - 1;
  if (last < 0) return;

  const hasSelection = selectedIndex.value != null;
  switch (e.key) {
    case "ArrowUp":
      e.preventDefault();
      if (!expanded.value) setExpanded(true);
      selectedIndex.value = hasSelection
        ? Math.max(selectedIndex.value! - 1, 0)
        : last;
      break;
    case "ArrowDown":
      e.preventDefault();
      if (!expanded.value) setExpanded(true);
      selectedIndex.value = hasSelection
        ? Math.min(selectedIndex.value! + 1, last)
        : 0;
      break;
  }
}

function onOptionKeyDown(e: KeyboardEvent) {
  switch (e.key) {
    case " ":
      e.preventDefault();
      break;
    case "Home":
      e.preventDefault();
      selectedIndex.value = 0;
      break;
    case "End":
      e.preventDefault();
      selectedIndex.value = filteredOptions.value.length - 1;
      break;
    default:
      onKeyDown(e);
  }
}
</script>

<template>
  <div class="auto-complete" @click="onRootClick">
    <SelectContainer
      class="auto-complete-content"
      :model-value="expanded"
      :label-value="labelValue"
      :disabled="disabled"
      :is-error="isError"
      :error-message="errorMessage"
      :info-message="infoMessage"
      :required="required"
      :max-height="maxHeight"
      :min-width="minWidth"
      @keydown="onKeyDown"
      @update:model-value="handleExpanded"
    >
      <template #label>
        <Input
          v-model="model"
          :disabled="disabled"
          :is-error="isError"
          :info-message="infoMessage"
          :placeholder="placeholder"
          :min-width="minWidth"
          icon="unfold_more"
          append-icon
          @focus="handleFocus(true)"
          @blur="handleFocus(false)"
        />
      </template>

      <template #options>
        <template v-if="filteredOptions.length">
          <Option
            v-for="(option, index) in filteredOptions"
            :ref="(el: any) => (optionRefs[index] = el?.$el)"
            :key="index"
            :aria-selected="model == option"
            :selected="model == option"
            :class="{ 'font-bold': model == option }"
            @focus="selectedIndex = index"
            @click="selectOption(option)"
            @keydown="onOptionKeyDown"
            @keyup.enter.space="selectOption(option)"
          >
            <slot name="option" :option="option" :index="index">
              {{ option }}
            </slot>
          </Option>
        </template>
        <div v-else class="no-results">
          <slot name="no-options">No options match your search</slot>
        </div>
      </template>
    </SelectContainer>
  </div>
</template>

<style scoped>
@reference "../../assets/main.css";

.no-results {
  @apply text-xs italic text-neutral-foreground-low flex justify-center p-xs;
}
</style>

// src/components/AutoComplete/AutoComplete.tsx
import { useState, useEffect, useRef } from "react";
import clsx from "clsx";
import { useControllable } from "../../hooks/useControllable";
import { SelectContainer } from "../../utils/components/SelectContainer";
import { Option } from "../../utils/components/Option";
import styles from "./AutoComplete.module.css";
import { Input } from "../Input";

export interface AutoCompleteProps {
  value?: string | number;
  onChange?: (value: any) => void;
  options: string[] | number[];
  disabled?: boolean;
  labelValue?: string;
  ariaLabel?: string;
  isError?: boolean;
  errorMessage?: string;
  infoMessage?: string;
  required?: boolean;
  placeholder?: string;
  className?: string;
}

export function AutoComplete({
  value,
  onChange,
  options,
  disabled = false,
  labelValue = "",
  ariaLabel,
  isError = false,
  errorMessage = "",
  infoMessage = "",
  required = false,
  placeholder = "Search...",
  className,
}: AutoCompleteProps) {
  const [model, setModel] = useControllable<any>({
    value,
    onChange,
  });

  const [expanded, setExpanded] = useState(false);
  const [selectedIndex, setSelectedIndex] = useState<number | null>(null);
  const optionRefs = useRef<(HTMLDivElement | null)[]>([]);
  let focus = false

  useEffect(() => {
    if (expanded) return;
    setSelectedIndex(null);
  }, [expanded]);

  useEffect(() => {
    setSelectedIndex(null);
  }, [model]);

  useEffect(() => {
    if (selectedIndex == null) return;
    optionRefs.current[selectedIndex]?.focus();
  }, [selectedIndex]);

  function handleExpanded(val: boolean, extra?: any) {
    if (extra?.source == "blur") setExpanded(val && focus);
    else if (focus) setExpanded(true)
    else setExpanded(val);
  }

  function handleFocus(val: boolean) {
    focus = val
  }

  const filteredOptions = options.filter((o) =>
    String(o)
      .toLowerCase()
      .includes(model?.toLowerCase() || ""),
  );

  function selectOption(option: string | number) {
    if (disabled) return;

    setModel(option);
    setExpanded(false);
  }

  function onKeyDown(e: React.KeyboardEvent) {
    const last = filteredOptions.length - 1;
    if (last < 0) return;

    const hasSelection = selectedIndex != null;
    switch (e.key) {
      case "ArrowUp":
        e.preventDefault();
        if (!expanded) setExpanded(true);
        setSelectedIndex(hasSelection ? Math.max(selectedIndex - 1, 0) : last);
        break;
      case "ArrowDown":
        e.preventDefault();
        if (!expanded) setExpanded(true);
        setSelectedIndex(hasSelection ? Math.min(selectedIndex + 1, last) : 0);
        break;
    }
  }

  function onOptionKeyDown(e: React.KeyboardEvent) {
    switch (e.key) {
      case " ":
        e.preventDefault();
        break;
      case "Home":
        e.preventDefault();
        setSelectedIndex(0);
        break;
      case "End":
        e.preventDefault();
        setSelectedIndex(filteredOptions.length - 1);
        break;
      default:
        onKeyDown(e);
    }
  }

  const optionsNode =
    filteredOptions.length > 0
      ? filteredOptions.map((option, index) => (
          <Option
            key={index}
            ref={(el) => {
              optionRefs.current[index] = el;
            }}
            selected={model === option}
            onClick={() => selectOption(option)}
            onFocus={() => setSelectedIndex(index)}
            onKeyDown={onOptionKeyDown}
          >
            {option}
          </Option>
        ))
      : [
          <div key="no-results" className={styles.noResults}>
            No options match your search
          </div>,
        ];

  return (
    <div className="auto-complete" onClick={() => setTimeout(() => handleExpanded(focus))} onKeyDown={onKeyDown}>
      <SelectContainer
        value={expanded}
        onChange={handleExpanded}
        labelValue={labelValue}
        ariaLabel={ariaLabel}
        absolute={true}
        disabled={disabled}
        isError={isError}
        errorMessage={errorMessage}
        infoMessage={infoMessage}
        required={required}
        options={optionsNode}
        label={
          <Input
            value={model}
            disabled={disabled}
            isError={isError}
            infoMessage={infoMessage}
            placeholder={placeholder}
            appendIcon="unfold_more"
            onChange={setModel}
            onFocus={() => {handleFocus(true)}}
            onBlur={() => handleFocus(false)}
          />
        }
        className={clsx("auto-complete-content", className)}
      />
    </div>
  );
}
