// src/components/Badge/Badge.tsx
import clsx from "clsx";
import { Spinner } from "../Spinner/Spinner";
import { Icon } from "../Icon/Icon";
import { getContrastColor, onEnterOrSpace } from "../../utils";
import styles from "./Badge.module.css";
import { useMemo } from "react";

export interface BadgeProps {
  labelValue?: string;
  color?: string;
  size?: "small" | "medium" | "large";
  type?: "default" | "secondary" | "heavy";
  loading?: boolean;
  closeable?: boolean;
  icon?: string;
  isAppendedIcon?: boolean;
  children?: React.ReactNode;
  className?: string;
  onClose?: () => void;
}

export function Badge({
  labelValue = "",
  color = "",
  size = "medium",
  type = "default",
  loading = false,
  closeable = false,
  icon = "",
  isAppendedIcon = false,
  children,
  className,
  onClose,
}: BadgeProps) {
  const prependIcon = !isAppendedIcon ? icon : "";
  const appendedIcon = closeable ? "close" : isAppendedIcon ? icon : "";

  const computedBackground = (() => {
    if (type === "secondary") return "transparent";
    if (type === "heavy") return color;
    return color ? `color-mix(in srgb, ${color} 30%, transparent)` : color;
  })();

  const customStyle: React.CSSProperties = useMemo(
    () =>
      color
        ? {
            color: type === "heavy" ? getContrastColor(color) : color,
            borderColor: color,
            background: computedBackground,
          }
        : {},
    [color, type],
  );

  function close(e: React.SyntheticEvent) {
    if (!closeable) return;
    e.stopPropagation();
    onClose?.();
  }

  return (
    <div
      className={clsx(
        styles.badge,
        "bagde",
        styles[size],
        styles[type],
        className,
      )}
      style={customStyle}
    >
      {loading ? (
        <Spinner />
      ) : (
        <>
          {prependIcon && <Icon name={prependIcon} />}
          {(children || labelValue) && (
            <p className={clsx(styles.colored, styles.label)}>
              {children || labelValue}
            </p>
          )}
          {appendedIcon && (
            <span className={clsx(closeable && styles.clickable)}>
              <Icon
                name={appendedIcon}
                className="close-icon"
                tabIndex={closeable ? 0 : -1}
                aria-label={closeable ? "Remove" : undefined}
                onClick={close}
                onKeyUp={onEnterOrSpace(close)}
              />
            </span>
          )}
        </>
      )}
    </div>
  );
}

// src/components/Badge/Badge.vue
<script setup lang="ts">
import { computed } from "vue";
import { getContrastColor } from "../../utils";

const props = withDefaults(
  defineProps<{
    labelValue?: string;
    color?: string;
    size?: "small" | "medium" | "large";
    type?: "default" | "secondary" | "heavy";
    loading?: boolean;
    closeable?: boolean;
    icon?: string;
    isAppendedIcon?: boolean;
  }>(),
  {
    labelValue: "",
    color: "",
    size: "medium",
    type: "default",
    loading: false,
    icon: "",
    closeable: false,
    isAppendedIcon: false,
  }
);

const emit = defineEmits(["close"]);

const prependIcon = computed(() => {
  if (!props.isAppendedIcon) return props.icon;
  return "";
});

const appendedIcon = computed(() => {
  if (props.closeable) return "close";
  else if (props.isAppendedIcon) return props.icon;
  return "";
});

const background = computed((): string => {
  if (props.type === "secondary") return "transparent";
  if (props.type === "heavy") return props.color;
  return props.color ? `color-mix(in srgb, ${props.color} 30%, transparent)` : props.color;
});

const textColor = computed(() => props.type === 'heavy' ? getContrastColor(props.color) : props.color);

function close(e: Event) {
  if (!props.closeable) return
  e.stopPropagation()
  emit('close')
}
</script>

<template>
  <div :class="[type, size]" class="badge">
    <Spinner v-if="loading" />
    <template v-else>
      <Icon :name="prependIcon" v-if="prependIcon" />
      <p class="font-semibold whitespace-nowrap truncate" v-if="labelValue || $slots.default">
        <slot>{{ labelValue }}</slot>
      </p>
      <Icon class="close-icon" :class="{ 'cursor-pointer': closeable }" :tabindex="closeable ? 0 : -1" :aria-label="closeable ? 'Remove' : undefined" :name="appendedIcon"
        v-if="appendedIcon" @click="close" @keyup.enter.space="close" />
    </template>
  </div>
</template>

<style scoped>
@reference "../../assets/main.css";

.badge {
  @apply flex items-center justify-center gap-xxs text-center w-fit h-fit rounded-full border-xxs py-xs;
  color: v-bind(textColor);
  border-color: v-bind(color);
  background: v-bind(background);
}

.small {
  @apply text-xs leading-(--font-size-sm) px-sm;

  .icon {
    @apply text-sm leading-(--font-size-sm);
  }
}

.medium {
  @apply text-sm leading-(--font-size-base) px-base;

  .icon {
    @apply text-base leading-(--font-size-base);
  }
}

.large {
  @apply text-base leading-(--font-size-xl) px-lg;

  .icon {
    @apply text-xl leading-(--font-size-xl);
  }
}

.badge.secondary {
  @apply bg-transparent;
}
</style>
