// src/components/Profile/Profile.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { useOptionalModel } from "#composables";
import {
  focusByArrowKey,
  focusWhenReady,
  getFocusableItems,
  isObject,
} from "../../utils";
import SelectContainer from "../../utils/components/SelectContainer.vue";

const props = withDefaults(
  defineProps<{
    modelValue?: any;
    name: string;
    picture?: string;
    options?: any[];
    labelKey?: string;
    valueKey?: string;
    disabled?: boolean;
    getObject?: boolean;
  }>(),
  {
    modelValue: undefined,
    labelKey: "label",
    valueKey: "value",
    disabled: false,
    getObject: false,
  }
);

const emit = defineEmits<{
  "update:modelValue": [value: object];
  logout: [];
  edit: [];
  editOption: [];
  privacyPolicyFunction: [];
  termsOfUseFucntion: [];
}>();

const [model] = useOptionalModel<any>(props, "modelValue", emit, null);
const isExpanded = ref(false);
const onFocusInput = ref(false);
const searchValue = ref("");
const menu = ref<HTMLElement>();
const footer = ref<HTMLElement>();

const filteredOptions = computed(() => {
  if (!props.options) return [];
  else if (!searchValue.value) return props.options;

  return props.options.filter((option: any) => {
    if (option[props.labelKey].toLowerCase().includes(searchValue.value.toLowerCase())) {
      return option;
    }
  });
});

const selected = computed(() => {
  return props.options?.find(
    (option: any) => getValue(option) == getValue(model.value)
  );
});

function getLabel(option: any) {
  return isObject(option) ? option[props.labelKey] : option;
}

function getValue(option: any) {
  return isObject(option) ? option[props.valueKey] : option;
}

function updateModel(option: any) {
  isExpanded.value = false;
  model.value = props.getObject ? option : getValue(option);
  emit("update:modelValue", option);
}

function changeExpanded(expanded: boolean) {
  setTimeout(() => {
    isExpanded.value = expanded;
  });
}

function onTriggerKeyDown(event: KeyboardEvent) {
  if (props.disabled || (event.key !== "ArrowDown" && event.key !== "ArrowUp"))
    return;

  event.preventDefault();
  isExpanded.value = true;
  focusWhenReady(() => {
    const items = getMenuItems();
    return event.key === "ArrowDown" ? items[0] : items[items.length - 1];
  });
}

function getMenuItems(footerStop?: HTMLElement) {
  const links = getFocusableItems(footer.value);
  const stop = footerStop ?? links[0];
  return getFocusableItems(menu.value).filter(
    (item) => !links.includes(item) || item === stop
  );
}

function onMenuKeyDown(event: KeyboardEvent) {
  const target = event.target as HTMLElement;
  const links = getFocusableItems(footer.value);
  const inFooter = links.includes(target);

  if (inFooter && (event.key === "ArrowLeft" || event.key === "ArrowRight")) {
    focusByArrowKey(event, links, "horizontal");
    return;
  }

  focusByArrowKey(event, getMenuItems(inFooter ? target : undefined), "vertical");
}
</script>

<template>
  <SelectContainer
    v-model="isExpanded"
    class="profile"
    aria-multiselectable="false"
    :disabled="disabled"
    dont-have-max-height
    min-width="25em"
    @keydown="onTriggerKeyDown"
  >
    <div
      v-if="!isExpanded"
      class="flex items-center gap-xs text-2xl mr-xxs text-neutral-interaction-default"
      @click="changeExpanded(!isExpanded)"
    >
      <Avatar
        :name="name"
        :src="picture"
        size="small"
        alt="profile picture"
      />
      <p class="text-sm font-bold">
        {{ model ? getLabel(selected) || name : name }}
      </p>
    </div>

    <template #options>
      <div ref="menu" @keydown="onMenuKeyDown">
        <div
          class="flex flex-col items-center gap-xs text-9xl px-xs py-sm text-neutral-interaction-default"
        >
          <Avatar
            :name="name"
            :src="picture"
            size="large"
            alt="profile picture"
          />
          <p
            class="text-sm text-center"
            v-if="model && getLabel(selected) && name"
          >
            {{ name }}
          </p>
          <h4
            class="text-3xl font-bold m-xxs text-center"
            v-if="(model && getLabel(selected)) || name"
          >
            {{ model ? getLabel(selected) || name : name }}
          </h4>
          <Button
            type="submit"
            color="primary"
            @click="emit('edit')"
            class="m-xxs truncate"
            :disabled="!name && !picture"
          >
            <slot name="edit-label"> Edit profile </slot>
          </Button>
        </div>
        <div
          class="flex flex-col items-center text-neutral-interaction-default"
          v-if="options && options.length"
        >
          <div class="flex items-center w-full relative">
            <Icon
              name="search"
              class="search-icon"
              :class="{
                'text-primary-interaction-default': onFocusInput === true,
              }"
            />
            <input
              v-model="searchValue"
              type="search"
              class="input-default"
              @focus="onFocusInput = true"
              @blur="onFocusInput = false"
              placeholder="Search"
            />
          </div>
          <div
            class="w-full text-neutral-interaction-default"
            :class="{
              'pr-xxs py-xxs': filteredOptions.length > 4,
            }"
          >
            <div
              class="w-full flex flex-col divide-y-xxs divide-neutral-default font-bold max-h-[12em] overflow-auto custom-scroll"
            >
              <div
                v-for="(option, index) in filteredOptions"
                :key="index"
                tabindex="0"
                class="profile-option justify-start w-full [&>*]:text-sm hover:bg-neutral-surface-highlight"
                @click="updateModel(option)"
                @keyup.enter.space="updateModel(option)"
              >
                <slot
                  name="option"
                  :option="option"
                  :index="index"
                  :active="
                    JSON.stringify(model || {}) == JSON.stringify(option || {})
                  "
                >
                  <p
                    class="text-sm"
                    :class="{
                      '[&>*]:underline':
                        JSON.stringify(model || {}) ==
                        JSON.stringify(option || {}),
                    }"
                  >
                    {{ getLabel(option) }}
                  </p>
                </slot>
              </div>
            </div>
          </div>
        </div>
        <div
          class="flex flex-col divide-y-xxs divide-neutral-default"
          :class="{
            'border-t-xxs border-t-neutral-default':
              filteredOptions && filteredOptions.length,
          }"
        >
          <div
            class="profile-option action text-neutral-interaction-default hover:bg-neutral-surface-highlight"
            tabindex="0"
            @click="emit('editOption')"
            @keyup.enter.space="emit('editOption')"
            v-if="model"
          >
            <Icon name="person" class="profile-icon" />
            <p class="text-sm font-bold">
              <slot name="edit-option"> Edit account </slot>
            </p>
          </div>
          <div
            class="text-danger-interaction-default profile-option action hover:bg-danger-surface-default"
            tabindex="0"
            @click="emit('logout')"
            @keyup.enter.space="emit('logout')"
          >
            <Icon name="logout" class="profile-icon" />
            <p class="text-sm font-bold">
              <slot name="logout-label"> Logout </slot>
            </p>
          </div>
        </div>
        <div
          ref="footer"
          class="flex items-center justify-center px-xs py-sm pt-xl text-neutral-interaction-default font-bold text-xxs gap-5 [&>*]:cursor-pointer"
        >
          <p
            class="hover:underline"
            tabindex="0"
            @click="emit('privacyPolicyFunction')"
            @keyup.enter.space="emit('privacyPolicyFunction')"
          >
            <slot name="privacy-policy"> Privacy Policy </slot>
          </p>
          <p
            class="hover:underline"
            tabindex="0"
            @click="emit('termsOfUseFucntion')"
            @keyup.enter.space="emit('termsOfUseFucntion')"
          >
            <slot name="terms-of-use"> Terms of use </slot>
          </p>
        </div>
      </div>
    </template>
  </SelectContainer>
</template>

<style scoped>
@reference "../../assets/main.css";

.avatar.large {
  @apply p-2xl;
}

:deep(.avatar.large span) {
  @apply text-3xl;
}

.profile-option {
  @apply flex items-center gap-xs p-xs cursor-pointer;
}

.profile-option.action {
  @apply p-xs text-xl;
}

.search-icon {
  @apply absolute left-1.5 text-xl;
}

.input-default {
  @apply w-full text-sm bg-neutral-surface-default border-xxs border-neutral-default placeholder:text-neutral-interaction-default py-xs pr-xs pl-2xl outline-none focus:border-neutral-default;
}

.profile-icon {
  @apply text-xl leading-xs;
}
</style>

// src/components/Profile/Profile.tsx
import { useState, useEffect, useRef } from 'react';
import clsx from 'clsx';
import { Avatar } from '../Avatar/Avatar';
import { Button } from '../Button/Button';
import { Icon } from '../Icon/Icon';
import { useControllable } from '../../hooks/useControllable';
import { onEnterOrSpace, focusByArrowKey, getFocusableItems, focusWhenReady } from '../../utils/index';
import styles from './Profile.module.css';
import { isObject } from '#utils/index';

export interface ProfileOption {
  [key: string]: any;
}

export interface ProfileProps {
  value?: any;
  onChange?: (value: any) => void;
  name: string;
  picture?: string;
  options?: ProfileOption[];
  labelKey?: string;
  valueKey?: string;
  absolute?: boolean;
  disabled?: boolean;
  getObject?: boolean;
  className?: string;
  editLabel?: React.ReactNode;
  editOptionLabel?: React.ReactNode;
  logoutLabel?: React.ReactNode;
  privacyPolicyLabel?: React.ReactNode;
  termsOfUseLabel?: React.ReactNode;
  onLogout?: () => void;
  onEdit?: () => void;
  onEditOption?: () => void;
  onPrivacyPolicy?: () => void;
  onTermsOfUse?: () => void;
  renderOption?: (params: { option: ProfileOption; index: number; active: boolean }) => React.ReactNode;
}

export function Profile({
  value,
  onChange,
  name,
  picture,
  options = [],
  labelKey = 'label',
  valueKey = 'value',
  absolute = false,
  disabled = false,
  getObject = false,
  className,
  editLabel = 'Edit profile',
  editOptionLabel = 'Edit account',
  logoutLabel = 'Logout',
  privacyPolicyLabel = 'Privacy Policy',
  termsOfUseLabel = 'Terms of use',
  onLogout,
  onEdit,
  onEditOption,
  onPrivacyPolicy,
  onTermsOfUse,
  renderOption,
}: ProfileProps) {
  const [model, setModel] = useControllable<unknown>({
    value,
    onChange,
  });

  const [isOpen, setIsOpen] = useState(false);
  const [searchValue, setSearchValue] = useState('');
  const [onFocusInput, setOnFocusInput] = useState(false);
  const wrapperRef = useRef<HTMLDivElement>(null);
  const triggerRef = useRef<HTMLDivElement>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);
  const menuRef = useRef<HTMLDivElement>(null);
  const footerRef = useRef<HTMLDivElement>(null);
  const wasOpenRef = useRef(false);

  useEffect(() => {
    const activeElement = document.activeElement;
    if (isOpen) dropdownRef.current?.focus({ preventScroll: true });
    else if (
      wasOpenRef.current &&
      (activeElement === document.body || wrapperRef.current?.contains(activeElement))
    )
      triggerRef.current?.focus({ preventScroll: true });
    wasOpenRef.current = isOpen;
  }, [isOpen]);

  useEffect(() => {
    function handleMouseDown(event: MouseEvent) {
      if (wrapperRef.current && !wrapperRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    }
    document.addEventListener('mousedown', handleMouseDown);
    return () => {
      document.removeEventListener('mousedown', handleMouseDown);
    };
  }, []);

  function getLabel(option: any): string {
    return isObject(option) ? String(option[labelKey] ?? '') : String(option ?? '');
  }

  function getValue(option: any): any {
    return isObject(option) ? option[valueKey] : option;
  }

  const selected = options.find(
    (option) => String(getValue(option)) === String(getValue(model))
  );

  const filteredOptions = searchValue
    ? options.filter((option) =>
        getLabel(option).toLowerCase().includes(searchValue.toLowerCase())
      )
    : options;

  function updateModel(option: ProfileOption) {
    setIsOpen(false);
    const newValue = getObject ? option : getValue(option);
    setModel(newValue);
  }

  function toggleOpen() {
    if (!disabled) {
      setIsOpen((prev) => !prev);
    }
  }

  function onTriggerKeyDown(e: React.KeyboardEvent) {
    if (disabled || (e.key !== 'ArrowDown' && e.key !== 'ArrowUp')) return;

    e.preventDefault();
    setIsOpen(true);
    focusWhenReady(() => {
      const items = getMenuItems();
      return e.key === 'ArrowDown' ? items[0] : items[items.length - 1];
    });
  }

  function getMenuItems(footerStop?: HTMLElement) {
    const footerLinks = getFocusableItems(footerRef.current);
    const stop = footerStop ?? footerLinks[0];
    return getFocusableItems(menuRef.current).filter(
      (item) => !footerLinks.includes(item) || item === stop
    );
  }

  function onMenuKeyDown(e: React.KeyboardEvent) {
    const target = e.target as HTMLElement;
    const footerLinks = getFocusableItems(footerRef.current);
    const inFooter = footerLinks.includes(target);

    if (inFooter && (e.key === 'ArrowLeft' || e.key === 'ArrowRight')) {
      focusByArrowKey(e, footerLinks, 'horizontal');
      return;
    }

    focusByArrowKey(e, getMenuItems(inFooter ? target : undefined), 'vertical');
  }

  const displayName = model && selected ? getLabel(selected) || name : name;

  return (
    <div
      ref={wrapperRef}
      className={clsx(
        styles.profile,
        'profile',
        absolute && styles.absolute,
        disabled && styles.disabled,
        className
      )}
    >
      {!isOpen && (
        <div
          className={clsx(
            styles.trigger,
            'flex items-center gap-xs text-2xl mr-xxs text-neutral-interaction-default'
          )}
          ref={triggerRef}
          tabIndex={disabled ? -1 : 0}
          onClick={toggleOpen}
          onKeyUp={onEnterOrSpace(toggleOpen)}
          onKeyDown={onTriggerKeyDown}
        >
          <Avatar name={name} src={picture} size="small" alt="profile picture" />
          <p className="text-sm font-bold">{displayName}</p>
        </div>
      )}

      {isOpen && (
        <div
          ref={dropdownRef}
          className={clsx(styles.dropdown, 'outline-none')}
          tabIndex={-1}
          onKeyDown={(e) => {
            if (e.key !== 'Escape') return;
            e.stopPropagation();
            setIsOpen(false);
          }}
        >
          <div ref={menuRef} onKeyDown={onMenuKeyDown}>
            <div className="flex flex-col items-center gap-xs text-9xl px-xs py-sm text-neutral-interaction-default">
              <Avatar name={name} src={picture} size="large" alt="profile picture" />
              {!!(model && getLabel(selected) && name) && (
                <p className="text-sm text-center">{name}</p>
              )}
              {((model && getLabel(selected)) || name) && (
                <h4 className="text-3xl font-bold m-xxs text-center">{displayName}</h4>
              )}
              <Button
                type="submit"
                color="primary"
                onClick={onEdit}
                className="m-xxs truncate"
                disabled={!name && !picture}
              >
                {editLabel}
              </Button>
            </div>

            {options && options.length > 0 && (
              <div className="flex flex-col items-center text-neutral-interaction-default">
                <div className="flex items-center w-full relative">
                  <Icon
                    name="search"
                    className={clsx(
                      styles.searchIcon,
                      onFocusInput && 'text-primary-interaction-default'
                    )}
                  />
                  <input
                    type="search"
                    value={searchValue}
                    onChange={(e) => setSearchValue(e.target.value)}
                    className={styles.inputDefault}
                    onFocus={() => setOnFocusInput(true)}
                    onBlur={() => setOnFocusInput(false)}
                    placeholder="Search"
                  />
                </div>
                <div
                  className={clsx(
                    'w-full text-neutral-interaction-default',
                    filteredOptions.length > 4 && 'pr-xxs py-xxs'
                  )}
                >
                  <div className="w-full flex flex-col divide-y-xxs divide-neutral-default font-bold max-h-[12em] overflow-auto custom-scroll">
                    {filteredOptions.map((option, index) => {
                      const active =
                        JSON.stringify(model || {}) === JSON.stringify(option || {});
                      return (
                        <div
                          key={index}
                          tabIndex={0}
                          className={clsx(
                            styles.profileOption,
                            'justify-start w-full [&>*]:text-sm hover:bg-neutral-surface-highlight'
                          )}
                          onClick={() => updateModel(option)}
                          onKeyUp={onEnterOrSpace(() => updateModel(option))}
                        >
                          {renderOption ? (
                            renderOption({ option, index, active })
                          ) : (
                            <p
                              className={clsx(
                                'text-sm',
                                active && '[&>*]:underline'
                              )}
                            >
                              {getLabel(option)}
                            </p>
                          )}
                        </div>
                      );
                    })}
                  </div>
                </div>
              </div>
            )}

            <div
              className={clsx(
                'flex flex-col divide-y-xxs divide-neutral-default',
                filteredOptions && filteredOptions.length
                  ? 'border-t-xxs border-t-neutral-default'
                  : ''
              )}
            >
              {!!model && (
                <div
                  tabIndex={0}
                  className={clsx(
                    styles.profileOption,
                    styles.profileOptionAction,
                    'text-neutral-interaction-default hover:bg-neutral-surface-highlight'
                  )}
                  onClick={onEditOption}
                  onKeyUp={onEditOption ? onEnterOrSpace(onEditOption) : undefined}
                >
                  <Icon name="person" className={styles.profileIcon} />
                  <p className="text-sm font-bold">{editOptionLabel}</p>
                </div>
              )}
              <div
                tabIndex={0}
                className={clsx(
                  styles.profileOption,
                  styles.profileOptionAction,
                  'text-danger-interaction-default hover:bg-danger-surface-default'
                )}
                onClick={onLogout}
                onKeyUp={onLogout ? onEnterOrSpace(onLogout) : undefined}
              >
                <Icon name="logout" className={styles.profileIcon} />
                <p className="text-sm font-bold">{logoutLabel}</p>
              </div>
            </div>

            <div ref={footerRef} className="flex items-center justify-center px-xs py-sm pt-xl text-neutral-interaction-default font-bold text-xxs gap-5 [&>*]:cursor-pointer">
              <p
                tabIndex={0}
                onClick={onPrivacyPolicy}
                onKeyUp={onPrivacyPolicy ? onEnterOrSpace(onPrivacyPolicy) : undefined}
                className="hover:underline"
              >
                {privacyPolicyLabel}
              </p>
              <p
                tabIndex={0}
                onClick={onTermsOfUse}
                onKeyUp={onTermsOfUse ? onEnterOrSpace(onTermsOfUse) : undefined}
                className="hover:underline"
              >
                {termsOfUseLabel}
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
