// src/components/TagSelect/TagSelect.tsx
import { useEffect, useRef, useState } from "react";
import clsx from "clsx";
import { useControllable } from "../../hooks/useControllable";
import { isObject } from "../../utils";
import { SelectContainer } from "../../utils/components/SelectContainer";
import { Option } from "../../utils/components/Option";
import { StatusBadge } from "../StatusBadge/StatusBadge";
import { Icon } from "../Icon/Icon";
import { Checkbox } from "../Checkbox/Checkbox";
import styles from "./TagSelect.module.css";
import { Button } from "../Button";

export interface TagSelectProps {
  value?: any[];
  onChange?: (value: any[]) => void;
  options?: any[];
  labelKey?: string;
  valueKey?: string;
  getObject?: boolean;
  disabled?: boolean;
  labelValue?: string;
  ariaLabel?: string;
  searchable?: boolean;
  creatable?: boolean;
  isError?: boolean;
  errorMessage?: string;
  infoMessage?: string;
  required?: boolean;
  placeholder?: string;
  icon?: string;
  expanded?: boolean;
  onExpandedChange?: (expanded: boolean) => void;
  absolute?: boolean;
  buttonLabel?: string;
  className?: string;
  children?: React.ReactNode;
}

export function TagSelect({
  value,
  onChange,
  options = [],
  labelKey = "label",
  valueKey = "value",
  getObject: getObjectProp = false,
  disabled = false,
  labelValue = "",
  ariaLabel,
  searchable = false,
  creatable = false,
  isError = false,
  errorMessage = "",
  infoMessage = "",
  required = false,
  placeholder,
  icon,
  expanded: expandedProp,
  onExpandedChange,
  absolute = true,
  buttonLabel,
  className,
  children,
}: TagSelectProps) {
  const [model, setModel] = useControllable<any[]>({
    value,
    defaultValue: [],
    onChange,
  });

  const [searchText, setSearchText] = useState("");
  const [createdOptions, setCreatedOptions] = useState<any[]>([]);
  const [isOpen, setIsOpen] = useControllable<boolean>({
    value: expandedProp,
    defaultValue: false,
    onChange: onExpandedChange,
  });
  const [selectedIndex, setSelectedIndex] = useState<number | null>(null);
  const optionRefs = useRef<(HTMLDivElement | null)[]>([]);
  const expanded = isOpen ?? false;
  const input = useRef<HTMLInputElement>(null);

  const selectedValues: any[] = Array.isArray(model) ? model : [];

  useEffect(() => {
    if (!isOpen) input.current?.blur();
    else input.current?.focus();
  }, [isOpen]);

  useEffect(() => {
    if (isOpen) return;
    setSelectedIndex(null);
  }, [isOpen]);

  useEffect(() => {
    setSelectedIndex(null);
  }, [searchText]);

  useEffect(() => {
    if (selectedIndex == null) return;
    optionRefs.current[selectedIndex]?.focus();
  }, [selectedIndex]);

  function getLabel(option: any): string {
    return isObject(option) ? option[labelKey] : String(option ?? "");
  }

  function getValue(option: any): any {
    return isObject(option) ? option[valueKey] ?? option[labelKey] : option;
  }

  function getTagLabel(tag: any): string {
    if (isObject(tag)) return getLabel(tag);
    const option = allOptions?.find((o: any) => getValue(o) === tag);
    return option ? getLabel(option) : String(tag ?? "");
  }

  function isIncluded(arr: any[], option: any): boolean {
    return arr.some((i) => getValue(i) === getValue(option));
  }

  function toggleOption(option: any) {
    if (disabled) return;
    const emitValue = getObjectProp ? option : getValue(option);
    const arr = [...selectedValues];
    const idx = arr.findIndex((m) => getValue(m) === getValue(option));
    if (idx !== -1) {
      arr.splice(idx, 1);
    } else {
      arr.push(emitValue);
    }
    setModel(arr);
  }

  function removeTag(index: number) {
    const arr = [...selectedValues];
    arr.splice(index, 1);
    setModel(arr);
  }

  function addCreatableOption() {
    if (!creatable || !searchText || isError) return;
    const allOptions = [...options, ...createdOptions];
    const existingOption = allOptions.find(
      (o) => getLabel(o).toLowerCase() === searchText.toLowerCase(),
    );
    if (existingOption) {
      if (!isIncluded(selectedValues, existingOption)) {
        toggleOption(existingOption);
      }
      setSearchText("");
      return;
    }
    if (isIncluded(selectedValues, searchText)) {
      setSearchText("");
      return;
    }
    const newOption = { [labelKey]: searchText, [valueKey]: searchText };
    setCreatedOptions((prev) => [...prev, newOption]);
    const emitValue = getObjectProp ? newOption : searchText;
    const arr = [...selectedValues, emitValue];
    setModel(arr);
    setSearchText("");
  }

  const allOptions = [...options, ...createdOptions];

  const filteredOptions = searchText
    ? allOptions.filter((o) =>
        getLabel(o).toLowerCase().includes(searchText.toLowerCase()),
      )
    : allOptions;

  const searchedOptions = filteredOptions;

  const showAddButton =
    creatable &&
    searchText &&
    !filteredOptions.some(
      (o) => getLabel(o).toLowerCase() === searchText.toLowerCase(),
    );

  const tagsNode =
    selectedValues.length > 0 ? (
      <div
        className={clsx(styles.tagContainer)}
        onClick={() => setTimeout(() => setIsOpen(false))}
      >
        {selectedValues.map((option, index) => (
          <StatusBadge
            key={index}
            color="neutral"
            className="py-none max-w-full"
            closeable
            onClose={() => removeTag(index)}
          >
            {getTagLabel(option)}
          </StatusBadge>
        ))}
      </div>
    ) : undefined;

  const searchNode = (
    <div className="flex items-center gap-xs w-full">
      {(searchable || creatable) && (
        <input
          ref={input}
          type="text"
          value={searchText}
          onChange={(e) => setSearchText(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter" && creatable) addCreatableOption();
            if (e.key === "Tab" && creatable && searchText) {
              e.preventDefault();
              e.stopPropagation();
              addCreatableOption();
            }
          }}
          aria-label={labelValue || ariaLabel || placeholder}
          placeholder={placeholder ?? "Search"}
          disabled={disabled}
          className={clsx(
            "text-neutral-interaction-default h-full w-full bg-neutral-surface-default p-none m-none border-none shadow-none outline-none text-sm",
            {
              "text-danger-foreground-low": isError,
              "bg-neutral-surface-disabled text-neutral-foreground-low":
                disabled,
            },
          )}
          style={{ boxShadow: "none" }}
          onClick={() => setTimeout(() => setIsOpen(true))}
        />
      )}
    </div>
  );

  const statusNode =
    !expanded && selectedValues.length > 0
      ? tagsNode
      : searchable || creatable
        ? searchNode
        : children;

  function onKeyDown(e: React.KeyboardEvent) {
    const last = searchedOptions.length - 1;
    if (last < 0) return;

    const hasSelection = selectedIndex != null;
    switch (e.key) {
      case "ArrowUp":
        e.preventDefault();
        if (!isOpen) setIsOpen(true);
        setSelectedIndex(hasSelection ? Math.max(selectedIndex - 1, 0) : last);
        break;
      case "ArrowDown":
        e.preventDefault();
        if (!isOpen) setIsOpen(true);
        setSelectedIndex(hasSelection ? Math.min(selectedIndex + 1, last) : 0);
        break;
    }
  }

  function onOptionKeyDown(e: React.KeyboardEvent) {
    switch (e.key) {
      case " ":
        e.preventDefault();
        break;
      case "Home":
        e.preventDefault();
        setSelectedIndex(0);
        break;
      case "End":
        e.preventDefault();
        setSelectedIndex(searchedOptions.length - 1);
        break;
      default:
        onKeyDown(e);
    }
  }

  const optionsNode = (
    <div className={styles.optionContainer}>
      {filteredOptions.length === 0 && searchText ? (
        <div className={styles.containerText} role="option" aria-disabled="true">No result found</div>
      ) : allOptions.length === 0 ? (
        <div className={styles.containerText} role="option" aria-disabled="true">No tags created yet</div>
      ) : (
        filteredOptions.map((option, index) => (
          <Option
            key={index}
            ref={(el) => {
              optionRefs.current[index] = el;
            }}
            aria-selected={isIncluded(selectedValues, option)}
            noHover
            onClick={() => toggleOption(option)}
            onFocus={() => setSelectedIndex(index)}
            onKeyDown={onOptionKeyDown}
            className={clsx(
              { "font-bold": isIncluded(selectedValues, option) },
              "p-xs",
            )}
          >
            <Checkbox
              value={isIncluded(selectedValues, option)}
              className="pointer-events-none"
              tabIndex={-1}
              aria-hidden="true"
            />
            {getLabel(option)}
          </Option>
        ))
      )}
    </div>
  );

  const actionsNode = showAddButton ? (
    <div className="flex justify-center w-full">
      <Button size="small" round={true} alwaysOpen={true} onClick={addCreatableOption}>
        Add
      </Button>
    </div>
  ) : undefined;

  const iconNode = icon ? (
    <Icon name={icon} className={styles.nodeIcon} />
  ) : undefined;

  return (
    <SelectContainer
      value={expanded}
      onChange={(val) => setIsOpen(val)}
      labelValue={buttonLabel ?? labelValue}
      ariaLabel={ariaLabel}
      ariaMultiselectable
      disabled={disabled}
      isError={isError}
      errorMessage={errorMessage}
      infoMessage={infoMessage}
      required={required}
      absolute={absolute}
      maxHeight="none"
      minWidth="12em"
      leadingComplement={iconNode}
      options={optionsNode}
      actions={actionsNode}
      className={clsx("tag-select", className)}
      onKeyDown={onKeyDown}
    >
      {statusNode}
    </SelectContainer>
  );
}

// src/components/TagSelect/TagSelect.vue
<script setup lang="ts">
import { ref, watch } from "vue";
import { useOptionalModel } from "#composables";
import { type ContainerModelExtra } from "../../utils/types/ContainerModelExtra";
import SelectContent from "../../utils/components/SelectContent.vue";
import Option from "../../utils/components/Option.vue";
import { computed } from "vue";
import { isObject } from "../../utils";
import SelectContainer from "../../utils/components/SelectContainer.vue";

type SelectExpandedExtra = {
  source: ContainerModelExtra["source"] | "value-selected";
};

const props = withDefaults(
  defineProps<{
    modelValue?: any[];
    options?: any[];
    labelValue?: string;
    icon?: string;
    expanded?: boolean;
    labelKey?: string;
    errorMessage?: string;
    infoMessage?: string;
    disabled?: boolean;
    required?: boolean;
    isError?: boolean;
    buttonLabel?: string;
  }>(),
  {
    modelValue: undefined,
    options: undefined,
    labelValue: "",
    errorMessage: "",
    expanded: false,
    labelKey: "label",
    infoMessage: "",
    disabled: false,
    required: false,
    isError: false,
    buttonLabel: "Add",
  }
);

const emit = defineEmits<{
  "update:modelValue": [value: any[]];
  "update:options": [value: any[]];
  "update:expanded": [value: boolean, extra: SelectExpandedExtra];
}>();

const [model, setModel] = useOptionalModel<any>(props, "modelValue", emit, []);
model.value = model.value || [];
const [optionsModel, setOptionsModel] = useOptionalModel<any>(
  props,
  "options",
  emit,
  []
);

const expandedModel = ref(props.expanded);
const searchText = ref("");
const selectedIndex = ref<number | null>(null);
const optionRefs = ref<HTMLElement[]>([]);

const searchedOptions = computed((): any[] => {
  if (!searchText.value) {
    return optionsModel.value;
  }
  return optionsModel.value.filter((option: any) => {
    if (isObject(option)) {
      if (
        option[props.labelKey]
          ?.toLowerCase()
          ?.includes(searchText.value.toLowerCase())
      ) {
        return option;
      }
    } else if (option?.toLowerCase()?.includes(searchText.value.toLowerCase()))
      return option;
  });
});

watch(
  () => props.expanded,
  () => {
    expandedModel.value = props.expanded;
  }
);

watch(expandedModel, (value) => {
  if (!value) selectedIndex.value = null;
});

watch(searchText, () => {
  selectedIndex.value = null;
});

watch(
  selectedIndex,
  (index) => {
    if (index == null) return;
    optionRefs.value[index]?.focus();
  },
  { flush: "post" }
);

function addTag(tag: string) {
  if (props.isError || !tag) return;

  if (isIncluded(optionsModel.value, tag)) {
    searchText.value = "";
    return;
  }

  optionsModel.value.push(tag);
  setOptionsModel(optionsModel.value, { index: optionsModel.value.length - 1 });
  searchText.value = "";
}

function removeTag(index: number) {
  model.value.splice(index, 1);
  setModel(model.value, { index: index });
}

function onKeyDown(e: KeyboardEvent) {
  const last = searchedOptions.value.length - 1;
  if (last < 0) return;

  const hasSelection = selectedIndex.value != null;
  switch (e.key) {
    case "ArrowUp":
      e.preventDefault();
      if (!expandedModel.value) changeExpanded(true, { source: "click" });
      selectedIndex.value = hasSelection
        ? Math.max(selectedIndex.value! - 1, 0)
        : last;
      break;
    case "ArrowDown":
      e.preventDefault();
      if (!expandedModel.value) changeExpanded(true, { source: "click" });
      selectedIndex.value = hasSelection
        ? Math.min(selectedIndex.value! + 1, last)
        : 0;
      break;
  }
}

function onOptionKeyDown(e: KeyboardEvent) {
  switch (e.key) {
    case " ":
      e.preventDefault();
      break;
    case "Home":
      e.preventDefault();
      selectedIndex.value = 0;
      break;
    case "End":
      e.preventDefault();
      selectedIndex.value = searchedOptions.value.length - 1;
      break;
    default:
      onKeyDown(e);
  }
}

function selectOption(option: any, index: number) {
  if (props.disabled || isIncluded(model.value, option)) return;
  setModel([...model.value, option], index);
  expandedModel.value = false;
  emit("update:expanded", false, { source: "value-selected" });
}

function isIncluded(options: any, option: any) {
  if (isObject(option)) {
    return options.find((i: any) => i[props.labelKey] === option[props.labelKey]);
  }
  return options?.includes(option);
}

function changeExpanded(value: boolean, extra: any) {
  expandedModel.value = value;
  emit("update:expanded", value, extra);
}

function checkSource(value: boolean, extra: any) {
  if (extra?.source == "click") changeExpanded(true, extra);
  else changeExpanded(value, extra);
}
</script>

<template>
  <SelectContainer
    class="tag-select"
    v-model="expandedModel"
    :required="required"
    :label-value="labelValue"
    :disabled="disabled"
    :is-error="isError"
    :error-message="errorMessage"
    :info-message="infoMessage"
    max-height="none"
    min-width="12em"
    @keydown="onKeyDown"
    @click="changeExpanded(true, { source: 'click' })"
    @update:model-value="checkSource"
  >
    <SelectContent
      v-model="searchText"
      v-model:expanded="expandedModel"
      :disabled="disabled"
      :icon="icon"
      :options="options"
      :is-error="isError"
      @update:expanded="changeExpanded"
    >
      <template #search-label>
        <slot name="search-label">Search</slot>
      </template>
      <template #status>
        <slot
          v-if="$slots.default && !expandedModel && !modelValue?.length"
        />
        <div
          class="relative"
          v-else-if="expandedModel || !modelValue?.length"
        >
          <div v-show="!searchText.length" class="pointer-events-none w-0 h-0">
            <span
              class="absolute text-neutral-foreground-low top-[50%] translate-y-[-50%]"
              :class="{ 'text-danger-foreground-low': isError }"
            >
              <slot name="search-label">Search</slot>
            </span>
          </div>
          <input
            v-model="searchText"
            type="text"
            class="search"
            @keydown.enter="addTag(searchText)"
            @keydown.prevent.tab="addTag(searchText)"
            style="--tw-ring-color: none !important"
            :disabled="disabled"
            :class="{
              'text-danger-foreground-low': isError,
              'bg-neutral-surface-disabled text-neutral-foreground-low':
                disabled,
            }"
          />
        </div>
        <div class="flex flex-wrap gap-xxs my-xs max-w-[40em]" v-else>
          <StatusBadge
            color="neutral"
            class="tag"
            v-for="(option, index) in model"
            :key="index"
            closeable
            @close="removeTag(Number(index))"
          >
            <div class="tag-default py-xxs">
              <p class="font-bold text-xs truncate">
                {{ isObject(option) ? option[labelKey] : option }}
              </p>
            </div>
          </StatusBadge>
        </div>
      </template>
    </SelectContent>

    <template #options>
      <div
        class="text-xs italic text-neutral-foreground-low flex justify-center"
        v-if="!searchedOptions.length && searchText.length"
      >
        <slot name="no-options-found"> No result found </slot>
      </div>
      <div
        class="text-xs italic text-neutral-foreground-low flex justify-center"
        v-else-if="!optionsModel.length"
      >
        <slot name="empty-state"> No tags created yet </slot>
      </div>
      <template v-else>
        <Option
          v-for="(option, index) in searchedOptions"
          :ref="(el: any) => (optionRefs[index] = el?.$el)"
          :aria-selected="isIncluded(model, option)"
          :key="`${isObject(option) ? option[labelKey] : option}`"
          :class="{ 'font-bold': isIncluded(model, option) }"
          @focus="selectedIndex = index"
          @click="selectOption(option, index)"
          @keydown="onOptionKeyDown"
          @keyup.enter.space="selectOption(option, index)"
        >
          <slot name="option" :option="option" :index="index">
            {{ isObject(option) ? option[labelKey] : option }}
          </slot>
        </Option>
      </template>
    </template>
    <template #actions>
      <div class="flex justify-center w-full">
        <Button @click="addTag(searchText)" round size="small" always-open>
          {{ buttonLabel }}
        </Button>
      </div>
    </template>
  </SelectContainer>
</template>

<style scoped>
@reference "../../assets/main.css";

.tag-default {
  @apply flex items-center gap-xs;
}

.search {
  @apply text-neutral-interaction-default h-full w-full bg-neutral-surface-default p-none m-none border-none shadow-none outline-none p3;
}

.tag {
  @apply py-none max-w-full;
}
</style>
