// src/components/RadioGroup/RadioGroup.vue
<script setup lang="ts">
import Group from "../../utils/components/Group.vue";
import { focusByArrowKey, getFocusableItems, isObject } from "../../utils";
import { ref, watch } from "vue";

const props = withDefaults(
  defineProps<{
    modelValue?: any;
    vertical?: boolean;
    disabled?: boolean;
    options: any[];
    labelKey?: string;
    valueKey?: string;
    getObject?: boolean;
  }>(),
  {
    modelValue: null,
    vertical: false,
    disabled: false,
    labelKey: "label",
    valueKey: "value",
    getObject: false,
  }
);

const emit = defineEmits<{
  "update:modelValue": [value: any];
}>();

const model = ref<any>(getValue(props.modelValue));

watch(
  () => props.modelValue,
  (newVal) => {
    model.value = getValue(newVal);
  }
);

function setModel(value: string) {
  let valueToEmit = value;
  model.value = value;
  if (props.getObject) {
    const object = props.options.find((option: any) => getValue(option) === value);
    valueToEmit = object;
  }
  emit("update:modelValue", valueToEmit);
}

function getLabel(value: any): string {
  return isObject(value) ? value[props.labelKey] : value;
}

function getValue(option: any): any {
  return isObject(option) ? option[props.valueKey] : option;
}

function getDisabled(option: any): boolean {
  return isObject(option) ? option.disabled : false;
}

function onKeyDown(event: KeyboardEvent) {
  focusByArrowKey(
    event,
    getFocusableItems(event.currentTarget as HTMLElement, ".out-circle"),
    props.vertical ? "vertical" : "horizontal"
  );
}
</script>

<template>
  <Group
    v-model="model"
    :vertical="vertical"
    :disabled="disabled"
    class="radio-group"
    role="radiogroup"
    @update:model-value="setModel"
    @keydown="onKeyDown"
  >
    <Radio
      v-for="option in options"
      :key="getValue(option)"
      :group-value="getValue(option)"
      :disabled="getDisabled(option)"
    >
      <slot :name="getValue(option)" :option="option">
        {{ getLabel(option) }}
      </slot>
    </Radio>
  </Group>
</template>

<style scoped>
@reference "../../assets/main.css";

.radio-group.hor .radio {
  @apply ml-sm first:ml-none;
}

.radio-group.vert .radio {
  @apply mt-sm first:mt-none;
}
</style>

// src/components/RadioGroup/RadioGroup.tsx
import { createContext } from 'react';
import clsx from 'clsx';
import { useControllable } from '../../hooks/useControllable';
import { isObject, focusByArrowKey, getFocusableItems } from '../../utils';
import { Radio } from '../Radio/Radio';
import styles from './RadioGroup.module.css';

export interface RadioGroupContextValue {
  selected: any;
  disabled: boolean;
  select: (value: any) => void;
}

export const RadioGroupContext = createContext<RadioGroupContextValue | null>(null);

export interface RadioGroupProps {
  value?: any;
  onChange?: (value: any) => void;
  vertical?: boolean;
  disabled?: boolean;
  options?: Array<any>;
  labelKey?: string;
  valueKey?: string;
  getObject?: boolean;
  children?: React.ReactNode;
  className?: string;
}

export function RadioGroup({
  value,
  onChange,
  vertical = false,
  disabled = false,
  options,
  labelKey = 'label',
  valueKey = 'value',
  getObject = false,
  children,
  className,
}: RadioGroupProps) {
  const [currentValue, setValueInternal] = useControllable<any>({
    value,
    onChange,
  });

  function setValue(newValue: any) {
    if (getObject && options) {
      const object = options.find((opt) => getOptValue(opt) === newValue);
      if (object !== undefined) {
        setValueInternal(object);
        return;
      }
    }
    setValueInternal(newValue);
  }

  function getLabel(opt: any): string {
    return isObject(opt) ? (opt as Record<string, any>)[labelKey] : String(opt);
  }

  function getOptValue(opt: any): any {
    return isObject(opt) ? (opt as Record<string, any>)[valueKey] : opt;
  }

  function getDisabled(opt: any): boolean {
    return isObject(opt) ? ((opt as Record<string, any>).disabled ?? false) : false;
  }

  const contextSelected =
    getObject && isObject(currentValue)
      ? (currentValue as Record<string, any>)[valueKey]
      : currentValue;

  function handleKeyDown(e: React.KeyboardEvent<HTMLDivElement>) {
    const items = getFocusableItems(e.currentTarget, '[role="radio"]');
    focusByArrowKey(e, items, vertical ? 'vertical' : 'horizontal');
  }

  return (
    <RadioGroupContext.Provider
      value={{ selected: contextSelected, disabled, select: setValue }}
    >
      <div
        role="radiogroup"
        className={clsx(
          styles.radioGroup,
          'radio-group',
          vertical ? styles.vertical : styles.horizontal,
          className,
        )}
        onKeyDown={handleKeyDown}
      >
        {options
          ? options.map((opt) => {
              const optValue = getOptValue(opt);
              return (
                <Radio
                  key={optValue}
                  groupValue={optValue}
                  disabled={getDisabled(opt)}
                >
                  {getLabel(opt)}
                </Radio>
              );
            })
          : children}
      </div>
    </RadioGroupContext.Provider>
  );
}
