// src/utils/components/Container.tsx
import { useState, useEffect, useRef, useId } from 'react';
import clsx from 'clsx';
import { useControllable } from '../../hooks';
import { Label } from './Label';
import { Icon } from '../../components/Icon';
import type { ContainerModelExtra } from '../types/ContainerModelExtra';
import '../styles/Container.css';
import { FloatCard } from '../../components/FloatCard';

export interface ContainerProps {
  value?: boolean;
  onChange?: (value: boolean, extra: ContainerModelExtra) => void;
  labelValue?: string;
  popupRole?: 'listbox' | 'menu' | 'dialog';
  popupId?: string;
  ariaLabel?: string;
  disabled?: boolean;
  isError?: boolean;
  errorMessage?: string;
  infoMessage?: string;
  required?: boolean;
  closeOnBlur?: boolean;
  hideBottom?: boolean;
  maxHeight?: string;
  minWidth?: string;
  secondary?: boolean;
  hideArrow?: boolean;
  icon?: string;
  children?: React.ReactNode;
  label?: React.ReactNode;
  complement?: React.ReactNode;
  leadingComplement?: React.ReactNode;
  renderContent?: (minWidth: string) => React.ReactNode;
  className?: string;
  onKeyDown?: (e: React.KeyboardEvent) => void;
}

export function Container({
  value,
  onChange,
  labelValue = '',
  popupRole = 'listbox',
  popupId,
  ariaLabel,
  disabled = false,
  isError = false,
  errorMessage = '',
  infoMessage = '',
  required = false,
  closeOnBlur = true,
  hideBottom = false,
  maxHeight = 'none',
  minWidth = '15em',
  secondary = false,
  hideArrow = false,
  icon = 'keyboard_arrow_down',
  children,
  label,
  complement,
  leadingComplement,
  renderContent,
  className,
  onKeyDown: onKeyDownProp,
}: ContainerProps) {
  const [model, setModel] = useControllable<boolean>({
    value,
  });

  const isExpanded = disabled ? false : (model ?? false);

  const id = useId();
  const containerRef = useRef<HTMLDivElement>(null);
  const isCombobox = popupRole === 'listbox';

  const [contentMinWidth, setContentMinWidth] = useState(minWidth);

  function resize() {
    const newVal = (containerRef.current?.scrollWidth ?? 0) + 'px';
    if (newVal !== contentMinWidth) {
      setContentMinWidth(newVal);
    }
  }

  function blur(value: boolean) {
    if (closeOnBlur && model) {
      setModel(value)
      onChange?.(value, { source: 'blur' });
    } else {
      setModel(value)
      onChange?.(value, { source: 'click' });
    }
  }

  useEffect(() => {
    const obs = new MutationObserver(resize);
    if (containerRef.current) {
      obs.observe(containerRef.current, { attributes: true });
    }
    resize();
    return () => obs.disconnect();
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    resize();
  });

  function toggle() {
    if (disabled) return;
    setModel(!model);
    onChange?.(!model, { source: 'click' });
  }

  function onKeyDown(e: React.KeyboardEvent) {
    onKeyDownProp?.(e);
    if (label || e.target !== e.currentTarget) return;
    if (e.key !== 'Enter' && e.key !== ' ') return;
    e.preventDefault();
    toggle();
  }

  function onKeyUp(e: React.KeyboardEvent) {
    if (label || e.target !== e.currentTarget) return;
    if (e.key === 'Enter' || e.key === ' ') e.stopPropagation();
  }

  return (
    <div>
      <FloatCard value={isExpanded} disabled={disabled} manualFocus={true} card={renderContent?.(contentMinWidth)} onChange={blur}>
        <div className={clsx('container', className)}>
          {labelValue && (
            <div className="flex justify-between items-center">
              <Label id={`${id}-label`} labelValue={labelValue} infoMessage={infoMessage} required={required} />
            </div>
          )}
          <div
            ref={containerRef}
            role={isCombobox ? 'combobox' : 'button'}
            aria-haspopup={popupRole}
            aria-expanded={isExpanded}
            aria-controls={isExpanded ? popupId : undefined}
            aria-label={labelValue ? undefined : ariaLabel}
            aria-labelledby={labelValue ? `${id}-label` : undefined}
            aria-describedby={isError ? `${id}-error` : undefined}
            aria-invalid={isCombobox ? isError : undefined}
            aria-required={isCombobox ? required : undefined}
            aria-disabled={disabled || undefined}
            className="label-container"
            tabIndex={disabled ? -1 : 0}
            onKeyDown={onKeyDown}
            onKeyUp={onKeyUp}
          >
            {label || (
              <div
                className={clsx('label-content', {
                  disabled,
                  secondary,
                  expanded: isExpanded,
                  'hide-bottom': hideBottom,
                  error: isError,
                })}
                style={{ maxHeight, minWidth }}
                onClick={toggle}
              >
                {leadingComplement}
                {children}

                <div className="flex items-center gap-xs ml-auto">
                  {complement}
                  {!hideArrow && (
                    <Icon
                      name={icon}
                      className={clsx('arrow-icon', {
                        'text-neutral-interaction-disabled': disabled,
                        'text-danger-interaction-default': isError,
                        expanded: isExpanded,
                      })}
                    />
                  )}
                </div>
              </div>
            )}
          </div>
        </div>
      </FloatCard>
      {isError && (
        <small id={`${id}-error`} className="text-danger-foreground-low text-start p3">{errorMessage}</small>
      )}
    </div>
  );
}

// src/utils/components/Container.vue
<script setup lang="ts">
// @TODO: Fix border width for container with sub items
import { ref, onMounted, onUpdated, onBeforeUnmount, computed, useId } from "vue";
import type { ContainerModelExtra } from "../types/ContainerModelExtra";
import { useOptionalModel } from "#composables";
import Label from "./Label.vue";

const props = withDefaults(
  defineProps<{
    modelValue?: boolean;
    labelValue?: string;
    popupRole?: "listbox" | "menu" | "dialog";
    popupId?: string;
    ariaLabel?: string;
    disabled?: boolean;
    isError?: boolean;
    errorMessage?: string;
    infoMessage?: string;
    required?: boolean;
    closeOnBlur?: boolean;
    hideBottom?: boolean;
    maxHeight?: string;
    minWidth?: string;
    secondary?: boolean;
    hideArrow?: boolean;
    icon?: string;
  }>(),
  {
    modelValue: undefined,
    labelValue: "",
    popupRole: "listbox",
    popupId: undefined,
    ariaLabel: undefined,
    disabled: false,
    isError: false,
    errorMessage: "",
    infoMessage: "",
    required: false,
    hideBottom: false,
    closeOnBlur: true,
    maxHeight: "none",
    minWidth: "15em",
    secondary: false,
    hideArrow: false,
    icon: "keyboard_arrow_down",
  }
);

const mutationObserver = new MutationObserver(resize);

const emit = defineEmits<{
  "update:modelValue": [value: boolean, extra: ContainerModelExtra];
}>();

const [model, setModel] = useOptionalModel<boolean>(
  props,
  "modelValue",
  emit,
  false
);
const id = useId();
const container = ref<HTMLDivElement>();
const labelContent = ref<HTMLDivElement>();

const isExpanded = computed((): boolean =>
  props.disabled ? false : model.value
);

const contentMinWidth = ref(props.minWidth);

function blur(value: boolean) {
  const source = props.closeOnBlur && model.value ? "blur" : "click";
  setModel(value, { source });
}

function resize() {
  contentMinWidth.value = container.value?.scrollWidth + "px";
}

onMounted(() => {
  resize();
  if (container.value)
    mutationObserver.observe(container.value, { attributes: true });
});

onUpdated(resize);

onBeforeUnmount(() => {
  mutationObserver.disconnect();
});

function toggle() {
  if (props.disabled) return;

  setModel(!model.value, { source: "click" });
}

function onKeyDown(e: KeyboardEvent) {
  if (!labelContent.value || e.target !== e.currentTarget) return;
  if (e.key !== "Enter" && e.key !== " ") return;

  e.preventDefault();
  toggle();
}

function onKeyUp(e: KeyboardEvent) {
  if (!labelContent.value || e.target !== e.currentTarget) return;
  if (e.key === "Enter" || e.key === " ") e.stopPropagation();
}
</script>

<template>
  <FloatCard :model-value="isExpanded" :disabled="disabled" manual-focus @update:model-value="blur">
    <div class="container">
      <div v-if="labelValue" class="flex justify-between items-center">
        <Label
          :id="`${id}-label`"
          :label-value="labelValue"
          :info-message="infoMessage"
          :required="required"
        />
      </div>
      <div
        ref="container"
        :role="popupRole === 'listbox' ? 'combobox' : 'button'"
        :aria-haspopup="popupRole"
        :aria-expanded="isExpanded"
        :aria-controls="isExpanded ? popupId : undefined"
        :aria-label="labelValue ? undefined : ariaLabel"
        :aria-labelledby="labelValue ? `${id}-label` : undefined"
        :aria-describedby="isError ? `${id}-error` : undefined"
        :aria-invalid="popupRole === 'listbox' ? isError : undefined"
        :aria-required="popupRole === 'listbox' ? required : undefined"
        :aria-disabled="disabled"
        class="label-container"
        :class="{ 'pointer-events-none': disabled }"
        :tabindex="disabled ? -1 : 0"
        @keydown="onKeyDown"
        @keyup="onKeyUp"
      >
        <slot name="label">
          <div
            ref="labelContent"
            class="label-content"
            :class="{
              disabled,
              secondary,
              expanded: isExpanded,
              'hide-bottom': hideBottom,
              error: isError,
            }"
            :style="{ 'max-height': maxHeight, 'min-width': minWidth }"
            @click="toggle"
          >
            <slot name="leading-complement" />
            <slot />

            <div class="flex items-center gap-xs ml-auto">
              <slot name="complement" />
              <Icon
                v-if="!hideArrow"
                :name="icon"
                class="arrow-icon"
                :class="{
                  'text-neutral-interaction-disabled': disabled,
                  'text-danger-interaction-default': isError,
                  expanded: isExpanded,
                }"
              />
            </div>
          </div>
        </slot>
      </div>
      <small v-if="isError" :id="`${id}-error`" class="text-danger-foreground-low text-start p3">{{
        errorMessage
      }}</small>
    </div>

    <template #card>
      <slot name="content" :min-width="contentMinWidth" />
    </template>
  </FloatCard>
</template>

<style scoped>
@reference "../../assets/main.css";

.container {
  @apply relative flex flex-col gap-xxs;
}

.label-container {
  @apply w-fit relative;
}

.label-content {
  @apply inline-flex items-center gap-xs outline-xxs rounded-sm cursor-pointer px-sm py-xs select-none transition-[outline,border-radius] p3
    duration-0 delay-100 text-neutral-interaction-default bg-neutral-surface-default outline-neutral-default focus:outline-primary-default;
}

.secondary.label-content {
  @apply bg-primary-interaction-default text-neutral-foreground-negative;
}

.expanded.label-content {
  @apply delay-0 outline-primary-default;
}

.expanded.label-content.hide-bottom {
  @apply rounded-none outline-neutral-default focus:outline-neutral-default;
}

.label-content.disabled {
  @apply bg-neutral-surface-disabled text-neutral-foreground-disabled;
}

.label-content.error {
  @apply text-danger-foreground-high outline-danger-default;
}

.arrow-icon {
  @apply shrink-0 flex items-center transition-transform duration-300 text-lg leading-(--font-size-xl);
}

.arrow-icon.expanded {
  @apply rotate-180;
}
</style>
