// src/components/ExpandableContainer/ExpandableContainer.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import type { ContainerModelExtra } from "../../utils/components/ContainerModelExtra.types.ts";
import Container from "../../utils/components/Container.vue";
import { useOptionalModel } from "#composables";

const props = withDefaults(
  defineProps<{
    modelValue?: boolean;
    labelValue?: string;
    absolute?: boolean;
    disabled?: boolean;
    isError?: boolean;
    errorMessage?: string;
    infoMessage?: string;
    required?: boolean;
    closeOnBlur?: boolean;
    alignRight?: boolean;
    maxHeight?: string;
    minWidth?: string;
    minWidthCard?: string;
    secondary?: boolean;
    hideArrow?: boolean;
    disableLabelAutoWidth?: boolean;
  }>(),
  {
    modelValue: undefined,
    labelValue: "",
    absolute: false,
    disabled: false,
    errorMessage: "",
    infoMessage: "",
    isError: false,
    required: false,
    alignRight: false,
    closeOnBlur: true,
    maxHeight: "40px",
    minWidth: "unset",
    secondary: false,
    hideArrow: false,
    disableLabelAutoWidth: false,
  }
);

const emit = defineEmits<{
  "update:modelValue": [value: boolean, extra: ContainerModelExtra];
}>();

const [model, setModel] = useOptionalModel<boolean>(
  props,
  "modelValue",
  emit,
  false
);
const content = ref<HTMLDivElement>();

const isExpanded = computed((): boolean =>
  props.disabled ? false : model.value
);
const isAbsolute = computed((): boolean =>
  isExpanded.value ? props.absolute : true
);

function changeModel(value: boolean, extra: ContainerModelExtra) {
  setModel(value, extra);
}
</script>

<template>
  <Container
    class="expandable-container"
    v-model="model"
    :label-value="labelValue"
    :close-on-blur="closeOnBlur"
    :disabled="disabled"
    :is-error="isError"
    :error-message="errorMessage"
    :info-message="infoMessage"
    :required="required"
    :max-height="maxHeight"
    :min-width="minWidth"
    :secondary="secondary"
    :hide-arrow="hideArrow"
    :disable-label-auto-width="disableLabelAutoWidth"
    @update:model-value="changeModel"
  >
    <slot />

    <template #complement v-if="$slots.complement">
      <slot name="complement" />
    </template>

    <template #label v-if="$slots.label">
      <slot name="label" />
    </template>

    <template #content="{ minWidth }">
      <div
        v-show="isExpanded"
        ref="content"
        class="content-wrapper text-xs top-full transition-[max-height] w-fit duration-100"
        :class="[
          {
            'absolute z-[80]': isAbsolute,
            'max-h-fit': isExpanded,
            'left-0': !alignRight,
            'right-0': alignRight,
          },
        ]"
        :style="{ 'min-width': minWidth }"
      >
        <div
          class="content translate-y-[-100%] transition-translate duration-100 ease-out mt-xs"
          :class="[{ 'translate-y-[0]': isExpanded }]"
        >
          <slot name="card">
            <div
              class="bg-neutral-surface-default shadow-neutral-selected border-xxs border-neutral-default rounded-sm"
            >
              <slot name="content" />
            </div>
          </slot>
        </div>
      </div>
    </template>
  </Container>
</template>

// src/utils/components/ExpandableContainer.tsx
import clsx from 'clsx';
import { useControllable } from '../../hooks';
import { Container } from './Container';
import type { ContainerModelExtra } from '../types/ContainerModelExtra';

export interface ExpandableContainerProps {
  value?: boolean;              // was modelValue
  defaultValue?: boolean;
  onChange?: (value: boolean, extra: ContainerModelExtra) => void;
  labelValue?: string;          // default: ''
  absolute?: boolean;           // default: true
  disabled?: boolean;           // default: false
  isError?: boolean;            // default: false
  errorMessage?: string;        // default: ''
  infoMessage?: string;         // default: ''
  required?: boolean;           // default: false
  closeOnBlur?: boolean;        // default: true
  alignRight?: boolean;         // default: false
  maxHeight?: string;           // default: '40px'
  minWidth?: string;            // default: 'unset'
  minWidthCard?: string;
  secondary?: boolean;          // default: false
  hideArrow?: boolean;          // default: false
  disableLabelAutoWidth?: boolean; // default: false
  children?: React.ReactNode;       // default slot
  complement?: React.ReactNode;     // complement slot
  label?: React.ReactNode;          // label slot
  card?: React.ReactNode;           // card slot (replaces <slot name="card">)
  content?: React.ReactNode;        // content slot inside card (replaces <slot name="content">)
  className?: string;
}

export function ExpandableContainer({
  value,
  defaultValue,
  onChange,
  labelValue = '',
  absolute = true,
  disabled = false,
  isError = false,
  errorMessage = '',
  infoMessage = '',
  required = false,
  closeOnBlur = true,
  alignRight = false,
  maxHeight = '40px',
  minWidth = 'unset',
  secondary = false,
  hideArrow = false,
  disableLabelAutoWidth = false,
  children,
  complement,
  label,
  card,
  content,
  className,
}: ExpandableContainerProps) {
  const [model, setModel] = useControllable<boolean>({
    value,
    defaultValue,
    onChange: (val) => onChange?.(val, { source: 'click' }),
  });

  const isExpanded = disabled ? false : (model ?? false);
  // absolute defaults to true so dropdowns float by default.
  // isAbsolute simply reflects the absolute prop — content is always rendered
  // (CSS visibility/opacity toggle) so transitions work regardless of expanded state.
  const isAbsolute = absolute;

  function changeModel(val: boolean, extra: ContainerModelExtra) {
    setModel(val);
    onChange?.(val, extra);
  }

  return (
    <Container
      className={clsx('expandable-container', className)}
      value={model}
      onChange={changeModel}
      labelValue={labelValue}
      closeOnBlur={closeOnBlur}
      disabled={disabled}
      isError={isError}
      errorMessage={errorMessage}
      infoMessage={infoMessage}
      required={required}
      maxHeight={maxHeight}
      minWidth={minWidth}
      secondary={secondary}
      hideArrow={hideArrow}
      disableLabelAutoWidth={disableLabelAutoWidth}
      label={label}
      complement={complement}
      renderContent={(contentMinWidth) => (
        <div
          className={clsx('text-xs top-full w-fit mt-xs', {
            'absolute z-[80]': isAbsolute,
            'left-0': !alignRight,
            'right-0': alignRight,
            'opacity-100 visible': isExpanded,
            'opacity-0 invisible pointer-events-none': !isExpanded,
          })}
          style={{
            minWidth: contentMinWidth,
            transition: 'opacity 150ms ease, visibility 150ms ease',
          }}
        >
          {card || (
            <div className="bg-neutral-surface-default shadow-neutral-selected border-xxs border-neutral-default rounded-sm">
              {content}
            </div>
          )}
        </div>
      )}
    >
      {children}
    </Container>
  );
}
