// src/utils/components/SelectContent.tsx
import { useEffect, useRef } from 'react';
import clsx from 'clsx';
import { useControllable } from '../../hooks';
import { Icon } from '../../components/Icon';
import type { ContainerModelExtra } from '../types/ContainerModelExtra';
import '../styles/SelectContent.css';

export type SelectExpandedExtra = {
  source: ContainerModelExtra['source'] | 'value-selected';
};

export interface SelectContentProps {
  value?: string;
  onChange?: (value: string, extra: { index: number }) => void;
  options?: any;
  icon?: string;
  expanded?: boolean;
  onExpandedChange?: (value: boolean, extra: SelectExpandedExtra) => void;
  searchable?: boolean;
  disabled?: boolean;
  isError?: boolean;
  secondary?: boolean;
  searchLabel?: React.ReactNode;
  status?: React.ReactNode;
  appendIcon?: string;
  className?: string;
}

export function SelectContent({
  value,
  onChange,
  options,
  icon,
  expanded,
  onExpandedChange,
  searchable = false,
  disabled = false,
  isError = false,
  secondary = false,
  searchLabel,
  status,
  appendIcon,
  className,
}: SelectContentProps) {
  const [model, setModel] = useControllable<string>({
    value,
    defaultValue: '',
    onChange: (val) => onChange?.(val, { index: -1 }),
  });

  const [expandedModel, setExpandedModel] = useControllable<boolean>({
    value: expanded,
    defaultValue: false,
    onChange: (val) => onExpandedChange?.(val, { source: 'click' }),
  });

  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (expanded && !disabled && inputRef.current) {
      inputRef.current.focus();
    }
  }, [expanded, disabled]);

  return (
    <>
      {icon && (
        <Icon
          name={icon}
          className={clsx('sc-icon', {
            expanded: expandedModel,
            disabled,
            error: isError,
          })}
        />
      )}
      <span
        className={clsx('flex items-center gap-xs truncate text-sm flex-1', className, {
          'text-neutral-foreground-low': !options,
        })}
      >
        {searchable && !disabled && (
          <div
            className={clsx('flex items-center text-neutral-foreground-high w-full', {
              secondary,
              hidden: !expandedModel,
            })}
            onClick={() => setExpandedModel(true)}
          >
            <Icon
              name="search"
              className={clsx('sc-icon', { expanded: expandedModel, disabled, error: isError })}
            />
            {!model?.length && (
              <div className="relative pointer-events-none">
                <span className="search-placeholder">
                  {searchLabel || 'Search'}
                </span>
              </div>
            )}
            <input
              ref={inputRef}
              type="search"
              className="search"
              disabled={disabled}
              value={model ?? ''}
              onChange={(e) => setModel(e.target.value)}
            />
            {appendIcon && (
              <Icon
                name={appendIcon}
                className={clsx('sc-icon', { expanded: expandedModel, disabled, error: isError })}
              />
            )}
          </div>
        )}
        {status}
      </span>
    </>
  );
}

// src/utils/components/SelectContent.vue
<script setup lang="ts">
import { ref, watch, nextTick } from "vue";
import { useOptionalModel } from "#composables";
import { type ContainerModelExtra } from "../types/ContainerModelExtra";

type SelectExpandedExtra = {
  source: ContainerModelExtra["source"] | "value-selected";
};

const props = withDefaults(
  defineProps<{
    modelValue?: string;
    options: any;
    icon?: string;
    expanded?: boolean;
    searchable?: boolean;
    disabled?: boolean;
    isError?: boolean;
    secondary?: boolean;
  }>(),
  {
    modelValue: "",
    expanded: undefined,
    searchable: false,
    disabled: false,
    secondary: false,
    isError: false,
  }
);

const emit = defineEmits<{
  "update:modelValue": [value: any, extra: { index: number }];
  "update:expanded": [value: boolean, extra: SelectExpandedExtra];
}>();

const [model] = useOptionalModel<string>(props, "modelValue", emit, "");
const [expandedModel, setExpandedModel] = useOptionalModel<boolean>(
  props,
  "expanded",
  emit,
  false
);
const inputRef = ref<HTMLInputElement>();

watch(
  () => props.expanded,
  () => {
    if (!props.expanded || props.disabled) return;

    nextTick(() => {
      if (!inputRef.value) return;

      inputRef.value.focus();
    });
  }
);
</script>

<template>
  <Icon
    v-if="icon"
    :name="icon"
    class="icon shrink-0"
    :class="{ expanded: expandedModel, disabled, error: isError }"
  />
  <span
    class="flex items-center gap-xs truncate text-sm"
    :class="{ 'text-neutral-foreground-low': !options }"
  >
    <div
      v-if="searchable && !disabled"
      class="flex items-center text-neutral-foreground-high"
      :class="{ secondary, hidden: !expandedModel }"
      @click="setExpandedModel(true, { source: 'click' })"
    >
      <Icon name="search" class="icon" :class="{ expanded: expandedModel, disabled, error: isError }" />
      <div v-show="!model.length" class="relative pointer-events-none">
        <span class="search-placeholder">
          <slot name="search-label">Search</slot>
        </span>
      </div>
      <input
        v-model="model"
        ref="inputRef"
        type="search"
        class="search"
        :disabled="disabled"
      />
    </div>
    <slot name="status" />
  </span>
</template>
<style scoped>
@reference "../../assets/main.css";

.search {
  @apply h-full w-full pl-xxs p-0 m-0 border-none shadow-none outline-none text-xs;
}

.secondary .search {
  @apply bg-primary-interaction-default text-neutral-foreground-negative placeholder:text-neutral-foreground-negative;
}

.icon.icon {
  @apply text-neutral-interaction-default text-base;
}

.secondary .icon.icon {
  @apply text-neutral-foreground-negative;
}

.icon.icon.expanded {
  @apply text-primary-interaction-default;
}

.icon.icon.disabled {
  @apply text-neutral-interaction-disabled;
}

.icon.icon.error {
  @apply text-danger-interaction-default;
}

.search-placeholder {
  @apply absolute text-neutral-foreground-low left-[.5em] top-[50%] translate-y-[-50%];
}

.secondary .search-placeholder {
  @apply text-neutral-foreground-negative;
}
</style>
