// src/utils/components/SelectContainer.vue
<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, onUpdated, computed, useId } from "vue";
import type { ContainerModelExtra } from "../types/ContainerModelExtra";
import { useOptionalModel } from "#composables";
import ExpandableContainer from "./ExpandableContainer.vue";

const props = withDefaults(
  defineProps<{
    modelValue?: boolean;
    labelValue?: string;
    popupRole?: "listbox" | "menu" | "dialog";
    ariaMultiselectable?: boolean | "true" | "false";
    ariaLabel?: string;
    disabled?: boolean;
    isError?: boolean;
    errorMessage?: string;
    infoMessage?: string;
    required?: boolean;
    closeOnBlur?: boolean;
    dontHaveMaxHeight?: boolean;
    maxHeight?: string;
    minWidth?: string;
    secondary?: boolean;
    hideArrow?: boolean;
    icon?: string;
  }>(),
  {
    modelValue: undefined,
    labelValue: "",
    popupRole: "listbox",
    ariaMultiselectable: undefined,
    ariaLabel: undefined,
    disabled: false,
    isError: false,
    errorMessage: "",
    infoMessage: "",
    required: false,
    closeOnBlur: true,
    dontHaveMaxHeight: false,
    maxHeight: "40px",
    minWidth: "15em",
    secondary: false,
    hideArrow: false,
  }
);

const emit = defineEmits<{
  "update:modelValue": [value: boolean, extra: ContainerModelExtra];
}>();

const [model, setModel] = useOptionalModel<boolean>(
  props,
  "modelValue",
  emit,
  false
);
const popupId = useId();
const container = ref<HTMLDivElement>();
const fatherContainer = ref<HTMLDivElement>();
const content = ref<HTMLDivElement>();
const resizeObserver = new ResizeObserver(resize);
const mutationObserver = new MutationObserver(resize);

const isExpanded = computed((): boolean =>
  props.disabled ? false : model.value
);

onMounted(() => {
  if (!fatherContainer.value) return;
  container.value = fatherContainer.value.querySelector(
    ".label-container"
  ) as HTMLDivElement;

  if (container.value) {
    mutationObserver.observe(container.value, {
      characterData: true,
      subtree: true,
      childList: true,
    });
    resizeObserver.observe(container.value, { box: "border-box" });
  }
  if (content.value)
    resizeObserver.observe(content.value, { box: "border-box" });

  setTimeout(() => {
    resize();
  }, 200);
});

onUpdated(resize);

onBeforeUnmount(() => {
  if (resizeObserver) resizeObserver.disconnect();
});

function resize() {
  if (!content.value) return;

  content.value.style.maxHeight = isExpanded.value
    ? `${content.value.scrollHeight + 1}px`
    : "0px";
}

function changeModel(value: boolean, extra: ContainerModelExtra) {
  setModel(value, extra || {});
}
</script>

<template>
  <div ref="fatherContainer">
    <ExpandableContainer class="select-container" v-model="model" :label-value="labelValue"
      :close-on-blur="closeOnBlur" :disabled="disabled" :is-error="isError" :error-message="errorMessage"
      :info-message="infoMessage" :required="required" :max-height="maxHeight" :min-width="minWidth"
      :secondary="secondary" :hide-arrow="hideArrow" :icon="icon" :popup-role="popupRole"
      :popup-id="popupRole === 'listbox' && !$slots.content ? popupId : undefined" :aria-label="ariaLabel"
      @update:model-value="changeModel">
      <slot />

      <template #leading-complement v-if="$slots['leading-complement']">
        <slot name="leading-complement" />
      </template>

      <template #complement v-if="$slots.complement">
        <slot name="complement" />
      </template>

      <template #label v-if="$slots.label">
        <slot name="label" />
      </template>

      <template #content>
        <div class="content transition-translate" :class="{
          secondary,
          expanded: isExpanded,
          'has-max-height': !dontHaveMaxHeight,
        }">
          <slot name="content">
            <ul
              :id="popupId"
              :role="popupRole === 'listbox' ? 'listbox' : 'none'"
              :aria-label="popupRole === 'listbox' ? labelValue || ariaLabel : undefined"
              :aria-multiselectable="popupRole === 'listbox' ? ariaMultiselectable : undefined"
              class="options-list" :class="[{ 'p-xxs [&>*]:p-xs': !dontHaveMaxHeight }]">
              <slot name="options" />
            </ul>
          </slot>

          <div v-if="$slots.actions" class="actions">
            <slot name="actions" />
          </div>
        </div>
      </template>
    </ExpandableContainer>
  </div>
</template>

<style scoped>
@reference "../../assets/main.css";

.content {
  @apply overflow-hidden flex flex-col items-center translate-y-[-100%] duration-100 ease-out rounded-sm text-xs;
}

.content.secondary {
  @apply bg-primary-interaction-default text-neutral-foreground-negative;

  .options-list::-webkit-scrollbar-thumb {
    @apply bg-primary-surface-pressed;
  }

  .options-list::-webkit-scrollbar {
    @apply bg-primary-surface-default;
  }
}

.content.expanded {
  @apply translate-y-[0];
}

.content.has-max-height {
  @apply max-h-[12em];
}

.options-list {
  @apply overflow-auto rounded-sm w-full;
}

.actions {
  @apply flex gap-xxs items-center justify-end p-xs w-full border-t-xxs border-neutral-default;
}
</style>

// src/utils/components/SelectContainer.tsx
import { useEffect, useRef, useId } from 'react';
import clsx from 'clsx';
import { useControllable } from '../../hooks';
import { ExpandableContainer } from './ExpandableContainer';
import type { ContainerModelExtra } from '../types/ContainerModelExtra';
import '../styles/SelectContainer.css';

export interface SelectContainerProps {
  value?: boolean;
  onChange?: (value: boolean, extra: ContainerModelExtra) => void;
  labelValue?: string;
  popupRole?: 'listbox' | 'menu' | 'dialog';
  ariaMultiselectable?: boolean;
  ariaLabel?: string;
  absolute?: boolean;
  disabled?: boolean;
  isError?: boolean;
  errorMessage?: string;
  infoMessage?: string;
  required?: boolean;
  closeOnBlur?: boolean;
  dontHaveMaxHeight?: boolean;
  maxHeight?: string;
  minWidth?: string;
  secondary?: boolean;
  hideArrow?: boolean;
  icon?: string;
  children?: React.ReactNode;
  complement?: React.ReactNode;
  leadingComplement?: React.ReactNode;
  label?: React.ReactNode;
  content?: React.ReactNode;
  options?: React.ReactNode;
  actions?: React.ReactNode;
  className?: string;
  onKeyDown?: (e: React.KeyboardEvent) => void;
}

export function SelectContainer({
  value,
  onChange,
  labelValue = '',
  absolute = false,
  popupRole = 'listbox',
  ariaMultiselectable,
  ariaLabel,
  disabled = false,
  isError = false,
  errorMessage = '',
  infoMessage = '',
  required = false,
  closeOnBlur = true,
  dontHaveMaxHeight = false,
  maxHeight = '40px',
  minWidth = '15em',
  secondary = false,
  hideArrow = false,
  icon,
  children,
  complement,
  leadingComplement,
  label,
  content,
  options,
  actions,
  className,
  onKeyDown,
}: SelectContainerProps) {
  const [model, setModel] = useControllable<boolean>({
    value,
  });

  const isExpanded = disabled ? false : (model ?? false);

  const isExpandedRef = useRef(isExpanded);
  isExpandedRef.current = isExpanded;

  const popupId = useId();
  const fatherRef = useRef<HTMLDivElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);

  function resize() {
    if (!contentRef.current) return;
    contentRef.current.style.maxHeight = isExpandedRef.current
      ? `${contentRef.current.scrollHeight + 1}px`
      : '0px';
  }

  useEffect(() => {
    const fatherEl = fatherRef.current;
    if (!fatherEl) return;
    const containerEl = fatherEl.querySelector('.label-container') as HTMLDivElement | null;
    const contentEl = contentRef.current;

    const resizeObs = new ResizeObserver(() => resize());
    const mutationObs = new MutationObserver(() => resize());

    if (containerEl) {
      mutationObs.observe(containerEl, { characterData: true, subtree: true, childList: true });
      resizeObs.observe(containerEl, { box: 'border-box' });
    }
    if (contentEl) resizeObs.observe(contentEl, { box: 'border-box' });

    const timer = setTimeout(() => resize(), 200);

    return () => {
      resizeObs.disconnect();
      mutationObs.disconnect();
      clearTimeout(timer);
    };
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    resize();
  });

  return (
    <div ref={fatherRef}>
      <ExpandableContainer
        className={clsx('select-container', className)}
        value={model}
        onChange={(val, extra) => {
          setModel(val);
          onChange?.(val, extra);
        }}
        absolute={absolute}
        labelValue={labelValue}
        closeOnBlur={closeOnBlur}
        disabled={disabled}
        isError={isError}
        errorMessage={errorMessage}
        infoMessage={infoMessage}
        required={required}
        maxHeight={maxHeight}
        minWidth={minWidth}
        secondary={secondary}
        hideArrow={hideArrow}
        popupRole={popupRole}
        popupId={popupRole === 'listbox' ? popupId : undefined}
        ariaLabel={ariaLabel}
        label={label}
        complement={complement}
        leadingComplement={leadingComplement}
        icon={icon}
        onKeyDown={onKeyDown}
        content={
          <div
            ref={contentRef}
            className="content-wrapper"
          >
            <div
              id={content ? popupId : undefined}
              className={clsx('sc-content', 'transition-translate', {
                secondary,
                expanded: isExpanded,
                'has-max-height': !dontHaveMaxHeight,
              })}
            >
              {content || (
                <ul
                  id={popupId}
                  role={popupRole === 'listbox' ? 'listbox' : 'none'}
                  aria-label={popupRole === 'listbox' ? labelValue || ariaLabel : undefined}
                  aria-multiselectable={popupRole === 'listbox' ? ariaMultiselectable : undefined}
                  className={clsx('options-list', {
                    'p-xxs [&>*]:p-xs': !dontHaveMaxHeight,
                  })}
                >
                  {options}
                </ul>
              )}

              {actions && (
                <div className="sc-actions">
                  {actions}
                </div>
              )}
            </div>
          </div>
        }
      >
        {children}
      </ExpandableContainer>
    </div>
  );
}
