// src/components/Breadcrumb/Breadcrumb.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { useOptionalModel } from "#composables";
import Option from "../../utils/components/Option.vue";
import { isObject } from "../../utils";

const props = withDefaults(
  defineProps<{
    modelValue: any;
    options?: any[];
    labelKey?: string;
    valueKey?: string;
    getObject?: boolean;
  }>(),
  {
    modelValue: undefined,
    options: undefined,
    labelKey: "label",
    valueKey: "value",
    getObject: false,
  }
);

const emit = defineEmits<{
  "update:modelValue": [value: any];
}>();

const [model] = useOptionalModel<any>(props, "modelValue", emit, undefined);
const expanded = ref<any[]>([]);

const parsedOptions = computed(() => {
  if (!props.options?.length) return [];

  const options = [...props.options];
  let selectedIndex = options.findIndex((option) => isActive(option));
  if (selectedIndex === -1) selectedIndex = 0;

  const result = [];

  for (let i = 0; i < options.length; i++) {
    if (
      i === 0 ||
      i === options.length - 1 ||
      (selectedIndex === 0 && i < 2) ||
      (selectedIndex === options.length - 1 && i >= options.length - 2) ||
      selectedIndex - 1 === i ||
      selectedIndex + 1 === i ||
      selectedIndex === i
    ) {
      result.push(options[i]);
    } else if (i === 1 && selectedIndex > 1) {
      result.push({
        icon: "more_horiz",
        options: options.slice(1, selectedIndex - 1)
      });
    } else if (i === options.length - 2 && selectedIndex < options.length - 2) {
      result.push({
        icon: "more_horiz",
        options: options.slice(selectedIndex + 2, options.length - 1)
      });
    }
  }

  return result;
});

function setModel(option: any) {
  const value = props.getObject ? option : getValue(option);
  expanded.value = expanded.value.map(() => false);

  setTimeout(() => {
    model.value = value;
    emit("update:modelValue", value);
  }, 200);
}

function getLabel(value: any): string {
  return isObject(value) ? value[props.labelKey] : value;
}

function getValue(option: any): any {
  return isObject(option) ? option[props.valueKey] : option;
}

function isActive(option: any): boolean {
  const value = getValue(option);
  const selectedValue = getValue(model.value);
  return selectedValue == value;
}
</script>

<template>
  <div class="breadcrumb">
    <template v-for="(option, index) in parsedOptions" :key="option">
      <div v-if="isObject(option) && option.icon == 'more_horiz'">
        <FloatCard v-model="expanded[index]" class="leading-none">
          <Icon name="more_horiz" class="cursor-pointer leading-xxs" />
            <template #card>
              <div class="more-options">
                <Option v-for="subOption in option.options" :key="subOption" @click="setModel(subOption)">
                  {{ getLabel(subOption) }}
                </Option>
              </div>
            </template>
        </FloatCard>
      </div>
      <h5
        v-else
        class="option"
        :class="{ active: isActive(option) }"
        @click="setModel(option)"
      >
        {{ getLabel(option) }}
      </h5>
      <Icon v-if="index < parsedOptions.length - 1" name="chevron_right" class="leading-xxs" />
    </template>
  </div>
</template>

<style scoped>
@reference "../../assets/main.css";

.breadcrumb {
  @apply flex items-center gap-xs;
}

.option {
  @apply text-neutral-interaction-default cursor-pointer hover:text-primary-interaction-hover;
}

.option.active {
  @apply pointer-events-none text-neutral-foreground-high;
}

.more-options {
  @apply overflow-auto min-w-9xl max-h-9xl p-xxs [&>*]:p-xs;
}

.fade-enter-active,
.fade-leave-active {
  @apply transition-opacity duration-200;
}

.fade-enter-from,
.fade-leave-to {
  @apply opacity-0;
}
</style>

// src/components/Breadcrumb/Breadcrumb.tsx
import { useState } from "react";
import clsx from "clsx";
import { Icon } from "../Icon/Icon";
import { FloatCard } from "../FloatCard/FloatCard";
import { useControllable } from "../../hooks/useControllable";
import { isObject } from "../../utils";
import styles from "./Breadcrumb.module.css";

export interface BreadcrumbProps {
  value?: any;
  onChange?: (value: any) => void;
  options?: any[];
  labelKey?: string;
  valueKey?: string;
  getObject?: boolean;
  className?: string;
}

export function Breadcrumb({
  value,
  onChange,
  options = [],
  labelKey = "label",
  valueKey = "value",
  getObject = false,
  className,
}: BreadcrumbProps) {
  const [model, setModel] = useControllable({
    value,
    onChange,
  });

  const [expanded, setExpanded] = useState<boolean[]>([]);

  function getLabel(val: any): string {
    return isObject(val) ? val[labelKey] : String(val);
  }

  function getValue(option: any): any {
    return isObject(option) ? option[valueKey] : option;
  }

  function isActive(option: any): boolean {
    const val = getValue(option);
    const selectedValue = getValue(model);
    return selectedValue == val;
  }

  function handleSelect(option: any) {
    const val = getObject ? option : getValue(option);
    setExpanded(expanded.map(() => false));
    setTimeout(() => {
      setModel(val);
    }, 200);
  }

  const parsedOptions = (() => {
    if (!options?.length) return [];

    const opts = [...options];
    let selectedIndex = opts.findIndex((option) => isActive(option));
    if (selectedIndex === -1) selectedIndex = 0;

    const result: any[] = [];

    for (let i = 0; i < opts.length; i++) {
      if (
        i === 0 ||
        i === opts.length - 1 ||
        (selectedIndex === 0 && i < 2) ||
        (selectedIndex === opts.length - 1 && i >= opts.length - 2) ||
        selectedIndex - 1 === i ||
        selectedIndex + 1 === i ||
        selectedIndex === i
      ) {
        result.push(opts[i]);
      } else if (i === 1 && selectedIndex > 1) {
        result.push({
          icon: "more_horiz",
          options: opts.slice(1, selectedIndex - 1),
        });
      } else if (i === opts.length - 2 && selectedIndex < opts.length - 2) {
        result.push({
          icon: "more_horiz",
          options: opts.slice(selectedIndex + 2, opts.length - 1),
        });
      }
    }

    return result;
  })();

  return (
    <div className={clsx(styles.breadcrumb, "breadcrumb", className)}>
      {parsedOptions.map((option, index) => (
        <span key={index} className={styles.itemWrapper}>
          {isObject(option) && option.icon === "more_horiz" ? (
            <FloatCard
              value={expanded[index]}
              onChange={(open: boolean) => {
                const next = [...expanded];
                next[index] = open;
                setExpanded(next);
              }}
              className="leading-none"
              card={
                <div className={styles.moreOptions}>
                  {option.options.map((subOption: any, subIndex: number) => (
                    <div
                      key={subIndex}
                      className={styles.subOption}
                      onClick={() => handleSelect(subOption)}
                    >
                      {getLabel(subOption)}
                    </div>
                  ))}
                </div>
              }
            >
              <Icon name="more_horiz" className={styles.moreIcon} />
            </FloatCard>
          ) : (
            <h5
              className={clsx(styles.option, isActive(option) && styles.active)}
              onClick={() => handleSelect(option)}
            >
              {getLabel(option)}
            </h5>
          )}
          {index < parsedOptions.length - 1 && (
            <Icon name="chevron_right" className="leading-xxs" />
          )}
        </span>
      ))}
    </div>
  );
}
