// src/components/Calendar/Calendar.vue
<script setup lang="ts">
import { ref, watch, onBeforeMount, computed } from "vue";
import {
  capitalizeFirstLetter,
  getArrayMonthDay,
  getMonths,
  checkDateType,
  focusWhenReady,
} from "../../utils/index";
import Day from "./Day.vue";
import DateDialog from "./DateDialog.vue";

type Type = "date" | "period" | "compare";
type Option = {
  title: string;
  date: Date;
  weeks: any[];
  value: number;
};

const props = withDefaults(
  defineProps<{
    modelValue?: Date | Date[] | Date[][];
    lang?: string;
    type?: Type;
    doubleCalendar?: boolean;
    minDate?: Date;
    maxDate?: Date;
  }>(),
  {
    lang: "en-US",
    type: "date",
    doubleCalendar: false,
  }
);

const emit = defineEmits<{
  "update:modelValue": [value: Date | Date[] | Date[][]];
}>();

const model = ref<Date[] | Date[][]>([]);
const show = ref({
  month: false,
  year: false,
});
const isBack = ref(true);
const showCalendar = ref(true);
const selectedIndex = ref(0);
const hoveredDate = ref();
const titles = ref<HTMLElement[]>([]);
const popups = ref<HTMLDivElement>();
const calendar = ref<HTMLDivElement>();

const dates = computed(() => {
  if (props.doubleCalendar) {
    return [
      {
        date: new Date(new Date().setMonth(new Date().getMonth() - 1)),
      },
      {
        date: new Date(),
        value: -1,
      },
    ];
  }

  return [
    {
      date: new Date(),
    },
  ];
});
const options = ref(getOptions());

const weekDays = computed((): string[] => {
  const date = new Date("2021-10-03T23:15:30");
  const weekDay: any = [];
  for (let i = 0; i < 7; i++) {
    const day = date.toLocaleDateString(props.lang, { weekday: "long" });
    const formattedDay =
      day.charAt(0).toUpperCase() + day.charAt(1).toLowerCase();
    weekDay.push(formattedDay);
    date.setDate(date.getDate() + 1);
  }
  return weekDay;
});
const months = computed(() => getMonths(props.lang));
const years = computed(() => {
  const years: any = [];
  const date = options.value[options.value.length - 1].date;
  for (let i = date.getFullYear(); i >= date.getFullYear() - 100; i--) {
    years.push(i);
  }
  return years;
});

onBeforeMount(checkValidModel);

watch(() => props.modelValue, checkValidModel, { immediate: true, deep: true });
watch(() => props.type, checkValidModel);
watch(
  () => props.lang,
  () => updateOptions()
);
watch(
  () => props.doubleCalendar,
  () => {
    options.value = getOptions();
    updateOptions();
  }
);

function checkValidModel() {
  model.value = checkDateType(props.modelValue, props.type);
}

function updateOptions(value?: number, changeWeeks = true) {
  options.value.forEach((option: any) => {
    if (value)
      option.date = new Date(option.date.getFullYear(), option.date.getMonth() + value, 1);
    if (changeWeeks) option.weeks = getArrayMonthDay(option.date);
    option.title = getTitle(option.date);
  });
}

function getOptions() {
  return dates.value.map((date) => getDateObject(date.date, date.value));
}

function getDateObject(date: Date, value = 1): Option {
  date = new Date(date.getFullYear(), date.getMonth(), 1);
  return {
    title: getTitle(date),
    weeks: getArrayMonthDay(date),
    value,
    date,
  };
}

function getTitle(date: Date): string {
  if (show.value.year || show.value.month) {
    return capitalizeFirstLetter(
      date.toLocaleDateString(props.lang, { year: "numeric" })
    );
  }
  return capitalizeFirstLetter(
    date.toLocaleDateString(props.lang, { year: "numeric", month: "long" })
  );
}

function setNewMonth(value: number) {
  isBack.value = value === -1;
  showCalendar.value = false;
  updateOptions(value);

  setTimeout(() => {
    showCalendar.value = true;
  }, 100);
}

function isDateDisabled(date: Date) {
  const iso = date.toISOString().substring(0, 10);
  if (props.minDate && iso < props.minDate.toISOString().substring(0, 10)) return true;
  if (props.maxDate && iso > props.maxDate.toISOString().substring(0, 10)) return true;
  return false;
}

function addMonths(date: Date, months: number): Date {
  const lastDay = new Date(date.getFullYear(), date.getMonth() + months + 1, 0).getDate();
  return new Date(date.getFullYear(), date.getMonth() + months, Math.min(date.getDate(), lastDay));
}

function getMonthDifference(from: Date, to: Date) {
  return (to.getFullYear() - from.getFullYear()) * 12 + to.getMonth() - from.getMonth();
}

function showMonthOf(date: Date) {
  const first = options.value[0].date;
  const last = options.value[options.value.length - 1].date;
  let difference = getMonthDifference(first, date);
  if (difference > 0) difference = Math.max(getMonthDifference(last, date), 0);
  if (!difference) return;

  isBack.value = difference < 0;
  showCalendar.value = false;
  updateOptions(difference);

  setTimeout(() => {
    showCalendar.value = true;
  }, 100);
}

function onGridKeyDown(event: KeyboardEvent) {
  const cell = (event.target as HTMLElement).closest<HTMLElement>("[data-date]");
  if (!cell) return;

  const [year, month, day] = cell.dataset.date!.split("-").map(Number);
  const current = new Date(year, month - 1, day);
  const moves: Record<string, (date: Date) => Date> = {
    ArrowLeft: (d) => new Date(d.getFullYear(), d.getMonth(), d.getDate() - 1),
    ArrowRight: (d) => new Date(d.getFullYear(), d.getMonth(), d.getDate() + 1),
    ArrowUp: (d) => new Date(d.getFullYear(), d.getMonth(), d.getDate() - 7),
    ArrowDown: (d) => new Date(d.getFullYear(), d.getMonth(), d.getDate() + 7),
    Home: (d) => new Date(d.getFullYear(), d.getMonth(), d.getDate() - d.getDay()),
    End: (d) => new Date(d.getFullYear(), d.getMonth(), d.getDate() + 6 - d.getDay()),
    PageUp: (d) => addMonths(d, -1),
    PageDown: (d) => addMonths(d, 1),
  };
  const move = moves[event.key];
  if (!move) return;
  event.preventDefault();

  const step = ["Home", "End"].includes(event.key)
    ? moves[event.key === "Home" ? "ArrowRight" : "ArrowLeft"]
    : move;
  let next = move(current);
  for (let i = 0; i < 366 && isDateDisabled(next); i++) {
    if (next.getTime() === current.getTime()) return;
    next = step(next);
  }
  if (isDateDisabled(next)) return;

  const key = `${next.getFullYear()}-${next.getMonth() + 1}-${next.getDate()}`;
  if (!calendar.value?.querySelector(`[data-date="${key}"]`)) showMonthOf(next);
  focusWhenReady(() => calendar.value?.querySelector<HTMLElement>(`[data-date="${key}"]`));
}

function hidePopup() {
  setTimeout(() => {
    const active = document.activeElement as HTMLElement | null;
    if (active && (popups.value?.contains(active) || titles.value.includes(active)))
      return;

    Object.keys(show.value).forEach((key) => {
      show.value[key as keyof typeof show.value] = false;
    });
    updateOptions();
  }, 100);
}

function showPopup(index: number) {
  selectedIndex.value = index;
  show.value.year = show.value.month && !show.value.year;
  show.value.month = !show.value.month || show.value.year;

  updateOptions();
}

function closePopup(event: KeyboardEvent) {
  if (!show.value.month && !show.value.year) return;

  event.stopPropagation();
  show.value.month = false;
  show.value.year = false;
  updateOptions();
  titles.value[selectedIndex.value]?.focus();
}

function focusFirstPopupOption(event: KeyboardEvent) {
  if (event.shiftKey || (!show.value.month && !show.value.year)) return;

  const popup = show.value.year ? "year" : "month";
  const option = popups.value?.querySelector<HTMLElement>(`[data-popup="${popup}"]`);
  if (!option) return;

  event.preventDefault();
  option.focus();
}

function focusTitleOnLastTab(event: KeyboardEvent, isLast: boolean) {
  if (!isLast || event.shiftKey) return;

  event.preventDefault();
  titles.value[selectedIndex.value]?.focus();
}

function getPosition(day: Date, week: any[]) {
  const parsedWeek = week.filter((day: any) => day);
  const index = parsedWeek.findIndex((d: any) => d == day);

  if (day == parsedWeek[0]) return "start";
  else if (index == parsedWeek.length - 1) return "end";
  return "middle";
}

function setModel(date: Date) {
  let selectedDate: Date[] | Date[][] = model.value;

  if (props.type === "compare") {
    selectedDate = selectedDate as unknown as Date[][];
    if (!selectedDate[0] || selectedDate[1].length > 1) {
      selectedDate = [[], []];
    }

    let index = 0;
    if (selectedDate[0].length > 1) index = 1;

    selectedDate[index] = sortDate(date, selectedDate[index]);
  } else {
    selectedDate = sortDate(date, selectedDate as Date[]);
  }

  emit("update:modelValue", props.type == "date" ? date : selectedDate);
}

function sortDate(date: Date, dates: Date[]): Date[] {
  if (
    dates.length > 1 ||
    !dates.length ||
    (options.value.length == 1 && props.type == "date")
  ) {
    dates = [];
    dates[0] = date;
  } else if (date < dates[0]) {
    dates[1] = dates[0];
    dates[0] = date;
  } else {
    dates[1] = date;
  }

  return dates;
}

function changeMonth(month: number) {
  show.value.month = false;
  const index = selectedIndex.value;
  const primary = options.value[index].date;
  const secondary =
    options.value[index == options.value.length - 1 ? 0 : index + 1].date;
  const toAdd = options.value[index].value;

  primary.setMonth(month);
  if (options.value.length > 1) secondary.setMonth(primary.getMonth() + toAdd);
  updateOptions();
  titles.value[index]?.focus();
}

function changeYear(year: number) {
  show.value.year = false;
  show.value.month = false;
  const index = selectedIndex.value;
  const primary = options.value[index].date;
  const secondary =
    options.value[index == options.value.length - 1 ? 0 : index + 1].date;
  let toAdd = options.value[index].value;

  if (
    !(primary.getMonth() == 1 && toAdd == 1) &&
    !(primary.getMonth() == 11 && toAdd == -1)
  )
    toAdd = 0;

  primary.setFullYear(year);
  if (options.value.length > 1) secondary.setFullYear(year + toAdd);
  updateOptions();
  titles.value[index]?.focus();
}
</script>

<template>
  <div ref="calendar" class="calendar" @keydown="onGridKeyDown">
    <div
      v-for="(option, index) in options"
      :key="index"
      class="w-full p-sm overflow-hidden"
    >
      <header class="relative flex items-center justify-center gap-xs mb-xs">
        <div
          v-if="index == 0"
          class="calendar-arrow left-0"
          tabindex="0"
          @click="setNewMonth(-1)"
          @keyup.enter.space="setNewMonth(-1)"
        >
          <Icon name="chevron_left" class="leading-xxs" />
        </div>
        <Transition :name="!isBack ? 'slide-fade' : 'slide-fade-out'">
          <h1
            class="text-base font-bold cursor-pointer text-neutral-foreground-high"
            v-if="show"
            :ref="(el) => (titles[index] = el as HTMLElement)"
            tabindex="0"
            @blur="hidePopup"
            @click="showPopup(index)"
            @keyup.enter.space="showPopup(index)"
            @keydown.tab="focusFirstPopupOption"
            @keydown.esc="closePopup"
          >
            {{ option.title }}
          </h1>
        </Transition>
        <div
          v-if="options.length - 1 == index"
          class="calendar-arrow right-0"
          tabindex="0"
          @click="setNewMonth(1)"
          @keyup.enter.space="setNewMonth(1)"
        >
          <Icon name="chevron_right" class="leading-xxs" />
        </div>
      </header>
      <Transition :name="!isBack ? 'slide-fade' : 'slide-fade-out'">
        <table v-if="showCalendar" class="w-full">
          <thead>
            <tr class="[&>*]:p-xxs">
              <th v-for="(weekDay, index) in weekDays" :key="index">
                {{ weekDay }}
              </th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="(week, index) in option.weeks.filter((w) =>
                w.some((d: any) => d)
              )"
              :key="index"
              class="[&>*]:py-xxs [&>*]:px-none"
            >
              <td v-for="(day, index) in week" :key="index">
                <Day
                  v-model="model"
                  v-model:hovered="hoveredDate"
                  :day="day"
                  :type="type"
                  :index="Number(index)"
                  :position="getPosition(day, week)"
                  :min-date="minDate"
                  :max-date="maxDate"
                  @select="setModel"
                />
              </td>
            </tr>
          </tbody>
        </table>
      </Transition>
    </div>
    <div ref="popups" @focusout="hidePopup" @keydown.esc="closePopup">
      <DateDialog :model-value="show.month && !show.year" :options="months" wrap>
        <template #option="{ option }">
          <div
            data-popup="month"
            :class="[
              option.value === options[selectedIndex].date.getMonth()
                ? 'bg-primary-interaction-default'
                : 'bg-primary-surface-highlight',
            ]"
            class="flex items-center justify-center flex-1 cursor-pointer min-w-[30%] text-neutral-foreground-negative text-sm p-sm border-xxs rounded-base hover:bg-primary-interaction-hover"
            tabindex="0"
            @click="changeMonth(option.value)"
            @keyup.enter.space="changeMonth(option.value)"
            @keydown.tab="
              focusTitleOnLastTab($event, option === months[months.length - 1])
            "
          >
            {{ option.label }}
          </div>
        </template>
      </DateDialog>
      <DateDialog
        :model-value="show.year"
        :options="years"
        vertical
        max-height="70%"
        no-padding
      >
        <template #option="{ option }">
          <div
            class="flex items-center justify-center cursor-pointer w-full p-xxs text-sm hover:bg-primary-surface-default hover:text-primary-interaction-default"
            :class="{
              'text-primary-interaction-default bg-primary-surface-default':
                option === options[selectedIndex].date.getFullYear(),
            }"
            data-popup="year"
            tabindex="0"
            @click="changeYear(option)"
            @keyup.enter.space="changeYear(option)"
            @keydown.tab="
              focusTitleOnLastTab($event, option === years[years.length - 1])
            "
          >
            {{ option }}
          </div>
        </template>
      </DateDialog>
    </div>
  </div>
</template>

<style scoped>
@reference "../../assets/main.css";

.calendar {
  @apply flex relative w-full;
}

th {
  @apply text-neutral-foreground-low text-sm;
}

.slide-fade-enter-active {
  @apply transition-all duration-300 ease-out;
}

.slide-fade-leave-active {
  transition: all 0.8s cubic-bezier(1, 0.5, 0.8, 1);
}

.slide-fade-enter-from,
.slide-fade-leave-to {
  @apply opacity-0;
  transform: translateX(20px);
}

.slide-fade-out-enter-active {
  @apply transition-all duration-300 ease-out;
}

.slide-fade-out-leave-active {
  transition: all 0.8s cubic-bezier(1, 0.5, 0.8, 1);
}

.slide-fade-out-enter-from,
.slide-fade-out-leave-to {
  @apply opacity-0;
  transform: translateX(-20px);
}

.calendar-arrow {
  @apply flex items-center absolute text-neutral-interaction-default rounded-base border-xxs p-xxs
    border-neutral-default cursor-pointer hover:bg-neutral-surface-hover hover:text-neutral-interaction-hover;

  .icon {
    @apply text-xl;
  }
}
</style>

// src/components/Calendar/Calendar.tsx
import type React from "react";
import { useState, useRef, useEffect, type RefObject, useMemo } from "react";
import clsx from "clsx";
import {
  getArrayMonthDay,
  getMonths,
  checkDateType,
  capitalizeFirstLetter,
  isRange,
  onEnterOrSpace,
  focusWhenReady,
} from "../../utils/index";
import { useTransition } from "../../hooks/useTransition";
import { Icon } from "../Icon/Icon";
import { Card } from "../Card/Card";
import styles from "./Calendar.module.css";

type SelectionType = "date" | "period" | "compare";

export interface CalendarProps {
  value?: Date | Date[] | [Date[], Date[]];
  onChange?: (value: any) => void;
  type?: SelectionType;
  doubleCalendar?: boolean;
  minDate?: Date;
  maxDate?: Date;
  disabledDates?: Date[];
  lang?: string;
  className?: string;
}

interface CalendarDayProps {
  date: Date | null;
  rangePrimary: boolean;
  rangeSecondary: boolean;
  selectedPrimary: boolean;
  selectedSecondary: boolean;
  hoveredPrimary: boolean;
  hoveredSecondary: boolean;
  isCompare: boolean;
  differencePrimary: string | false;
  differenceSecondary: string | false;
  showSplit: boolean;
  splitIsSecondary: boolean;
  isToday: boolean;
  position: "start" | "middle" | "end";
  isOutsideMonth: boolean;
  isDisabled: boolean;
  onClick: () => void;
  onMouseEnter?: () => void;
  onMouseLeave?: () => void;
}

function CalendarDay({
  date,
  rangePrimary,
  rangeSecondary,
  selectedPrimary,
  selectedSecondary,
  hoveredPrimary,
  hoveredSecondary,
  isCompare,
  differencePrimary,
  differenceSecondary,
  showSplit,
  splitIsSecondary,
  isToday,
  isOutsideMonth,
  isDisabled,
  position,
  onClick,
  onMouseEnter,
  onMouseLeave,
}: CalendarDayProps) {
  if (!date) return <div className={styles.dayCell} />;

  return (
    <div
      className={clsx(
        styles.dayCell,
        styles[position],
        rangePrimary && styles.rangePrimary,
        rangeSecondary && styles.rangeSecondary,
        selectedPrimary && styles.selectedPrimary,
        selectedSecondary && styles.selectedSecondary,
        hoveredPrimary && styles.hoveredPrimary,
        hoveredSecondary && styles.hoveredSecondary,
        isCompare && styles.isCompare,
        differencePrimary && styles[differencePrimary],
        differenceSecondary && styles[differenceSecondary],
        isToday && styles.today,
        isOutsideMonth && styles.outsideMonth,
        isDisabled && styles.disabled,
      )}
      tabIndex={isDisabled ? -1 : 0}
      onClick={isDisabled ? undefined : onClick}
      onKeyUp={isDisabled ? undefined : onEnterOrSpace(() => onClick())}
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      role="gridcell"
      data-date={getDateKey(date)}
      aria-selected={selectedPrimary || selectedSecondary}
    >
      {showSplit && (
        <div className={styles.splitOverlay}>
          <div className={styles.halfPrimary} />
          <div
            className={
              splitIsSecondary ? styles.halfSecondary : styles.halfHover
            }
          />
        </div>
      )}
      <span className={styles.dayLabel}>{date.getDate()}</span>
    </div>
  );
}

interface CalendarDateDialogProps {
  months: { label: string; value: number }[];
  currentMonth: number;
  currentYear: number;
  isOpen: boolean;
  header: RefObject<HTMLDivElement | null>;
  onSelectMonth: (month: number) => void;
  onSelectYear: (year: number) => void;
}

function CalendarDateDialog({
  months,
  currentMonth,
  currentYear,
  isOpen,
  header,
  onSelectMonth,
  onSelectYear,
}: CalendarDateDialogProps) {
  const [activePanel, setActivePanel] = useState<"month" | "year" | null>(
    "month",
  );
  const yearListRef = useRef<HTMLDivElement>(null);
  const popupsRef = useRef<HTMLDivElement>(null);

  const yearRange: number[] = [];
  for (let y = currentYear; y >= currentYear - 100; y--) {
    yearRange.push(y);
  }

  function getTop() {
    if (typeof header === "function") return 0;

    const current = header.current;
    return `${current ? current.scrollHeight : 0}px`;
  }

  useEffect(() => {
    if (activePanel === "year" && yearListRef.current) {
      const activeEl = yearListRef.current.querySelector(
        `.${styles.yearActive}`,
      ) as HTMLElement | null;
      if (activeEl) {
        activeEl.scrollIntoView({ block: "center", behavior: "smooth" });
      }
    }
  }, [activePanel]);

  function focusFirstPopupOption(event: React.KeyboardEvent<HTMLButtonElement>) {
    if (event.key !== "Tab" || event.shiftKey || !activePanel) return;

    const popup = activePanel === "year" ? "year" : "month";
    const option = popupsRef.current?.querySelector<HTMLElement>(`[data-popup="${popup}"]`);
    if (!option) return;

    event.preventDefault();
    option.focus();
  }

  function focusHeaderOnLastTab(event: React.KeyboardEvent<HTMLButtonElement>, isLast: boolean, headerButton: HTMLButtonElement | null) {
    if (event.key !== "Tab" || !isLast || event.shiftKey) return;

    event.preventDefault();
    headerButton?.focus();
  }

  const monthButtonRef = useRef<HTMLButtonElement>(null);
  const yearButtonRef = useRef<HTMLButtonElement>(null);

  return (
    <Card
      className={clsx(
        styles.dateDialog,
        isOpen ? styles.dialogEnter : styles.dialogLeave,
      )}
      style={{ top: getTop() }}
    >
      <div className={styles.dialogHeader}>
        <button
          ref={monthButtonRef}
          className={clsx(
            styles.headerToggle,
            activePanel === "month" && styles.headerToggleActive,
          )}
          onClick={() =>
            setActivePanel((prev) => (prev === "month" ? null : "month"))
          }
        >
          {months[currentMonth]?.label ?? ""}
        </button>
        <button
          ref={yearButtonRef}
          className={clsx(
            styles.headerToggle,
            activePanel === "year" && styles.headerToggleActive,
          )}
          onClick={() =>
            setActivePanel((prev) => (prev === "year" ? null : "year"))
          }
          onKeyDown={focusFirstPopupOption}
        >
          {currentYear}
        </button>
      </div>

      <div ref={popupsRef} onBlur={(e: React.FocusEvent<HTMLDivElement>) => {
        const related = e.relatedTarget as Node | null;
        if (
          popupsRef.current?.contains(related) ||
          related === monthButtonRef.current ||
          related === yearButtonRef.current
        )
          return;
        setActivePanel(null);
      }}>
        {activePanel === "month" && (
          <div className={styles.monthGrid}>
            {months.map((m, idx) => (
              <button
                key={m.value}
                data-popup="month"
                className={clsx(
                  styles.monthButton,
                  m.value === currentMonth && styles.monthActive,
                )}
                tabIndex={0}
                onClick={() => {
                  onSelectMonth(m.value);
                  setActivePanel(null);
                }}
                onKeyDown={(e) => focusHeaderOnLastTab(e, idx === months.length - 1, monthButtonRef.current)}
              >
                {m.label}
              </button>
            ))}
          </div>
        )}

        {activePanel === "year" && (
          <div className={styles.yearList} ref={yearListRef}>
            {yearRange.map((yr, idx) => (
              <button
                key={yr}
                data-popup="year"
                className={clsx(
                  styles.yearButton,
                  yr === currentYear && styles.yearActive,
                )}
                tabIndex={0}
                onClick={() => {
                  onSelectYear(yr);
                  setActivePanel(null);
                }}
                onKeyDown={(e) => focusHeaderOnLastTab(e, idx === yearRange.length - 1, yearButtonRef.current)}
              >
                {yr}
              </button>
            ))}
          </div>
        )}
      </div>
    </Card>
  );
}

function isSameDay(a: Date, b: Date): boolean {
  return (
    a.getFullYear() === b.getFullYear() &&
    a.getMonth() === b.getMonth() &&
    a.getDate() === b.getDate()
  );
}

function addMonths(date: Date, months: number): Date {
  const lastDay = new Date(date.getFullYear(), date.getMonth() + months + 1, 0).getDate();
  return new Date(date.getFullYear(), date.getMonth() + months, Math.min(date.getDate(), lastDay));
}

function getDateKey(date: Date): string {
  return `${date.getFullYear()}-${date.getMonth() + 1}-${date.getDate()}`;
}

function isDateDisabled(
  date: Date,
  minDate?: Date,
  maxDate?: Date,
  disabledDates?: Date[],
): boolean {
  const iso = date.toISOString().substring(0, 10);
  if (minDate && iso < minDate.toISOString().substring(0, 10)) return true;
  if (maxDate && iso > maxDate.toISOString().substring(0, 10)) return true;
  if (disabledDates?.some((d) => isSameDay(d, date))) return true;
  return false;
}

function getDates(
  model: Date[] | Date[][],
  type: SelectionType,
  index: number,
): Date[] {
  if (!model) return [];
  if (type === "compare") return ((model as Date[][])[index] ?? []) as Date[];
  return model as Date[];
}

function isInRangeCheck(
  day: Date,
  model: Date[] | Date[][],
  type: SelectionType,
  index: number,
  isSelected: boolean,
): boolean {
  if (!model || (index > 0 && type !== "compare")) return false;
  const dates = getDates(model, type, index);
  if (
    dates.length > 1 &&
    dates[0] instanceof Date &&
    dates[1] instanceof Date
  ) {
    return isRange(dates[0], dates[1], day, isSelected);
  }
  return (
    isSelected &&
    dates[0] instanceof Date &&
    dates[0].toISOString().substring(0, 10) ===
      day.toISOString().substring(0, 10)
  );
}

function getHoveredCheck(
  day: Date,
  model: Date[] | Date[][],
  type: SelectionType,
  hovered: Date | null,
  index: number,
): boolean {
  if (!hovered || !model || type === "date") return false;
  const dates = getDates(model, type, index);
  return dates.length === 1 && isRange(dates[0], hovered, day);
}

function getDifferenceCheck(
  day: Date,
  model: Date[] | Date[][],
  type: SelectionType,
  hovered: Date | null,
  index: number,
): string | false {
  if (!model || type === "date") return false;
  const dates = getDates(model, type, index);

  const parsedDay = day.toISOString().substring(0, 10);
  let toCompare = hovered?.toISOString().substring(0, 10);
  const start = (dates[0] as Date)?.toISOString().substring(0, 10);

  if (dates.length > 1)
    toCompare = (dates[1] as Date)?.toISOString().substring(0, 10);
  if (start !== parsedDay && parsedDay !== toCompare) return false;

  if (toCompare === parsedDay) toCompare = start;
  if (!toCompare || !parsedDay) return false;

  if (parsedDay < toCompare) return "isBigger";
  if (parsedDay > toCompare) return "isSmaller";
  return false;
}

function getDayProps(
  date: Date,
  model: Date[] | Date[][],
  type: SelectionType,
  today: Date,
  hoveredDate: Date | null,
  minDate?: Date,
  maxDate?: Date,
  disabledDates?: Date[],
) {
  const isToday = isSameDay(date, today);
  const isDisabled = isDateDisabled(date, minDate, maxDate, disabledDates);
  const isCompare = type !== "date";

  const rangePrimary = isInRangeCheck(date, model, type, 0, false);
  const rangeSecondary = isInRangeCheck(date, model, type, 1, false);
  const selectedPrimary = isInRangeCheck(date, model, type, 0, true);
  const selectedSecondary = isInRangeCheck(date, model, type, 1, true);
  const hoveredPrimary = getHoveredCheck(date, model, type, hoveredDate, 0);
  const hoveredSecondary = getHoveredCheck(date, model, type, hoveredDate, 1);
  const differencePrimary = getDifferenceCheck(
    date,
    model,
    type,
    hoveredDate,
    0,
  );
  const differenceSecondary = getDifferenceCheck(
    date,
    model,
    type,
    hoveredDate,
    1,
  );

  const dates0 = getDates(model, type, 0);
  const dates1 = getDates(model, type, 1);
  const showSplit =
    type !== "date" &&
    selectedPrimary &&
    ((hoveredDate !== null &&
      isSameDay(hoveredDate, date) &&
      dates0.length > 1) ||
      selectedSecondary) &&
    (dates1.length < 2 || selectedSecondary);
  const splitIsSecondary = selectedSecondary;

  return {
    rangePrimary,
    rangeSecondary,
    selectedPrimary,
    selectedSecondary,
    hoveredPrimary,
    hoveredSecondary,
    isCompare,
    differencePrimary,
    differenceSecondary,
    showSplit,
    splitIsSecondary,
    isToday,
    isDisabled,
  };
}
interface CalendarComponent {
  (props: CalendarProps): React.JSX.Element;
  Day: typeof CalendarDay;
  DateDialog: typeof CalendarDateDialog;
}

function getInitialMonthYear(value?: Date | Date[] | [Date[], Date[]]): {
  month: number;
  year: number;
} {
  const today = new Date();
  if (!value) return { month: today.getMonth(), year: today.getFullYear() };
  if (value instanceof Date)
    return { month: value.getMonth(), year: value.getFullYear() };
  if (Array.isArray(value) && value.length > 0) {
    const first = Array.isArray(value[0])
      ? (value[0] as Date[])[0]
      : (value[0] as Date);
    if (first instanceof Date)
      return { month: first.getMonth(), year: first.getFullYear() };
  }
  return { month: today.getMonth(), year: today.getFullYear() };
}

export function Calendar({
  value,
  onChange,
  type = "date",
  doubleCalendar = false,
  minDate,
  maxDate,
  disabledDates,
  lang = "en",
  className,
}: CalendarProps): React.JSX.Element {
  const initial = getInitialMonthYear(value);
  const [currentMonth, setCurrentMonth] = useState(initial.month);
  const [currentYear, setCurrentYear] = useState(initial.year);
  const [showDateDialog, setShowDateDialog] = useState(false);
  const [transitionKey, setTransitionKey] = useState(0);
  const [hoveredDate, setHoveredDate] = useState<Date | null>(null);
  const header = useRef<HTMLDivElement>(null);
  const titleRef = useRef<HTMLButtonElement>(null);
  const dateDialogRef = useRef<HTMLDivElement>(null);

  const isBackRef = useRef(false);
  const { isMounted: _gridMounted, isActive: _gridActive } = useTransition(
    transitionKey % 2 === 0,
    { duration: 300 },
  );

  const model = useMemo(
    (): Date[] | Date[][] => checkDateType(value as any, type),
    [value],
  );

  const today = new Date();
  const monthDate = new Date(currentYear, currentMonth, 1);
  const weeks = getArrayMonthDay(monthDate);
  const months = getMonths(lang);

  const nextMonthNum = currentMonth === 11 ? 0 : currentMonth + 1;
  const nextYearNum = currentMonth === 11 ? currentYear + 1 : currentYear;
  const nextMonthDate = new Date(nextYearNum, nextMonthNum, 1);
  const nextWeeks = getArrayMonthDay(nextMonthDate);

  const weekDays: string[] = [];
  const baseDate = new Date("2021-10-03T23:15:30");
  for (let i = 0; i < 7; i++) {
    const day = baseDate.toLocaleDateString(lang, { weekday: "short" });
    weekDays.push(day.charAt(0).toUpperCase() + day.charAt(1).toLowerCase());
    baseDate.setDate(baseDate.getDate() + 1);
  }

  const monthLabel = capitalizeFirstLetter(
    new Date(currentYear, currentMonth, 1).toLocaleDateString(lang, {
      year: "numeric",
      month: "long",
    }),
  );

  const nextMonthLabel = capitalizeFirstLetter(
    new Date(nextYearNum, nextMonthNum, 1).toLocaleDateString(lang, {
      year: "numeric",
      month: "long",
    }),
  );

  function showMonthOf(date: Date) {
    const first = new Date(currentYear, currentMonth, 1);
    const target = new Date(date.getFullYear(), date.getMonth(), 1);
    if (doubleCalendar && target > first) target.setMonth(target.getMonth() - 1);

    isBackRef.current = target < first;
    setTransitionKey((k) => k + 1);
    setCurrentMonth(target.getMonth());
    setCurrentYear(target.getFullYear());
  }

  function handleGridKeyDown(event: React.KeyboardEvent) {
    const cell = (event.target as HTMLElement).closest<HTMLElement>("[data-date]");
    if (!cell) return;

    const [year, month, day] = cell.dataset.date!.split("-").map(Number);
    const current = new Date(year, month - 1, day);
    const moves: Record<string, (date: Date) => Date> = {
      ArrowLeft: (d) => new Date(d.getFullYear(), d.getMonth(), d.getDate() - 1),
      ArrowRight: (d) => new Date(d.getFullYear(), d.getMonth(), d.getDate() + 1),
      ArrowUp: (d) => new Date(d.getFullYear(), d.getMonth(), d.getDate() - 7),
      ArrowDown: (d) => new Date(d.getFullYear(), d.getMonth(), d.getDate() + 7),
      Home: (d) => new Date(d.getFullYear(), d.getMonth(), d.getDate() - d.getDay()),
      End: (d) => new Date(d.getFullYear(), d.getMonth(), d.getDate() + 6 - d.getDay()),
      PageUp: (d) => addMonths(d, -1),
      PageDown: (d) => addMonths(d, 1),
    };
    const move = moves[event.key];
    if (!move) return;
    event.preventDefault();

    const step = ["Home", "End"].includes(event.key)
      ? moves[event.key === "Home" ? "ArrowRight" : "ArrowLeft"]
      : move;
    let next = move(current);
    for (let i = 0; i < 366 && isDateDisabled(next, minDate, maxDate, disabledDates); i++) {
      if (next.getTime() === current.getTime()) return;
      next = step(next);
    }
    if (isDateDisabled(next, minDate, maxDate, disabledDates)) return;

    const key = getDateKey(next);
    const root = event.currentTarget as HTMLElement;
    if (!root.querySelector(`[data-date="${key}"]`)) showMonthOf(next);
    focusWhenReady(() => root.querySelector<HTMLElement>(`[data-date="${key}"]`));
  }

  function prevMonth() {
    isBackRef.current = true;
    setTransitionKey((k) => k + 1);
    if (currentMonth === 0) {
      setCurrentMonth(11);
      setCurrentYear((y) => y - 1);
    } else {
      setCurrentMonth((m) => m - 1);
    }
  }

  function nextMonth() {
    isBackRef.current = false;
    setTransitionKey((k) => k + 1);
    if (currentMonth === 11) {
      setCurrentMonth(0);
      setCurrentYear((y) => y + 1);
    } else {
      setCurrentMonth((m) => m + 1);
    }
  }

  function handleDayClick(date: Date) {
    let newModel: Date[] | Date[][];

    if (type === "date") {
      newModel = [date];
    } else if (type === "period") {
      const dates = model as Date[];
      if (dates.length === 0 || dates.length >= 2) {
        newModel = [date];
      } else {
        const [start] = dates;
        if (date < start) newModel = [date, start];
        else newModel = [start, date];
      }
    } else {
      const ranges = model as Date[][];
      let range0 = [...(ranges[0] ?? [])];
      let range1 = [...(ranges[1] ?? [])];

      if (!ranges[0] || range1.length > 1) {
        range0 = [];
        range1 = [];
      }

      const rangeIdx = range0.length > 1 ? 1 : 0;
      const target = rangeIdx === 0 ? range0 : range1;

      let sorted: Date[];
      if (target.length > 1 || target.length === 0) sorted = [date];
      else if (date < target[0]) sorted = [date, target[0]];
      else sorted = [target[0], date];

      if (rangeIdx === 0) newModel = [sorted, range1];
      else newModel = [range0, sorted];
    }

    if (onChange) {
      if (type === "date") onChange(date);
      else onChange(newModel);
    }
  }

  function handleSelectMonth(month: number) {
    isBackRef.current = month < currentMonth;
    setTransitionKey((k) => k + 1);
    setCurrentMonth(month);
    setShowDateDialog(false);
    titleRef.current?.focus();
  }

  function handleSelectYear(year: number) {
    isBackRef.current = year < currentYear;
    setTransitionKey((k) => k + 1);
    setCurrentYear(year);
    setShowDateDialog(false);
    titleRef.current?.focus();
  }

  function closeDateDialog(e: React.KeyboardEvent) {
    if (e.key !== "Escape" || !showDateDialog) return false;

    e.stopPropagation();
    setShowDateDialog(false);
    titleRef.current?.focus();
    return true;
  }

  function focusDateDialog(e: React.KeyboardEvent) {
    if (closeDateDialog(e)) return;
    if (e.key !== "Tab" || e.shiftKey || !showDateDialog) return;

    const firstButton = dateDialogRef.current?.querySelector<HTMLElement>("button");
    if (!firstButton) return;

    e.preventDefault();
    firstButton.focus();
  }

  function getPosition(week: any[], index: number) {
    if (index === 0) return "start";
    else if (week.length - 1 === index) return "end";

    return "middle";
  }

  const animationClass = isBackRef.current
    ? styles["slide-fade-back"]
    : styles["slide-fade-forward"];

  function renderGrid(gridWeeks: any[], label: string) {
    return (
      <div role="grid" aria-label={label}>
        <div className={styles.grid}>
          {weekDays.map((wd, index) => (
            <div key={wd + index} className={styles.weekdayHeader}>
              {wd}
            </div>
          ))}
        </div>

        {gridWeeks
          .filter((week: any[]) => week.some((d: any) => d))
          .map((week: any[], weekIdx: number) => (
            <div key={weekIdx} className={styles.grid}>
              {week.map((day: Date | "", dayIdx: number) => {
                if (!day) {
                  return <div key={dayIdx} className={styles.noDate} />;
                }
                const props = getDayProps(
                  day,
                  model,
                  type,
                  today,
                  hoveredDate,
                  minDate,
                  maxDate,
                  disabledDates,
                );
                return (
                  <CalendarDay
                    key={dayIdx}
                    date={day}
                    position={getPosition(week, dayIdx)}
                    {...props}
                    isOutsideMonth={false}
                    onClick={() => handleDayClick(day)}
                    onMouseEnter={() => setHoveredDate(day)}
                    onMouseLeave={() => setHoveredDate(null)}
                  />
                );
              })}
            </div>
          ))}
      </div>
    );
  }

  return (
    <div
      className={clsx(
        styles.calendar,
        "calendar",
        doubleCalendar && styles.doubleCalendar,
        className,
      )}
    >
      <div className={styles.header} ref={header}>
        <button
          className={styles.navButton}
          tabIndex={0}
          onClick={prevMonth}
          aria-label="Previous month"
        >
          <Icon name="chevron_left" className="leading-xxs" />
        </button>

        <button
          ref={titleRef}
          className={styles.monthYear}
          tabIndex={0}
          onClick={() => setShowDateDialog((v) => !v)}
          onKeyDown={focusDateDialog}
        >
          {doubleCalendar ? `${monthLabel} – ${nextMonthLabel}` : monthLabel}
        </button>

        <button
          className={styles.navButton}
          tabIndex={0}
          onClick={nextMonth}
          aria-label="Next month"
        >
          <Icon name="chevron_right" className="leading-xxs" />
        </button>
      </div>

      {showDateDialog && (
        <div ref={dateDialogRef} onKeyDown={closeDateDialog}>
          <CalendarDateDialog
            header={header}
            months={months}
            currentMonth={currentMonth}
            currentYear={currentYear}
            isOpen={showDateDialog}
            onSelectMonth={handleSelectMonth}
            onSelectYear={handleSelectYear}
          />
        </div>
      )}

      <div className={styles.slideContainer} onKeyDown={handleGridKeyDown}>
        <div
          key={transitionKey}
          className={clsx(animationClass, doubleCalendar && styles.doubleGrid)}
        >
          {renderGrid(weeks, monthLabel)}
          {doubleCalendar && renderGrid(nextWeeks, nextMonthLabel)}
        </div>
      </div>
    </div>
  );
}

(Calendar as unknown as CalendarComponent).Day = CalendarDay;
(Calendar as unknown as CalendarComponent).DateDialog = CalendarDateDialog;

export { CalendarDay, CalendarDateDialog };
