// src/components/RoundMenu/RoundMenu.tsx
import React, { useState } from 'react';
import clsx from 'clsx';
import { Button } from '../Button/Button';
import styles from './RoundMenu.module.css';

export interface RoundMenuProps {
  options: Array<{ icon?: string; label?: string; onClick?: () => void; [key: string]: any }>;
  iconKey?: string;
  labelKey?: string;
  radius?: number;
  className?: string;
}

export function RoundMenu({
  options,
  iconKey = 'icon',
  labelKey = 'label',
  radius = 80,
  className,
}: RoundMenuProps) {
  const [isExpanded, setIsExpanded] = useState(false);

  function calculatePosition(index: number, total: number): React.CSSProperties {
    const angle = (2 * Math.PI * index) / total - Math.PI / 2;
    const x = Math.cos(angle) * radius;
    const y = Math.sin(angle) * radius;
    return {
      transform: `translate3d(${x}px, ${y}px, 0)`,
    };
  }

  return (
    <div className={clsx(styles.roundMenu, 'round-menu', className)}>
      <Button
        round
        className={clsx(styles.trigger, isExpanded && styles.expanded)}
        aria-label={isExpanded ? 'Close menu' : 'Open menu'}
        aria-expanded={isExpanded}
        onClick={() => setIsExpanded((prev) => !prev)}
        color={isExpanded ? 'neutral': 'success'}
        icon={isExpanded ? 'close' : 'add'}
      />
      {options.map((option, index) => {
        const positionStyle = isExpanded
          ? calculatePosition(index, options.length)
          : undefined;

        return (
          <div
            key={index}
            className={clsx(styles.menuItem, !isExpanded && styles.collapsed)}
            style={positionStyle}
            aria-label={option[labelKey] ?? option.label}
            title={option[labelKey] ?? option.label}
          >
            <Button
              round
              background={option.background}
              icon={option[iconKey] ?? option.icon}
              tabIndex={isExpanded ? 0 : -1}
              onClick={option.onClick}
            >
              {option[labelKey] ?? option.label}
            </Button>
          </div>
        );
      })}
    </div>
  );
}

// src/components/RoundMenu/RoundMenu.vue
<script setup lang="ts">
import { ref, watch, onBeforeMount } from 'vue';

const props = withDefaults(defineProps<{
  options: any[];
}>(), {});

const isExpanded = ref(false);
const positions = ref<string[]>([]);
const isHovering = ref<boolean[]>([]);

onBeforeMount(() =>  {
    calculateButtonPosition();
})

watch(props.options, () => {
    calculateButtonPosition();
});

function calculateButtonPosition() {
  for(let i = 0; i < props.options.length; i++) {
    const angle = (i * 360) / props.options.length;
    const rads = (angle * Math.PI) / 180;

    const z = props.options.length < 7 ? 60 : props.options.length < 10 ? 7 * props.options.length : 6 * props.options.length;
    const x = z * Math.cos(rads);
    const y = z * Math.sin(rads);
    positions.value.push(`${x}px, ${y}px, 0`);
  }
}
</script>

<template>
    <div class="round-menu">
      <div class="option" :class="{'z-[1]': !isExpanded}">
        <Button
          :color="!isExpanded ? 'success' : 'neutral'"
          size="small"
          :aria-label="isExpanded ? 'Close menu' : 'Open menu'"
          :aria-expanded="isExpanded"
          @click="isExpanded = !isExpanded"
          round
        />
      </div>
      <div
        v-for="option, index in options"
        :key="index"
        class="option"
        :style="isExpanded ? {
          transform:`translate3d(${positions[index]})`, 
          '-webkit-transform':`translate3d(${positions[index]})`,
        } : {}"
      >
        <Button
          :background="option.background"
          :icon="option.icon"
          round
          size="small"
          :tabindex="isExpanded ? 0 : -1"
          @click="option.action()"
          @mouseenter="isHovering[index] = true"
          @mouseleave="isHovering[index] = false"
          @focus="isHovering[index] = true"
          @blur="isHovering[index] = false"
          :class="{'z-[50]': isHovering[index]}"
        >
          {{ option.label }}
        </Button>
      </div>
    </div>
</template>

<style scoped>
@reference "../../assets/main.css";

.round-menu {
  @apply relative flex items-center h-fit w-fit overflow-visible;
}

.option {
  @apply absolute hover:z-50;
  -webkit-transform: translate3d(0, 0, 0);
  transform: translate3d(0, 0, 0);
  -webkit-transition: -webkit-transform ease-out 200ms;
  transition: -webkit-transform ease-out 200ms;
  transition: transform ease-out 200ms;
  transition: transform ease-out 200ms, -webkit-transform ease-out 200ms;
}

.option {
  -webkit-transition-timing-function: cubic-bezier(0.935, 0, 0.34, 1.33);
  transition-timing-function: cubic-bezier(0.935, 0, 0.34, 1.33);
}
</style>
