// src/components/Alert/Alert.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, onUpdated, ref } from "vue";
import Icon from "../Icon/Icon.vue";

const props = withDefaults(
  defineProps<{
    title?: string;
    message?: string;
    type?: "info" | "success" | "warning" | "danger" | "neutral";
    size?: "small" | "medium" | "large";
    icon?: string;
    expandable?: boolean;
    closable?: boolean;
    hideIcon?: boolean;
    iconPosition?: "start" | "center" | "end";
  }>(),
  {
    message: "",
    type: "info",
    size: "medium",
    icon: "",
    expandable: false,
    closable: false,
    hideIcon: false,
    iconPosition: "start",
  }
);

const emit = defineEmits<{
  close: [];
}>();

let isExpanded = ref(false);
let card = ref<HTMLDivElement>();
let content = ref<HTMLDivElement>();
const resizeObserver = new ResizeObserver(resize);
const typeIcon = computed(
  (): "info" | "content_copy" | "check_circle" | "error" => {
    switch (props.type) {
      case "info":
      case "neutral":
        return "info";
      case "warning":
      case "danger":
        return "error";
      case "success":
        return "check_circle";
      default:
        return "info";
    }
  }
);

onMounted(() => {
  if (card.value) resizeObserver.observe(card.value, { box: "border-box" });
  if (content.value)
    resizeObserver.observe(content.value, { box: "border-box" });
});

onUpdated(resize);

onBeforeUnmount(() => {
  if (resizeObserver) resizeObserver.disconnect();
});

function resize() {
  if (!content.value || !card.value) return;

  const cardStyles = getComputedStyle(card.value);
  const paddingTop = parseInt(cardStyles.paddingTop);
  const paddingBottom = parseInt(cardStyles.paddingBottom);
  card.value.style.height = `${
    content.value.scrollHeight + paddingTop + paddingBottom
  }px`;
  content.value.style.width = "fit-content";
  const maxWidth = Math.max(content.value.offsetWidth);

  if (
    card.value &&
    (card.value.style.width || card.value.offsetWidth != maxWidth)
  ) {
    content.value.style.width = "100%";
  } else {
    content.value.style.width = `${maxWidth}px`;
  }
}
</script>

<template>
  <div
    ref="card"
    :class="[
      type,
      size,
      {
        'items-start': expandable,
        'items-center': !expandable || !isExpanded,
      },
    ]"
    class="alert"
  >
    <Transition name="content">
      <div
        ref="content"
        class="flex gap-sm transition-[max-height] duration-300"
        :class="[`items-${iconPosition}`]"
      >
        <div
          class="type-icon"
          v-if="!hideIcon"
        >
          <Icon :name="icon || typeIcon" />
        </div>
        <div class="self-center flex-1">
          <slot>
            <div class="flex flex-col gap-xxs">
              <h6 v-if="title" class="title">{{ title }}</h6>
              <p class="message" v-if="!expandable || isExpanded">
                {{ message }}
              </p>
            </div>
          </slot>
        </div>
      </div>
    </Transition>
    <slot name="actions">
      <div class="type-icon cursor-pointer rotate-transition group">
        <div
          class="flex items-center transition-transform ease-in-out duration-300"
          :class="{ 'rotate-180': isExpanded }"
        >
          <Icon
            name="expand_more"
            v-if="expandable"
            @click="isExpanded = !isExpanded"
          />
        </div>
        <Icon name="close" v-if="closable" @click="emit('close')" />
      </div>
    </slot>
  </div>
</template>

<style scoped>
@reference "../../assets/main.css";

.alert {
  @apply flex justify-between p-base rounded-base border-xxs gap-base transition-[height] duration-100;

  .title {
    @apply font-bold;
  }
}

.alert.small {
  .title {
    @apply text-sm;
  }

  .message {
    @apply text-xs;
  }

  .type-icon .type-icon,
  .icon {
    @apply text-xl;
  }
}

.alert.medium {
  .title {
    @apply text-base;
  }

  .message {
    @apply text-sm;
  }

  .type-icon .type-icon,
  .icon {
    @apply text-2xl;
  }
}

.alert.large {
  .title {
    @apply text-xl;
  }

  .message {
    @apply text-base;
  }

  .type-icon .type-icon,
  .icon {
    @apply text-2xl;
  }
}

.info {
  @apply bg-informative-surface-default border-informative-default text-informative-interaction-default;

  .title {
    @apply text-informative-foreground-high;
  }

  .type-icon,
  .message {
    @apply text-informative-foreground-low;
  }
}

.success {
  @apply bg-success-surface-default border-success-default text-success-interaction-default;

  .title {
    @apply text-success-foreground-high;
  }

  .type-icon,
  .message {
    @apply text-success-foreground-low;
  }
}

.warning {
  @apply bg-warning-surface-default border-warning-default text-warning-interaction-default;

  .title {
    @apply text-warning-foreground-high;
  }

  .type-icon,
  .message {
    @apply text-warning-foreground-low;
  }
}

.danger {
  @apply bg-danger-surface-default border-danger-default text-danger-interaction-default;

  .title {
    @apply text-danger-foreground-high;
  }

  .type-icon,
  .message {
    @apply text-danger-foreground-low;
  }
}

.neutral {
  @apply bg-neutral-surface-default border-neutral-default text-neutral-interaction-default;

  .title {
    @apply text-neutral-foreground-high;
  }

  .type-icon,
  .message {
    @apply text-neutral-foreground-low;
  }
}

.type-icon {
  @apply flex transition-transform duration-500;
}
</style>

// src/components/Alert/Alert.tsx
import { useState, useRef, useEffect, useCallback } from 'react';
import clsx from 'clsx';
import { Icon } from '../Icon/Icon';
import styles from './Alert.module.css';

export interface AlertProps {
  title?: string;
  message?: string;
  type?: 'info' | 'success' | 'warning' | 'danger' | 'neutral';
  size?: 'small' | 'medium' | 'large';
  icon?: string;
  expandable?: boolean;
  closable?: boolean;
  hideIcon?: boolean;
  iconPosition?: 'start' | 'center' | 'end';
  children?: React.ReactNode;
  actions?: React.ReactNode;
  onClose?: () => void;
  className?: string;
}

function getTypeIcon(type: string): string {
  switch (type) {
    case 'info':
    case 'neutral':
      return 'info';
    case 'warning':
    case 'danger':
      return 'error';
    case 'success':
      return 'check_circle';
    default:
      return 'info';
  }
}

export function Alert({
  title,
  message = '',
  type = 'info',
  size = 'medium',
  icon = '',
  expandable = false,
  closable = false,
  hideIcon = false,
  iconPosition = 'start',
  children,
  actions,
  onClose,
  className,
}: AlertProps) {
  const [isExpanded, setIsExpanded] = useState(false);
  const cardRef = useRef<HTMLDivElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);

  const resize = useCallback(() => {
    if (!contentRef.current || !cardRef.current) return;

    const cardStyles = getComputedStyle(cardRef.current);
    const paddingTop = parseInt(cardStyles.paddingTop);
    const paddingBottom = parseInt(cardStyles.paddingBottom);
    cardRef.current.style.height = `${
      contentRef.current.scrollHeight + paddingTop + paddingBottom
    }px`;
    contentRef.current.style.width = 'fit-content';
    const maxWidth = contentRef.current.offsetWidth;

    if (
      cardRef.current.style.width ||
      cardRef.current.offsetWidth !== maxWidth
    ) {
      contentRef.current.style.width = '100%';
    } else {
      contentRef.current.style.width = `${maxWidth}px`;
    }
  }, []);

  useEffect(() => {
    const observer = new ResizeObserver(resize);
    if (cardRef.current) observer.observe(cardRef.current, { box: 'border-box' });
    if (contentRef.current) observer.observe(contentRef.current, { box: 'border-box' });
    return () => observer.disconnect();
  }, [resize]);

  useEffect(() => {
    resize();
  });

  const typeIcon = icon || getTypeIcon(type);

  return (
    <div
      ref={cardRef}
      className={clsx(
        styles.alert,
        'alert',
        styles[type],
        styles[size],
        expandable && styles.itemsStart,
        (!expandable || !isExpanded) && styles.itemsCenter,
        className
      )}
    >
      <div
        ref={contentRef}
        className={clsx(styles.contentWrapper, styles[`items-${iconPosition}`])}
      >
        {!hideIcon && (
          <div className={styles.typeIcon}>
            <Icon name={typeIcon} />
          </div>
        )}
        <div className={styles.body}>
          {children || (
            <div className={styles.textContent}>
              {title && <h6 className={styles.title}>{title}</h6>}
              {(!expandable || isExpanded) && message && (
                <p className={styles.message}>{message}</p>
              )}
            </div>
          )}
        </div>
      </div>
      {actions || (
        <div className={clsx(styles.typeIcon, styles.actionIcon)}>
          {expandable && (
            <div
              className={clsx(
                styles.expandToggle,
                isExpanded && styles.rotated
              )}
              onClick={() => setIsExpanded(!isExpanded)}
            >
              <Icon name="expand_more" />
            </div>
          )}
          {closable && (
            <Icon name="close" onClick={onClose} className={styles.clickable} />
          )}
        </div>
      )}
    </div>
  );
}

Alert.Actions = function AlertActions({
  children,
}: {
  children?: React.ReactNode;
}) {
  return <>{children}</>;
};
