// src/components/TagInput/TagInput.tsx
import { useState, useRef, useEffect, Children, isValidElement } from "react";
import clsx from "clsx";
import { useControllable } from "../../hooks/useControllable";
import { isNilAndBlank, applyMask } from "../../utils/index";
import { Label } from "../../utils/components/Label";
import { Tooltip } from "../Tooltip/Tooltip";
import { StatusBadge } from "../StatusBadge/StatusBadge";
import styles from "./TagInput.module.css";
import { Icon } from "../Icon";

const ERROR_MESSAGES = {
  DUPLICATE: "Duplicated values are not allowed",
  INVALID_INPUT: "Please provide a valid input",
  MAX_VALUES: "Max number of values reached",
};

export interface TagInputProps {
  value?: any[];
  onChange?: (value: any[]) => void;
  labelValue?: string;
  errorMessage?: string;
  infoMessage?: string;
  disabled?: boolean;
  required?: boolean;
  allowDuplicate?: boolean;
  max?: number;
  isError?: boolean;
  placeholder?: string;
  mask?: "cpf" | "cnpj" | "cep" | "domain" | "url" | "email";
  icon?: string;
  appendIcon?: boolean;
  tooltipMinWidth?: number;
  children?: React.ReactNode;
  className?: string;
}

function PrependIcon({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}

function AppendIcon({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}

function Hint({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}

export function TagInput({
  value,
  onChange,
  labelValue,
  errorMessage,
  infoMessage,
  disabled = false,
  required = false,
  allowDuplicate = false,
  max,
  isError = false,
  placeholder = "",
  mask,
  icon,
  appendIcon = false,
  tooltipMinWidth,
  children,
  className,
}: TagInputProps) {
  const [tags, setTags] = useControllable<any[]>({
    value,
    defaultValue: [],
    onChange,
  });

  const [newTag, setNewTag] = useState("");
  const [hasError, setHasError] = useState(false);
  const [errorMsg, setErrorMsg] = useState("");
  const [isFocused, setIsFocused] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const errorTimerRef = useRef<ReturnType<typeof setTimeout> | undefined>(
    undefined,
  );

  useEffect(() => {
    return () => clearTimeout(errorTimerRef.current);
  }, []);

  function showError(msg: string) {
    setHasError(true);
    setErrorMsg(msg);
    clearTimeout(errorTimerRef.current);
    errorTimerRef.current = setTimeout(() => {
      setHasError(false);
      setErrorMsg("");
    }, 2000);
  }

  function addTag(rawValue: string) {
    const trimmed = rawValue.trim();
    if (isNilAndBlank(trimmed)) return;

    if (mask) {
      const masked = applyMask(trimmed, mask);
      if (masked !== trimmed) {
        showError(ERROR_MESSAGES.INVALID_INPUT);
        return;
      }
    }

    const currentTags = tags ?? [];

    if (!allowDuplicate && currentTags.includes(trimmed)) {
      showError(ERROR_MESSAGES.DUPLICATE);
      return;
    }

    if (max !== undefined && currentTags.length >= max) {
      showError(ERROR_MESSAGES.MAX_VALUES);
      return;
    }

    setTags([...currentTags, trimmed]);
    setNewTag("");
  }

  function removeTag(index: number) {
    if (newTag !== "") return;
    setTags((tags ?? []).filter((_, i) => i !== index));
  }

  function handleKeyDown(e: React.KeyboardEvent<HTMLTextAreaElement>) {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      addTag(newTag);
    } else if (e.key === "Tab") {
      e.preventDefault();
      if (newTag) addTag(newTag);
    } else if (e.key === "Backspace" && newTag === "") {
      const currentTags = tags ?? [];
      removeTag(currentTags.length - 1);
    }
  }

  function handlePaste(e: React.ClipboardEvent<HTMLTextAreaElement>) {
    e.preventDefault();
    const text = e.clipboardData.getData("text");
    const newItems = text
      .split(/[,\n]/)
      .map((s) => s.trim())
      .filter(Boolean);

    if (newItems.length === 0) return;

    const currentTags = tags ?? [];
    const toAdd: string[] = [];

    for (const item of newItems) {
      if (isNilAndBlank(item)) continue;
      if (mask) {
        const masked = applyMask(item, mask);
        if (masked !== item) continue;
      }
      const workingList = [...currentTags, ...toAdd];
      if (!allowDuplicate && workingList.includes(item)) continue;
      if (max !== undefined && workingList.length >= max) break;
      toAdd.push(item);
    }

    if (toAdd.length > 0) {
      setTags([...currentTags, ...toAdd]);
      setNewTag("");
    }
  }

  let prependIconChild: React.ReactNode = null;
  let appendIconChild: React.ReactNode = null;
  let hintChild: React.ReactNode = null;

  Children.forEach(children, (child) => {
    if (isValidElement(child)) {
      const childProps = child.props as Record<string, unknown>;
      if (child.type === PrependIcon)
        prependIconChild = childProps.children as React.ReactNode;
      else if (child.type === AppendIcon)
        appendIconChild = childProps.children as React.ReactNode;
      else if (child.type === Hint)
        hintChild = childProps.children as React.ReactNode;
    }
  });

  const currentTags = tags ?? [];

  return (
    <div className={clsx(styles.tagInput, "tag-input", className)}>
      {labelValue && (
        <div className={styles.labelRow}>
          <Label
            labelValue={labelValue}
            infoMessage={infoMessage}
            tooltipMinWidth={tooltipMinWidth}
            required={required}
          />
          {max !== undefined && max > 0 && (
            <span className="text-neutral-foreground-low font-bold text-xs">
              {currentTags.length} / {max}
            </span>
          )}
        </div>
      )}

      <div
        className={clsx(
          styles.container,
          isFocused && !disabled && styles.focused,
          (isError || hasError) && styles.error,
          disabled && styles.disabled,
          hasError && styles.shake,
        )}
        onClick={() => textareaRef.current?.focus()}
      >
        {prependIconChild
          ? prependIconChild
          : icon &&
            !appendIcon && (
              <Icon
                className={clsx(
                  styles.tagInputIcon,
                  isFocused && !disabled && styles.focused,
                )}
                name={icon}
              />
            )}

        {currentTags.map((tag, index) => (
          <Tooltip key={index} position="bottom" className="max-w-full">
            <Tooltip.Label>
              <div className="max-w-[100%]">
                <span className="whitespace-normal break-all">
                  {String(tag)}
                </span>
              </div>
            </Tooltip.Label>
            <StatusBadge
              labelValue={String(tag)}
              color="neutral"
              size="small"
              closeable
              onClose={() => removeTag(index)}
            />
          </Tooltip>
        ))}

        <textarea
          ref={textareaRef}
          className={styles.textarea}
          rows={1}
          value={newTag}
          onChange={(e) => setNewTag(e.target.value)}
          onKeyDown={handleKeyDown}
          onPaste={handlePaste}
          onFocus={() => setIsFocused(true)}
          onBlur={() => setIsFocused(false)}
          placeholder={currentTags.length === 0 ? placeholder : ""}
          disabled={disabled}
        />

        {appendIconChild
          ? appendIconChild
          : appendIcon &&
            icon && (
              <Icon
                className={clsx(
                  styles.tagInputIcon,
                  isFocused && !disabled && styles.focused,
                )}
                name={icon}
              />
            )}
      </div>

      {hintChild && (
        <label className="text-neutral-foreground-low text-sm">
          {hintChild}
        </label>
      )}

      {(isError || hasError) && (
        <p className={styles.errorMessage}>{errorMsg || errorMessage}</p>
      )}
    </div>
  );
}

TagInput.PrependIcon = PrependIcon;
TagInput.AppendIcon = AppendIcon;
TagInput.Hint = Hint;

// src/components/TagInput/TagInput.vue
<script setup lang="ts">
import { onMounted, ref, watch } from "vue";
import {
  isNilAndBlank,
  applyMask,
  isValidEmail,
  isValidDomain,
  isValidUrl,
} from "../../utils/index";
import Label from "../../utils/components/Label.vue";

const props = withDefaults(
  defineProps<{
    modelValue: any[];
    labelValue?: string;
    errorMessage?: string;
    infoMessage?: string;
    disabled?: boolean;
    required?: boolean;
    allowDuplicate?: boolean;
    max?: number;
    isError?: boolean;
    placeholder?: string;
    mask?: "cpf" | "cnpj" | "cep" | "domain" | "url" | "email";
    icon?: string;
    appendIcon?: boolean;
  }>(),
  {
    modelValue: undefined,
    labelValue: "",
    errorMessage: "",
    infoMessage: "",
    disabled: false,
    required: false,
    allowDuplicate: false,
    max: undefined,
    isError: false,
    placeholder: "",
    mask: undefined,
    icon: "",
    appendIcon: false,
  }
);

const emit = defineEmits<{
  "update:modelValue": [value: any[]];
}>();

onMounted(() => {
  addToTagList();
});

let tags: any = ref([]);
const isFocused = ref(false);
const newTag = ref("");
const hasError = ref(false);
const errMessage = ref("");
const tagInput = ref<HTMLTextAreaElement | null>(null);

const ERROR_MESSAGES = {
  DUPLICATE: "Duplicated values are not allowed",
  INVALID_INPUT: "Please provide a valid input",
  MAX_VALUES: "Max number of values reached",
};

watch(
  () => props.modelValue,
  () => {
    addToTagList();
  }
);

function focusInput() {
  if (props.disabled) return;

  const input = tagInput.value?.querySelector("#input-default") as HTMLTextAreaElement;
  if (input) input.focus();
}

function addTagOnTab(e: KeyboardEvent) {
  if (e.shiftKey || isNilAndBlank(newTag.value)) return;

  e.preventDefault();
  addTag(newTag.value);
}

function addToTagList() {
  tags.value = props.modelValue || [];
}

function addTag(tag: string) {
  if (hasError.value) return;

  if (isNilAndBlank(tag)) return;

  if (checkMultipleValues(tag)) {
    const urls = tag.split(/,|\n/).map((url) => url.trim());
    if (urls.length > 0) {
      urls.forEach((url) => {
        if (!checkErrors(url)) tags.value.push(url);
        resetFields();
      });
    }
  } else {
    if (!checkErrors(tag)) {
      tags.value.push(tag);
      resetFields();
    }
  }
  emit("update:modelValue", tags.value);
}

function checkErrors(url: string) {
  hasError.value = false;
  if (!props.allowDuplicate && checkDuplicate(url)) {
    setErrorMessage(ERROR_MESSAGES.DUPLICATE);
    return true;
  } else if (url.trim().length === 0) {
    setErrorMessage(ERROR_MESSAGES.INVALID_INPUT);
    return true;
  } else if (
    props.max !== undefined &&
    props.max > 0 &&
    tags.value.length > props.max - 1
  ) {
    setErrorMessage(ERROR_MESSAGES.MAX_VALUES);
    return true;
  }

  return false;
}

function resetErrorAfterTimeout() {
  setTimeout(() => {
    hasError.value = false;
  }, 2000);
}

function checkDuplicate(tag: string) {
  return tags.value.includes(tag);
}

function checkMultipleValues(tag: string) {
  return tag.includes(",") || tag.includes("\n");
}

function setErrorMessage(message: string) {
  errMessage.value = message;
  hasError.value = true;
  resetErrorAfterTimeout();
}

function resetFields() {
  errMessage.value = "";
  newTag.value = "";
  hasError.value = false;
}

function removeTag(index: number) {
  if (newTag.value.length) return;
  tags.value.splice(index, 1);
  emit("update:modelValue", tags.value);
}

function checkEmail(value: any) {
  hasError.value = !isValidEmail(value);
}

function checkDomain(value: any) {
  hasError.value = !isValidDomain(value);
}
function checkUrl(value: any) {
  hasError.value = !isValidUrl(value);
}

function applyMasks(e: any) {
  let maskedValue = e.target.value;
  maskedValue = applyMask(maskedValue, props.mask);

  if (props.mask == "email") checkEmail(maskedValue);
  else if (props.mask == "domain") checkDomain(maskedValue);
  else if (props.mask == "url") checkUrl(maskedValue);
}
</script>

<template>
  <div ref="tagInput" class="tag-input">
    <div
      class="flex justify-between items-center"
      v-if="labelValue"
    >
      <Label :label-value="labelValue" :info-message="infoMessage" :required="required" />
      <span
        v-if="max !== undefined && max > 0"
        class="text-neutral-foreground-low font-bold text-xs"
      >
        {{ tags.length }} / {{ max }}</span
      >
    </div>
    <div
      class="tag-input-container"
      :class="{
        active: isFocused && !disabled,
        error: hasError || isError,
        disabled: disabled,
      }"
      @click="focusInput"
    >
      <slot name="icon-slot">
        <Icon
          v-if="icon && !appendIcon"
          :name="icon"
          class="side-icon"
          :class="{ focused: isFocused && !disabled }"
        />
      </slot>
      <Tooltip
        v-for="(tag, index) in tags"
        :key="tag"
        position="bottom"
        class="max-w-full"
      >
        <StatusBadge
          color="neutral"
          class="tag-padding"
          size="small"
          :label-value="tag"
          :closeable="!disabled"
          @close="removeTag(Number(index))"
        />
        <template #label>
          <div class="max-w-[100%]">
            <span class="whitespace-normal break-all">{{ tag }}</span>
          </div>
        </template>
      </Tooltip>
      <textarea
        rows="1"
        v-model="newTag"
        id="input-default"
        class="input-default"
        :disabled="disabled"
        :placeholder="placeholder"
        @input="applyMasks"
        @focusout="isFocused = false"
        @focus="isFocused = true"
        @keydown.enter="
          (e) => {
            e.preventDefault();
            addTag(newTag);
          }
        "
        @keydown.tab="addTagOnTab"
        @keydown.backspace="removeTag(tags.length - 1)"
      />
      <slot name="appended-icon-slot">
        <Icon
          v-if="appendIcon && icon"
          :name="icon"
          class="side-icon"
          :class="{ focused: isFocused && !disabled }"
        />
      </slot>
    </div>
    <label v-if="$slots['hint-message']" class="p3 text-neutral-foreground-low">
      <slot name="hint-message" />
    </label>
    <label v-if="props.isError || hasError" class="error-default">{{
      props.errorMessage || errMessage
    }}</label>
  </div>
</template>

<style scoped>
@reference "../../assets/main.css";

.tag-input {
  @apply flex flex-col gap-xxs;
}

.tag-input-container {
  @apply flex flex-wrap gap-xxs outline-xxs outline-neutral-default rounded-base items-center py-xs px-sm bg-neutral-surface-default;
}

.tag-input-container.active {
  @apply outline-primary-interaction-default;
}

.tag-input-container.error {
  @apply outline-danger-default;
  animation: shake 0.5s;

  .input-default {
    @apply text-danger-foreground-high;
  }
}

.tag-input-container.disabled,
.tag-input-container.disabled .input-default {
  @apply bg-neutral-surface-disabled text-neutral-foreground-low outline-neutral-default;
}

.input-default {
  @apply p3 bg-transparent text-neutral-foreground-high rounded-base outline-none flex-1 p-xxs resize-none border-none placeholder:text-neutral-foreground-low;
}

.error-default {
  @apply text-danger-foreground-low p3;
}

.tag-default {
  @apply flex items-center gap-xxs;
}

.tag-padding {
  @apply py-xxs max-w-full;
}

.side-icon {
  @apply text-neutral-interaction-default;
}

.side-icon.focused {
  @apply text-primary-interaction-default;
}

@keyframes shake {
  0% {
    transform: translateX(0);
  }
  20% {
    transform: translateX(-5px);
  }
  40% {
    transform: translateX(5px);
  }
  60% {
    transform: translateX(-5px);
  }
  80% {
    transform: translateX(5px);
  }
  100% {
    transform: translateX(0);
  }
}
</style>
