// src/components/Drawer/Drawer.tsx
import { useRef } from 'react';
import clsx from 'clsx';
import { Overlay } from '../../utils/components/Overlay';
import { useControllable } from '../../hooks/useControllable';
import { useTransition } from '../../hooks/useTransition';
import { useModalFocus } from '../../hooks/useModalFocus';
import { trapFocus } from '../../utils';
import './Drawer.css';

export interface DrawerProps {
  value?: boolean;
  onChange?: (value: boolean) => void;
  position?: 'right' | 'left' | 'top' | 'bottom';
  size?: string;
  noOutsideClose?: boolean;
  zIndex?: number;
  children?: React.ReactNode;
  className?: string;
  'aria-label'?: string;
  'aria-labelledby'?: string;
}

export function Drawer({
  value,
  onChange,
  position = 'right',
  size = 'fit-content',
  noOutsideClose = false,
  zIndex = 1002,
  children,
  className,
  'aria-label': ariaLabel,
  'aria-labelledby': ariaLabelledby,
}: DrawerProps) {
  const [isOpen, setOpen] = useControllable<boolean>({ value, defaultValue: false, onChange });
  const { isMounted, isActive } = useTransition(isOpen ?? false, { duration: 500 });
  const drawerRef = useRef<HTMLDivElement>(null);

  useModalFocus(drawerRef, isOpen ?? false);

  const isMobile = typeof window !== 'undefined' && window.innerWidth < 768;
  const effectivePosition = isMobile ? 'bottom' : position;
  const effectiveWidth = isMobile ? '100%' : size;

  function getStyle() {
    if (position == 'top'|| position == 'bottom') return {
      height: size,
      maxHeight: 'calc(100% - var(--spacing-xl))',
    }

    return {
      width: effectiveWidth,
      maxWidth: 'calc(100% - var(--spacing-xl))',
    }
  }

  function handleOverlayClick() {
    if (noOutsideClose) {
      drawerRef.current?.classList.add('no-outside-close-warning');
      setTimeout(() => {
        drawerRef.current?.classList.remove('no-outside-close-warning');
      }, 100);
    } else {
      setOpen(false);
    }
  }

  function handleEscape(e: React.KeyboardEvent<HTMLDivElement>) {
    if (noOutsideClose) return;
    if (e.key !== 'Escape') return;

    e.stopPropagation();
    setOpen(false);
  }

  return (
    <Overlay value={isOpen} zIndex={zIndex} onClick={handleOverlayClick}>
      {isMounted && (
        <div
          ref={drawerRef}
          className={clsx('drawer', effectivePosition, isActive && 'active', className)}
          style={{ ...getStyle(), zIndex }}
          tabIndex={-1}
          role="dialog"
          aria-modal="true"
          aria-label={ariaLabel}
          aria-labelledby={ariaLabelledby}
          onKeyDown={(e) => {
            handleEscape(e);
            trapFocus(e, drawerRef.current);
          }}
        >
          {children}
        </div>
      )}
    </Overlay>
  );
}

// src/components/Drawer/Drawer.vue
<script setup lang="ts">
import { ref, computed, watch } from "vue";
import { useModalFocus } from "#composables";
import { trapFocus } from "../../utils";
import Overlay from "../../utils/components/Overlay.vue";

defineOptions({ inheritAttrs: false });

const props = withDefaults(
  defineProps<{
    modelValue?: boolean;
    size?: string;
    noOutsideClose?: boolean;
    position?: "top" | "bottom" | "left" | "right";
    zIndex?: number;
  }>(),
  {
    modelValue: false,
    size: "fit-content",
    noOutsideClose: false,
    position: "right",
    zIndex: 1002,
  }
);

const emit = defineEmits<{
  "update:modelValue": [value: any];
}>();

const model = ref(props.modelValue);
const drawer = ref<HTMLElement>();

const isMobile = computed(() => window.innerWidth < 768);

watch(
  () => props.modelValue,
  (cur) => {
    model.value = cur;
  }
);

useModalFocus(drawer, model);

function closeDialog() {
  if (!props.noOutsideClose) {
    model.value = false;
    emit("update:modelValue", false);
  }
}

function onEscape(e: KeyboardEvent) {
  if (props.noOutsideClose) return;

  e.stopPropagation();
  closeDialog();
}
</script>

<template>
  <Teleport to="body">
    <Overlay v-model="model" :z-index="zIndex" @click="closeDialog">
      <Transition name="slide-in">
        <div
          v-if="model"
          v-bind="$attrs"
          ref="drawer"
          class="drawer"
          :class="position"
          role="dialog"
          aria-modal="true"
          tabindex="-1"
          @keydown.esc="onEscape"
          @keydown="trapFocus($event, drawer)"
          :style="{
            zIndex: zIndex,
            width: position === 'left' || position === 'right' ? (isMobile ? '100%' : size) : '100%',
            height: position === 'top' || position === 'bottom' ? (isMobile ? '100%' : size) : '100%'
          }"
        >
          <slot />
        </div>
      </Transition>
    </Overlay>
  </Teleport>
</template>

<style scoped>
@reference "../../assets/main.css";

.drawer {
  @apply fixed bg-neutral-surface-default border-xxs border-neutral-default transform transition-transform outline-none;
}

.right {
  @apply top-0 right-0 h-screen rounded-l-base;
  max-width: calc(100% - var(--spacing-xl));
}

.left {
  @apply top-0 left-0 h-screen rounded-r-base;
  max-width: calc(100% - var(--spacing-xl));
}

.top {
  @apply top-0 left-0 w-screen rounded-b-base;
  max-height: calc(100% - var(--spacing-xl));
}

.bottom {
  @apply bottom-0 left-0 w-screen rounded-t-base;
  max-height: calc(100% - var(--spacing-xl));
}

.slide-in-enter-active,
.slide-in-leave-active {
  transition: transform 0.5s ease;
}

/* Right position animations */
.right.slide-in-enter-from,
.right.slide-in-leave-to {
  transform: translateX(100%);
}

.right.slide-in-enter-to,
.right.slide-in-leave-from {
  transform: translateX(0%);
}

/* Left position animations */
.left.slide-in-enter-from,
.left.slide-in-leave-to {
  transform: translateX(-100%);
}

.left.slide-in-enter-to,
.left.slide-in-leave-from {
  transform: translateX(0%);
}

/* Top position animations */
.top.slide-in-enter-from,
.top.slide-in-leave-to {
  transform: translateY(-100%);
}

.top.slide-in-enter-to,
.top.slide-in-leave-from {
  transform: translateY(0%);
}

/* Bottom position animations */
.bottom.slide-in-enter-from,
.bottom.slide-in-leave-to {
  transform: translateY(100%);
}

.bottom.slide-in-enter-to,
.bottom.slide-in-leave-from {
  transform: translateY(0%);
}

@media screen and (max-width: 768px) {
  .slide-in-enter-from,
  .slide-in-leave-to {
    transform: translateY(100%);
  }
  .slide-in-enter-to,
  .slide-in-leave-from {
    transform: translateY(0%);
  }

  .drawer {
    @apply w-full;
  }
}
</style>
