// src/components/Crop/Crop.tsx
import { useRef, useState, useEffect, useCallback, useId } from 'react';
import { getPosition } from '../../utils';
import { Icon } from '../Icon';
import { Slider } from '../Slider';
import styles from './Crop.module.css';

interface CropProps {
  src?: string;
  value?: string;
  onChange?: (croppedDataUrl: string) => void;
  width?: string;
  height?: string;
  className?: string;
}

export function Crop({
  src,
  onChange,
  width = '360px',
  height = '200px',
  className,
}: CropProps) {
  const maskId = useId();
  const bCropRef = useRef<HTMLDivElement>(null);
  const cropAreaRef = useRef<HTMLDivElement>(null);
  const selectedAreaRef = useRef<SVGRectElement>(null);
  const isDraggingRef = useRef(false);
  const parsedImgRef = useRef(new Image());
  const imgRef = useRef(new Image());

  const [zoom, setZoom] = useState(0);
  const [svgDims, setSvgDims] = useState({ width: 0, height: 0 });
  const [parsedImgSrc, setParsedImgSrc] = useState('');

  const resize = useCallback(() => {
    if (!bCropRef.current) return;
    setSvgDims({
      width: bCropRef.current.clientWidth ? bCropRef.current.clientWidth + 10 : 0,
      height: bCropRef.current.clientHeight ? bCropRef.current.clientHeight + 10 : 0,
    });
  }, []);

  const crop = useCallback((cropArea: HTMLDivElement, parent: HTMLElement) => {
    const rect = cropArea.getBoundingClientRect();
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    canvas.width = rect.width;
    canvas.height = rect.height;

    const parentRect = parent.getBoundingClientRect();
    const cropLeft = rect.left - parentRect.left;
    const cropTop = rect.top - parentRect.top;

    ctx.drawImage(
      parsedImgRef.current,
      cropLeft,
      cropTop,
      rect.width,
      rect.height,
      0,
      0,
      rect.width,
      rect.height
    );

    const croppedImage = canvas.toDataURL('image/png');
    onChange?.(croppedImage);
  }, [onChange]);

  const updateCropArea = useCallback((event: any) => {
    if (
      !cropAreaRef.current ||
      !cropAreaRef.current.parentElement ||
      !selectedAreaRef.current ||
      !isDraggingRef.current
    )
      return;

    const clamped = getPosition(
      event,
      cropAreaRef.current,
      cropAreaRef.current.parentElement,
      { left: true, top: true },
      { x: -1, y: -3 }
    );
    cropAreaRef.current.style.top = `${clamped.y}px`;
    cropAreaRef.current.style.left = `${clamped.x}px`;
    selectedAreaRef.current.setAttribute('x', clamped.x.toString());
    selectedAreaRef.current.setAttribute('y', clamped.y.toString());

    crop(cropAreaRef.current, cropAreaRef.current.parentElement);
  }, [crop]);

  const changeZoom = useCallback((zoomVal: number) => {
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (!cropAreaRef.current || !cropAreaRef.current.parentElement || !ctx) return;

    const img = imgRef.current;
    const parsedZoom = zoomVal + 1;

    const parentRect = cropAreaRef.current.parentElement.getBoundingClientRect();
    const rect = cropAreaRef.current.getBoundingClientRect();
    canvas.width = parentRect.width;
    canvas.height = parentRect.height;

    const sourceX = (parentRect.width - img.width) / 2;
    const sourceY = (parentRect.height - img.height) / 2;

    ctx.drawImage(img, sourceX, sourceY);
    const zoomX = rect.left + rect.width / 2 - parentRect.left;
    const zoomY = rect.top + rect.height / 2 - parentRect.top;

    ctx.clearRect(0, 0, canvas.width, canvas.height);

    ctx.save();
    ctx.translate(zoomX, zoomY);
    ctx.scale(parsedZoom, parsedZoom);
    ctx.translate(-zoomX, -zoomY);
    ctx.drawImage(img, sourceX, sourceY);
    ctx.restore();

    const croppedImage = canvas.toDataURL('image/png');
    const newImg = new Image();
    newImg.src = croppedImage;
    newImg.onload = () => {
      parsedImgRef.current = newImg;
      setParsedImgSrc(croppedImage);
      if (cropAreaRef.current && cropAreaRef.current.parentElement) {
        crop(cropAreaRef.current, cropAreaRef.current.parentElement);
      }
    };
  }, [crop]);

  useEffect(() => {
    const handleMouseMove = (e: MouseEvent) => updateCropArea(e);
    const handleMouseUp = () => { isDraggingRef.current = false; };
    const handleTouchMove = (e: TouchEvent) => updateCropArea(e.touches[0]);
    const handleTouchEnd = () => { isDraggingRef.current = false; };

    window.addEventListener('mousemove', handleMouseMove);
    window.addEventListener('mouseup', handleMouseUp);
    window.addEventListener('touchmove', handleTouchMove);
    window.addEventListener('touchend', handleTouchEnd);

    let resizeObserver: ResizeObserver | undefined;
    if (bCropRef.current) {
      resizeObserver = new ResizeObserver(resize);
      resizeObserver.observe(bCropRef.current, { box: 'border-box' });
    }

    if (src) {
      imgRef.current.src = src;
      imgRef.current.onload = () => {
        setParsedImgSrc(src);
        parsedImgRef.current = imgRef.current;
        changeZoom(0);
      };
    }

    return () => {
      window.removeEventListener('mousemove', handleMouseMove);
      window.removeEventListener('mouseup', handleMouseUp);
      window.removeEventListener('touchmove', handleTouchMove);
      window.removeEventListener('touchend', handleTouchEnd);
      resizeObserver?.disconnect();
    };
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  function startDragging(event: React.MouseEvent) {
    isDraggingRef.current = true;
    updateCropArea(event.nativeEvent);
  }

  function startDraggingTouch(event: React.TouchEvent) {
    isDraggingRef.current = true;
    updateCropArea(event.touches[0]);
  }

  function onCropAreaKeyDown(event: React.KeyboardEvent<HTMLDivElement>) {
    const directions: Record<string, [number, number]> = {
      ArrowLeft: [-1, 0],
      ArrowRight: [1, 0],
      ArrowUp: [0, -1],
      ArrowDown: [0, 1],
    };
    const direction = directions[event.key];
    const area = cropAreaRef.current;
    const parent = area?.parentElement;
    if (!direction || !area || !parent || !selectedAreaRef.current) return;

    event.preventDefault();
    const step = event.shiftKey ? 50 : 10;
    const maxX = parent.clientWidth - area.offsetWidth;
    const maxY = parent.clientHeight - area.offsetHeight;
    const x = Math.min(maxX, Math.max(0, area.offsetLeft + direction[0] * step));
    const y = Math.min(maxY, Math.max(0, area.offsetTop + direction[1] * step));

    area.style.left = `${x}px`;
    area.style.top = `${y}px`;
    selectedAreaRef.current.setAttribute('x', x.toString());
    selectedAreaRef.current.setAttribute('y', y.toString());
    crop(area, parent);
  }

  function handleZoomChange(val: number | [number, number]) {
    const v = typeof val === 'number' ? val : val[0];
    setZoom(v);
    changeZoom(v);
  }

  const computedBorderRadius = (() => {
    if (bCropRef.current) {
      return getComputedStyle(bCropRef.current).getPropertyValue('--border-radius-xl') || '16px';
    }
    return '16px';
  })();

  return (
    <div ref={bCropRef} className={`${styles.crop} crop${className ? ` ${className}` : ''}`}>
      <div
        className="relative w-full h-full bg-black rounded-xl"
        style={{ minWidth: width, minHeight: height }}
      >
        <div className={styles.cropImg} onClick={startDragging}>
          <svg
            className="absolute z-[1]"
            width={`${svgDims.width || 0}px`}
            height={`${svgDims.height || 0}px`}
            viewBox={`0 0 ${svgDims.width || 0} ${svgDims.height || 0}`}
            xmlns="http://www.w3.org/2000/svg"
          >
            <defs>
              <mask id={maskId}>
                <rect width="100%" height="100%" fill="white" />
                <rect
                  ref={selectedAreaRef}
                  x="0"
                  y="0"
                  width={width}
                  height={height}
                  rx={computedBorderRadius}
                  ry={computedBorderRadius}
                  fill="black"
                />
              </mask>
            </defs>
            <rect
              width="100%"
              height="100%"
              fill="rgba(255, 255, 255, 0.7)"
              mask={`url(#${maskId})`}
            />
          </svg>
          {parsedImgSrc && <img src={parsedImgSrc} alt="model value" />}
          {src && <img src={src} style={{ position: 'relative', visibility: 'hidden' }} alt="" />}
        </div>
        <div
          ref={cropAreaRef}
          className={styles.cropArea}
          style={{ width, height }}
          tabIndex={0}
          aria-label="Crop area"
          onMouseDown={startDragging}
          onTouchStart={startDraggingTouch}
          onKeyDown={onCropAreaKeyDown}
        />
      </div>
      <footer className={styles.footer}>
        <Icon name="zoom_out" className="select-none leading-xxs" />
        <Slider
          value={zoom}
          onChange={handleZoomChange}
          size="small"
          max={2}
        />
        <Icon name="zoom_in" className="select-none leading-xxs" />
      </footer>
    </div>
  );
}

// src/components/Crop/Crop.vue
<script setup lang="ts">
import { getPosition } from "../../utils/index";
import { ref, onMounted, onBeforeUnmount, onUpdated, computed } from "vue";

const props = withDefaults(
  defineProps<{
    modelValue?: string;
    src: string;
    width?: string;
    height?: string;
  }>(),
  {
    modelValue: undefined,
    src: undefined,
    width: "360px",
    height: "200px",
  }
);

const isDraggingArea = ref(false);
const bCrop = ref<HTMLDivElement>();
const cropArea = ref<HTMLDivElement>();
const selectedArea = ref<Element>();
const zoom = ref(0);
const parsedImg = ref(new Image());
const img = new Image();
img.src = props.src;
const svgProperty = ref({
  width: 0,
  height: 0,
});
const resizeObserver = new ResizeObserver(resize);
const computedBorderRadius = computed((): string => {
  if (
    document.readyState === "complete" ||
    document.readyState === "interactive"
  ) {
    return (
      (bCrop.value as any)
        ?.computedStyleMap()
        .get("--border-radius-xl")
        ?.toString() || "16px"
    );
  }
  return "16px";
});

const emit = defineEmits<{
  "update:modelValue": [value: string];
}>();

onMounted(async () => {
  window.addEventListener("mousemove", updateCropArea);
  window.addEventListener("mouseup", () => {
    isDraggingArea.value = false;
  });

  window.addEventListener("touchmove", updateCropAreaTouch);
  window.addEventListener("touchend", () => {
    isDraggingArea.value = false;
  });

  if (bCrop.value) resizeObserver.observe(bCrop.value, { box: "border-box" });
  img.onload = () => {
    changeZoom(zoom.value);
  };
});

onUpdated(resize);

onBeforeUnmount(() => {
  if (resizeObserver) resizeObserver.disconnect();

  window.removeEventListener("mousemove", updateCropArea);
  window.removeEventListener("mouseup", () => {
    isDraggingArea.value = false;
  });

  window.removeEventListener("touchmove", updateCropAreaTouch);
  window.removeEventListener("touchend", () => {
    isDraggingArea.value = false;
  });
});

function resize() {
  svgProperty.value.width = bCrop.value?.clientWidth
    ? bCrop.value?.clientWidth + 10
    : 0;
  svgProperty.value.height = bCrop.value?.clientHeight
    ? bCrop.value?.clientHeight + 10
    : 0;
}

function startDraggingAreaTouch(event: TouchEvent) {
  isDraggingArea.value = true;
  updateCropAreaTouch(event);
}

function startDraggingArea(event: MouseEvent) {
  isDraggingArea.value = true;
  updateCropArea(event);
}

function updateCropAreaTouch(event: TouchEvent) {
  updateCropArea(event.touches[0]);
}

function updateCropArea(event: any) {
  if (
    !cropArea.value ||
    !cropArea.value.parentElement ||
    !selectedArea.value ||
    !isDraggingArea.value
  )
    return;

  const clamped = getPosition(
    event,
    cropArea.value,
    cropArea.value.parentElement,
    { left: true, top: true },
    { x: -1, y: -3 }
  );
  cropArea.value.style.top = `${clamped.y}px`;
  cropArea.value.style.left = `${clamped.x}px`;
  selectedArea.value.setAttribute("x", clamped.x.toString());
  selectedArea.value.setAttribute("y", clamped.y.toString());

  crop(cropArea.value, cropArea.value.parentElement);
}

function onCropAreaKeyDown(event: KeyboardEvent) {
  const directions: Record<string, [number, number]> = {
    ArrowLeft: [-1, 0],
    ArrowRight: [1, 0],
    ArrowUp: [0, -1],
    ArrowDown: [0, 1],
  };
  const direction = directions[event.key];
  const area = cropArea.value;
  const parent = area?.parentElement;
  if (!direction || !area || !parent || !selectedArea.value) return;

  event.preventDefault();
  const step = event.shiftKey ? 50 : 10;
  const maxX = parent.clientWidth - area.offsetWidth;
  const maxY = parent.clientHeight - area.offsetHeight;
  const x = Math.min(maxX, Math.max(0, area.offsetLeft + direction[0] * step));
  const y = Math.min(maxY, Math.max(0, area.offsetTop + direction[1] * step));

  area.style.left = `${x}px`;
  area.style.top = `${y}px`;
  selectedArea.value.setAttribute("x", x.toString());
  selectedArea.value.setAttribute("y", y.toString());
  crop(area, parent);
}

function changeZoom(zoom: number) {
  const canvas = document.createElement("canvas");
  const ctx = canvas.getContext("2d");
  if (!cropArea.value || !cropArea.value.parentElement || !ctx) return;

  const parsedZoom = zoom + 1;

  const parentRect = cropArea.value.parentElement.getBoundingClientRect();
  const rect = cropArea.value.getBoundingClientRect();
  canvas.width = parentRect.width;
  canvas.height = parentRect.height;

  const sourceX = (parentRect.width - img.width) / 2;
  const sourceY = (parentRect.height - img.height) / 2;

  ctx.drawImage(img, sourceX, sourceY);
  const zoomX = rect.left + rect.width / 2 - parentRect.left;
  const zoomY = rect.top + rect.height / 2 - parentRect.top;

  ctx.clearRect(0, 0, canvas.width, canvas.height);

  ctx.save();
  ctx.translate(zoomX, zoomY);
  ctx.scale(parsedZoom, parsedZoom);
  ctx.translate(-zoomX, -zoomY);
  ctx.drawImage(img, sourceX, sourceY);
  ctx.restore();

  const croppedImage = canvas.toDataURL("image/png");
  parsedImg.value = new Image();
  parsedImg.value.src = croppedImage;
  parsedImg.value.onload = () => {
    if (!cropArea.value || !cropArea.value.parentElement) return;
    crop(cropArea.value, cropArea.value.parentElement);
  };
}

function crop(cropArea: HTMLDivElement, parent: HTMLElement) {
  const rect = cropArea.getBoundingClientRect();
  const canvas = document.createElement("canvas");
  const ctx = canvas.getContext("2d");
  if (!ctx) return;

  canvas.width = rect.width;
  canvas.height = rect.height;

  const parentRect = parent.getBoundingClientRect();
  const cropLeft = rect.left - parentRect.left;
  const cropTop = rect.top - parentRect.top;

  const sourceX = cropLeft;
  const sourceY = cropTop;
  const sourceWidth = rect.width;
  const sourceHeight = rect.height;

  ctx.drawImage(
    parsedImg.value as HTMLImageElement,
    sourceX,
    sourceY,
    sourceWidth,
    sourceHeight,
    0,
    0,
    rect.width,
    rect.height
  );

  const croppedImage = canvas.toDataURL("image/png");
  emit("update:modelValue", croppedImage);
}
</script>

<template>
  <div ref="bCrop" class="crop">
    <div
      class="relative w-full h-full bg-black rounded-xl"
      :style="{ 'min-width': width, 'min-height': height }"
    >
      <div class="crop-img" @click="startDraggingArea">
        <svg
          class="absolute z-[1]"
          :width="svgProperty.width || 0 + 'px'"
          :height="svgProperty.height || 0 + 'px'"
          :viewBox="`0 0 ${svgProperty.width || 0} ${svgProperty.height || 0}`"
          xmlns="http://www.w3.org/2000/svg"
        >
          <defs>
            <mask id="highlight-mask">
              <rect width="100%" height="100%" fill="white" />
              <rect
                ref="selectedArea"
                x="0"
                y="0"
                :width="width"
                :height="height"
                :rx="computedBorderRadius"
                :ry="computedBorderRadius"
                fill="black"
              />
            </mask>
          </defs>
          <rect
            width="100%"
            height="100%"
            fill="rgba(255, 255, 255, 0.7)"
            mask="url(#highlight-mask)"
          />
        </svg>
        <img :src="parsedImg.src" alt="model value" />
        <img :src="src" style="position: relative; visibility: hidden" />
      </div>
      <div
        ref="cropArea"
        class="crop-area"
        :style="{ width: width, height: height }"
        tabindex="0"
        aria-label="Crop area"
        @mousedown="startDraggingArea"
        @touchstart="startDraggingAreaTouch"
        @keydown="onCropAreaKeyDown"
      />
    </div>
    <footer>
      <Icon name="zoom_out" class="select-none leading-xxs" />
      <Slider
        v-model="zoom"
        size="small"
        :max="2"
        @update:model-value="(value: number | number[]) => changeZoom(value as number)"
      />
      <Icon name="zoom_in" class="select-none leading-xxs" />
    </footer>
  </div>
</template>

<style scoped>
@reference "../../assets/main.css";

.crop {
  @apply flex flex-col gap-xs rounded-xl w-full h-full;
}

.crop-area {
  @apply z-[2] absolute w-full border-xxs border-primary-default bg-transparent top-0 cursor-move rounded-xl;
}

.crop-img {
  @apply relative w-full h-full overflow-hidden rounded-xl bg-black;

  img {
    @apply absolute select-none;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%) scale(1);
  }
}

footer {
  @apply flex items-center gap-base;
  margin: 0 10%;
}
</style>
