// src/components/DatePicker/DatePicker.tsx
import { useState } from "react";
import clsx from "clsx";
import { useControllable } from "../../hooks";
import { checkDateType } from "../../utils";
import { ExpandableContainer } from "../../utils/components/ExpandableContainer";
import { Calendar } from "../Calendar/Calendar";
import { Button } from "../Button/Button";
import { Checkbox } from "../Checkbox/Checkbox";
import { Icon } from "../Icon/Icon";
import styles from "./DatePicker.module.css";

type SelectionType = "date" | "period" | "compare";

export interface DatePickerProps {
  value?: Date | Date[] | [Date[], Date[]];
  onChange?: (value: any) => void;
  type?: SelectionType;
  minDate?: Date;
  maxDate?: Date;
  disabledDates?: Date[];
  disabled?: boolean;
  labelValue?: string;
  isError?: boolean;
  errorMessage?: string;
  infoMessage?: string;
  required?: boolean;
  clearLabel?: string;
  applyLabel?: string;
  compareLabel?: string;
  lang?: string;
  onApply?: (value: any) => void;
  separator?: string;
  isCompare?: boolean;
  allowChangeType?: boolean;
  expanded?: boolean;
  onExpandedChange?: (expanded: boolean) => void;
  options?: Array<{
    label: string;
    value: string | [string, string];
    selected?: boolean;
    calculate?: () => Date[];
  }>;
  hideActions?: boolean;
  onClear?: () => void;
  onTypeChange?: (type: SelectionType) => void;
  className?: string;
  children?: React.ReactNode;
  actions?: React.ReactNode;
}

function formatDate(date: Date, lang: string): string {
  return new Date(date).toLocaleDateString(lang, {
    year: "numeric",
    month: "short",
    day: "2-digit",
  });
}

function getAnd(lang: string): string {
  return lang.includes("pt") ? "e" : "and";
}

function buildDisplayLabel(
  value: Date | Date[] | [Date[], Date[]] | undefined,
  type: SelectionType,
  lang: string,
  separator?: string,
): string {
  if (!value) return "";

  const model = checkDateType(value as any, type);

  if (type === "compare") {
    const ranges = model as Date[][];
    const range0 = ranges[0] ?? [];
    const range1 = ranges[1] ?? [];

    if (range1.length > 0) {
      const sep = separator ?? getAnd(lang);
      const r0 =
        formatDate(range0[0], lang) +
        (range0[1] ? " - " + formatDate(range0[1], lang) : "");
      const r1 =
        formatDate(range1[0], lang) +
        (range1[1] ? " - " + formatDate(range1[1], lang) : "");
      return `${r0} ${sep} ${r1}`;
    } else if (range0.length > 0) {
      return (
        formatDate(range0[0], lang) +
        (range0[1] ? " - " + formatDate(range0[1], lang) : "")
      );
    }
    return "";
  }

  const dates = model as Date[];
  if (dates.length === 0) return "";

  const label =
    formatDate(dates[0], lang) +
    (dates[1] && type !== "date" ? " - " + formatDate(dates[1], lang) : "");
  return label;
}

export function DatePicker({
  value,
  onChange,
  type = "date",
  minDate,
  maxDate,
  disabledDates,
  disabled = false,
  labelValue = "",
  isError = false,
  errorMessage = "",
  infoMessage = "",
  required = false,
  clearLabel = "Clear selection",
  applyLabel = "Apply filters",
  compareLabel = "Compare dates",
  lang = "en",
  onApply,
  separator,
  isCompare = false,
  allowChangeType = false,
  expanded,
  onExpandedChange,
  options,
  hideActions = false,
  onClear,
  onTypeChange,
  className,
  children,
  actions,
}: DatePickerProps) {
  const [controlledValue, setControlledValue] = useControllable<
    Date | Date[] | [Date[], Date[]] | undefined
  >({
    value,
    onChange,
  });

  const [controlledType, setControlledType] = useControllable<SelectionType>({
    value: type,
    defaultValue: type,
    onChange: onTypeChange,
  });

  const [isOpen, setIsOpen] = useControllable<boolean>({
    value: expanded,
    defaultValue: false,
    onChange: onExpandedChange,
  });

  const [selectedPreset, setSelectedPreset] = useState<string | null>(null);

  const [isMulti, setIsMulti] = useState(
    isCompare || controlledType === "compare",
  );

  function handleExpand(isOpenVal: boolean) {
    setIsOpen(isOpenVal);
  }

  function handleCalendarChange(newValue: any) {
    setControlledValue(newValue);
    setSelectedPreset(null);
  }

  function handleClear() {
    setControlledValue(undefined as any);
    setSelectedPreset(null);
    onClear?.();
  }

  function handleApply() {
    setIsOpen(false);
    onApply?.(controlledValue);
  }

  function handlePresetSelect(opt: {
    label: string;
    value: string | [string, string];
    calculate?: () => Date[];
  }) {
    setSelectedPreset(opt.label);
    if (opt.calculate) {
      const dates = opt.calculate();
      setControlledValue(dates as any);
    }
  }

  function isPresetSelected(opt: {
    label: string;
    value: string | [string, string];
  }): boolean {
    return selectedPreset === opt.label;
  }

  function handleChangeType(checked: boolean | null) {
    const newIsMulti = !!checked;
    setIsMulti(newIsMulti);
    setControlledType(newIsMulti ? "compare" : "period");
  }

  const triggerContent = (
    <div
      className={clsx(
        "flex items-center text-lg text-neutral-interaction-default",
        {
          expanded: isOpen,
          error: isError,
          disabled,
        },
      )}
    >
      <Icon name="calendar_month" className={styles.calendarIcon} />
      <h5 className={clsx("whitespace-nowrap ml-xs", { "font-bold": isOpen })}>
        <span className={styles.displayLabel}>
          {buildDisplayLabel(
            controlledValue,
            controlledType!,
            lang,
            separator,
          ) ||
            children ||
            "\u00A0"}
        </span>
      </h5>
    </div>
  );

  const hasPresetSidebar =
    ((options && options.length) || allowChangeType) &&
    controlledType != "date";

  const cardContent = (
    <div>
      <div className="flex">
        {hasPresetSidebar && (
          <div className={styles.presetSidebar}>
            <div className="flex flex-col">
              {options &&
                options.map((opt, i) => (
                  <button
                    key={i}
                    className={clsx(
                      styles.presetOption,
                      isPresetSelected(opt) && styles.presetActive,
                    )}
                    onClick={() => handlePresetSelect(opt)}
                  >
                    {opt.label}
                  </button>
                ))}
            </div>
            {allowChangeType && (
              <div className="px-xs py-sm">
                <Checkbox value={isMulti} onChange={handleChangeType}>
                  {compareLabel}
                </Checkbox>
              </div>
            )}
          </div>
        )}

        <div className="flex flex-col items-end gap-base relative overflow-hidden flex-1">
          <div className="px-sm pt-xxs w-full">
            <Calendar
              value={controlledValue}
              onChange={handleCalendarChange}
              type={controlledType}
              minDate={minDate}
              maxDate={maxDate}
              disabledDates={disabledDates}
              lang={lang}
            />
          </div>

          {!hideActions && (
            <div className={styles.actions}>
              {actions || (
                <>
                  <Button
                    size="small"
                    variant="plain"
                    color="neutral"
                    onClick={handleClear}
                  >
                    {clearLabel}
                  </Button>
                  <Button
                    size="small"
                    variant="default"
                    color="primary"
                    onClick={handleApply}
                  >
                    {applyLabel}
                  </Button>
                </>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );

  return (
    <ExpandableContainer
      value={isOpen}
      onChange={(val) => handleExpand(val)}
      disabled={disabled}
      isError={isError}
      errorMessage={errorMessage}
      infoMessage={infoMessage}
      required={required}
      hideArrow
      card={cardContent}
      className={clsx("date-picker", className)}
      labelValue={labelValue}
    >
      {triggerContent}
    </ExpandableContainer>
  );
}

// src/components/DatePicker/DatePicker.vue
<script setup lang="ts">
import { ref, watch, onBeforeMount } from "vue";
import { dateOptions, checkDateType } from "../../utils";
import Option from "../../utils/components/Option.vue";
import ExpandableContainer from "../../utils/components/ExpandableContainer.vue";

type OptionType = {
  label: string;
  value: string;
  calculate: () => Date[];
  selected?: boolean;
  disabled?: boolean;
};
type Type = "date" | "period" | "compare";

const props = withDefaults(
  defineProps<{
    modelValue?: Date | Date[] | Date[][];
    labelValue?: string;
    lang?: string;
    separator?: string;
    type?: Type;
    isCompare?: boolean;
    allowChangeType?: boolean;
    minDate?: Date;
    maxDate?: Date;
    disabled?: boolean;
    required?: boolean;
    isError?: boolean;
    errorMessage?: string;
    expanded?: boolean;
    options?: OptionType[] | any;
    hideActions?: boolean;
  }>(),
  {
    lang: "en-US",
    labelValue: "",
    type: "date",
    isCompare: false,
    allowChangeType: false,
    disabled: false,
    required: false,
    isError: false,
    errorMessage: "",
    expanded: false,
    options: dateOptions,
    hideActions: false,
  }
);

const emit = defineEmits<{
  "update:modelValue": [value: Date | Date[] | Date[][]];
  "update:expanded": [value: boolean];
  "update:type": [value: Type];
  apply: [value: Date | Date[] | Date[][]];
  clear: [];
}>();

const model = ref<Date[] | Date[][]>([]);
const isExpanded = ref(props.expanded);
const isMulti = ref(props.type === "compare");
const optionSelected = ref(
  (props.options.length &&
    props.options.find((o: OptionType) => o.selected)?.value) ||
    ""
);
const formatedDate = ref("");

onBeforeMount(updateModel);

watch(
  () => props.modelValue,
  updateModel
);

watch(
  () => props.type,
  () => {
    isMulti.value = props.type === "compare";
    updateModel();
  }
);

watch(
  () => props.expanded,
  () => (isExpanded.value = props.expanded)
);

function updateModel() {
  let value = props.modelValue;
  if (optionSelected.value) {
    const option: OptionType = props.options.find(
      (o: OptionType) => o.value == optionSelected.value
    );
    value = option.calculate();
  }

  checkValidModel(value, !optionSelected.value);
}

function checkValidModel(value: Date | Date[] | Date[][] | undefined, updateFormatedDate = true) {
  model.value = checkDateType(value, props.type);
  if (updateFormatedDate) setFormatedDate();
}

function formatDate(date: Date, template?: any) {
  return date.toLocaleDateString(
    props.lang,
    template || { year: "numeric", month: "short", day: "2-digit" }
  );
}

function getAnd() {
  if (props.lang.includes("pt")) {
    return "e";
  }
  return "and";
}

function setFormatedDate() {
  if (model.value && Array.isArray(model.value[0])) {
    if (Array.isArray(model.value[1]) && model.value[1].length > 0) {
      formatedDate.value = `${
        formatDate(model.value[0][0]) +
        (model.value[0][1] ? " - " + formatDate(model.value[0][1]) : "")
      } ${props.separator || getAnd()} ${
        formatDate(model.value[1][0]) +
        (model.value[1][1] ? " - " + formatDate(model.value[1][1]) : "")
      }`;
    } else if (model.value[0].length > 0) {
      formatedDate.value =
        formatDate(model.value[0][0]) +
        (model.value[0][1] ? " - " + formatDate(model.value[0][1]) : "");
    } else {
      formatedDate.value = "";
    }
  } else if (
    model.value &&
    Array.isArray(model.value) &&
    model.value[0] instanceof Date
  ) {
    formatedDate.value =
      formatDate(model.value[0] as Date) +
      (model.value[1] && props.type != "date" ? " - " + formatDate(model.value[1] as Date) : "");
  } else {
    formatedDate.value = "";
  }

  if (formatedDate.value) optionSelected.value = "";
}

function setModel(value: any) {
  checkValidModel(value);
  emit(
    "update:modelValue",
    props.type == "date" ? model.value[0] : model.value
  );
}

function changeDate(option: OptionType) {
  setModel(option.calculate());
  formatedDate.value = "";
  optionSelected.value = option.value;
}

function clear() {
  setModel(undefined);
  emit("clear");
  optionSelected.value = "";
  formatedDate.value = "";
}

function changeType() {
  emit("update:type", isMulti.value ? "compare" : "period");
}
</script>

<template>
  <ExpandableContainer
    class="date-picker"
    v-model="isExpanded"
    :disabled="disabled"
    :required="required"
    :label-value="labelValue"
    :is-error="isError"
    :error-message="errorMessage"
    hide-arrow
    @update:modelValue="emit('update:expanded', isExpanded)"
  >
    <div
      class="flex items-center text-lg h-xl text-neutral-interaction-default"
      :class="{
        expanded: isExpanded,
        error: isError,
        disabled: disabled,
      }"
    >
      <Icon name="calendar_month" class="calendar-icon" />
    </div>
    <h5 class="whitespace-nowrap" :class="{ 'font-bold': isExpanded }">
      <span
        v-if="
          formatedDate ||
          options.find((o: OptionType) => o.value == optionSelected)?.label
        "
      >
        {{
          formatedDate ||
          options.find((o: OptionType) => o.value == optionSelected)?.label
        }}
      </span>
      <slot v-else />
    </h5>
    <template #content>
      <div class="flex content">
        <div
          class="flex flex-col justify-between border-r-xxs border-neutral-default w-fit truncate rounded-l-sm overflow-hidden p-xs"
          v-if="type !== 'date' && options.length"
        >
          <div class="flex flex-col">
            <Option
              v-for="(option, index) in options"
              :key="index"
              class="px-xs py-sm min-w-9xl"
              :selected="optionSelected == option.value"
              :disabled="option.disabled"
              @click="changeDate(option)"
            >
              {{ option.label }}
            </Option>
          </div>
          <div class="px-xs py-sm" v-if="allowChangeType">
            <Checkbox v-model="isMulti" @update:model-value="changeType">
              <slot name="compare-label"> Compare two periods </slot>
            </Checkbox>
          </div>
        </div>
        <div class="flex flex-col items-end gap-base relative overflow-hidden">
          <Calendar
            class="px-sm pt-xxs"
            v-model="model"
            :lang="lang"
            :type="type"
            :min-date="minDate"
            :max-date="maxDate"
            :double-calendar="type !== 'date'"
            @update:model-value="setModel"
          />
          <div
            class="flex items-center justify-end gap-xs w-full border-t-xxs border-neutral-default p-sm"
            v-if="!hideActions"
          >
            <slot name="actions">
              <Button size="small" variant="plain" @click="clear">
                <slot name="clear-label"> Clear </slot>
              </Button>
              <Button size="small" @click="emit('apply', model)">
                <slot name="apply-label"> Apply </slot>
              </Button>
            </slot>
          </div>
        </div>
      </div>
    </template>
  </ExpandableContainer>
</template>

<style scoped>
@reference "../../assets/main.css";

.calendar-icon.icon {
  @apply text-xl leading-xxs;
}

.expanded .icon {
  @apply text-primary-interaction-default;
}

.disabled .icon {
  @apply text-neutral-interaction-disabled;
}

.error .icon {
  @apply text-danger-interaction-default;
}
</style>
