// src/components/ActionCard/ActionCard.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from "vue";
import Card from "../Card/Card.vue";
import Icon from "../Icon/Icon.vue";

withDefaults(
  defineProps<{
    icon?: string;
    color?: string;
    hideDrag?: boolean;
  }>(),
  {
    icon: "",
    color: "",
    hideDrag: false,
  }
);

const isDragging = ref(false);

const emit = defineEmits<{
  dragstart: [event: Event];
  dragging: [event: Event];
  dragend: [event: Event];
  delete: [];
}>();

onMounted(() => {
  window.addEventListener("mousemove", move);
  window.addEventListener("mouseup", end);
  window.addEventListener("touchmove", move);
  window.addEventListener("touchend", end);
});

onBeforeUnmount(() => {
  window.removeEventListener("mousemove", move);
  window.removeEventListener("mouseup", end);
  window.removeEventListener("touchmove", move);
  window.removeEventListener("touchend", end);
});

function changeState(value: boolean, event: Event) {
  isDragging.value = value;
  if (value) emit("dragstart", event);
  else emit("dragend", event);
}

function start(event: Event) {
  changeState(true, getEvent(event));
}

function move(event: Event) {
  if (!isDragging.value) return;
  emit("dragging", getEvent(event));
}

function end(event: Event) {
  if (!isDragging.value) return;
  changeState(false, getEvent(event));
}

function getEvent(event: Event): Event {
  if (event instanceof TouchEvent) return event.touches[0] as unknown as Event;
  return event;
}
</script>

<template>
  <div class="action-card">
    <Icon
      v-if="!hideDrag"
      class="side-icon cursor-grab"
      :class="{ 'cursor-grabbing': isDragging }"
      name="drag_indicator"
      @mousedown="start"
      @touchstart="start"
    />
    <Card class="rounded-base [&>*]:px-xl">
      <header
        class="flex items-center gap-xs bg-primary-interaction-default text-neutral-foreground-negative rounded-base py-sm"
        :class="{ 'rounded-b-none': $slots.card }"
        :style="{ background: color }"
      >
        <Icon :name="icon" v-if="icon" class="leading-xxs" />
        <slot />
      </header>
      <div class="py-sm" v-if="$slots.card">
        <slot name="card" />
      </div>
    </Card>
    <Icon class="side-icon cursor-pointer" name="delete" @click="emit('delete')" />
  </div>
</template>

<style scoped>
@reference "../../assets/main.css";

.action-card {
  @apply flex items-center gap-xxs transition-transform duration-150 ease-in-out;
}

.action-card:hover {
  @apply transition-transform duration-150 ease-in-out scale-105;

  .side-icon {
    @apply text-neutral-interaction-default;
  }
}

.side-icon {
  @apply flex items-center text-neutral-interaction-disabled leading-xxs;
}
</style>

// src/components/ActionCard/ActionCard.tsx
import { useState, useEffect, useRef, useCallback, Children, isValidElement } from 'react';
import clsx from 'clsx';
import { Card } from '../Card/Card';
import { Icon } from '../Icon/Icon';
import styles from './ActionCard.module.css';

export interface ActionCardProps {
  icon?: string;
  color?: string;
  hideDrag?: boolean;
  children?: React.ReactNode;
  className?: string;
  onDragstart?: (event: MouseEvent | Touch) => void;
  onDragging?: (event: MouseEvent | Touch) => void;
  onDragend?: (event: MouseEvent | Touch) => void;
  onDelete?: () => void;
}

function getEvent(event: MouseEvent | TouchEvent): MouseEvent | Touch {
  if (event instanceof TouchEvent) return event.touches[0];
  return event;
}

function ActionCardCard({ children }: { children?: React.ReactNode }) {
  return <div className="py-sm">{children}</div>;
}

export function ActionCard({
  icon = '',
  color = '',
  hideDrag = false,
  children,
  className,
  onDragstart,
  onDragging,
  onDragend,
  onDelete,
}: ActionCardProps) {
  const [isDragging, setIsDragging] = useState(false);
  const isDraggingRef = useRef(false);

  isDraggingRef.current = isDragging;

  const move = useCallback(
    (event: MouseEvent | TouchEvent) => {
      if (!isDraggingRef.current) return;
      onDragging?.(getEvent(event));
    },
    [onDragging]
  );

  const end = useCallback(
    (event: MouseEvent | TouchEvent) => {
      if (!isDraggingRef.current) return;
      setIsDragging(false);
      isDraggingRef.current = false;
      onDragend?.(getEvent(event));
    },
    [onDragend]
  );

  useEffect(() => {
    window.addEventListener('mousemove', move as EventListener);
    window.addEventListener('mouseup', end as EventListener);
    window.addEventListener('touchmove', move as EventListener);
    window.addEventListener('touchend', end as EventListener);

    return () => {
      window.removeEventListener('mousemove', move as EventListener);
      window.removeEventListener('mouseup', end as EventListener);
      window.removeEventListener('touchmove', move as EventListener);
      window.removeEventListener('touchend', end as EventListener);
    };
  }, [move, end]);

  function start(event: React.MouseEvent | React.TouchEvent) {
    const rawEvent = event.nativeEvent;
    setIsDragging(true);
    isDraggingRef.current = true;
    onDragstart?.(getEvent(rawEvent as MouseEvent | TouchEvent));
  }

  const cardChildren: React.ReactNode[] = [];
  const headerChildren: React.ReactNode[] = [];

  Children.forEach(children, (child) => {
    if (isValidElement(child) && child.type === ActionCardCard) {
      cardChildren.push(child);
    } else {
      headerChildren.push(child);
    }
  });

  const hasCardSlot = cardChildren.length > 0;

  return (
    <div className={clsx(styles.actionCard, 'action-card', className)}>
      {!hideDrag && (
        <span
          className={clsx(styles.sideIcon, isDragging ? 'cursor-grabbing' : 'cursor-grab')}
          onMouseDown={start as React.MouseEventHandler}
          onTouchStart={start as React.TouchEventHandler}
        >
          <Icon name="drag_indicator" />
        </span>
      )}
      <Card className="rounded-base [&>*]:px-xl">
        <header
          className={clsx(
            'flex items-center gap-xs bg-primary-interaction-default text-neutral-foreground-negative rounded-base py-sm',
            hasCardSlot && 'rounded-b-none'
          )}
          style={{ background: color || undefined }}
        >
          {icon && <Icon name={icon} className="leading-xxs" />}
          {headerChildren}
        </header>
        {hasCardSlot && cardChildren}
      </Card>
      <span className={clsx(styles.sideIcon, 'cursor-pointer')} onClick={onDelete}>
        <Icon name="delete" />
      </span>
    </div>
  );
}

ActionCard.Card = ActionCardCard;
