// src/components/Carousel/Carousel.vue
<script setup lang="ts">
import { computed, ref, watch, onMounted, nextTick } from "vue";

const props = withDefaults(
  defineProps<{
    modelValue?: number;
    options: any[];
    visible?: number;
    interval?: number;
    disabled?: boolean;
    circular?: boolean;
    vertical?: boolean;
  }>(),
  {
    modelValue: 0,
    visible: 1,
    disabled: false,
    circular: false,
    vertical: false,
  }
);

const emit = defineEmits<{
  "update:modelValue": [value: number];
}>();

const model = ref(props.modelValue);
const carouselOptionsContainer = ref<HTMLElement>();
const contentStyle = ref<{ width?: string; height?: string }>({});
const transform = ref("-0px");
const carouselInterval = ref<ReturnType<typeof setInterval>>();
const optionSections = computed(() => {
  const sections = [];
  for (let i = 0; i < props.options.length; i += props.visible) {
    sections.push(props.options.slice(i, i + props.visible));
  }
  return sections;
});

const maxIndex = computed(
  () => Math.ceil(props.options.length / props.visible) - 1
);

const gap = computed(() => {
  return parseFloat(
    (carouselOptionsContainer.value as any)
      ?.computedStyleMap()
      .get("--spacing-xs")
      .toString()
      .replace("px", "")
  );
});

watch(
  () => props.modelValue,
  () => {
    checkModel(props.modelValue);
    nextTick(() => {
      calculateContentStyle();
    });
  }
);

watch(
  () => props.visible,
  () => {
    setModel(0);
    nextTick(() => {
      calculateContentStyle();
    });
  }
);

watch(
  () => props.options.length,
  () => {
    checkModel(model.value);
    calculateContentStyle();
  }
);

watch(
  () => props.interval,
  () => {
    setCarouselInterval();
  }
);

onMounted(() => {
  checkModel(props.modelValue);
  nextTick(() => {
    calculateContentStyle();
  });
  setCarouselInterval();
});

function checkModel(value: number) {
  model.value = Math.max(0, Math.min(value, maxIndex.value));
}

function setModel(value: number) {
  if (value > maxIndex.value) {
    if (!props.circular) return;
    value = 0;
  }
  else if (value < 0) {
    if (!props.circular) return;
    value = maxIndex.value;
  }
  model.value = value;
  nextTick(() => {
    calculateContentStyle();
  });

  emit("update:modelValue", value);
}

function setCarouselInterval() {
  if (!props.interval) {
    clearInterval(carouselInterval.value);
    carouselInterval.value = undefined;
    return;
  }

  carouselInterval.value = setInterval(() => {
    nextTick(() => {
      setModel(model.value + 1);
    });
  }, props.interval);
}

function onKeyUp(e: KeyboardEvent) {
  switch (e.key) {
    case "ArrowUp": {
      if (!props.vertical) break;
      if (model.value == 0 && !props.circular) break;
      setModel(model.value - 1);
      break;
    }
    case "ArrowDown": {
      if (!props.vertical) break;
      if (model.value == maxIndex.value && !props.circular) break;
      setModel(model.value + 1);
      break;
    }
    case "ArrowLeft": {
      if (props.vertical) break;
      if (model.value == 0 && !props.circular) break;
      setModel(model.value - 1);
      break;
    }
    case "ArrowRight": {
      if (props.vertical) break;
      if (model.value == maxIndex.value && !props.circular) break;
      setModel(model.value + 1);
      break;
    }
    case "Home": {
      if (model.value == 0 && !props.circular) break;
      setModel(0);
      break;
    }
    case "End": {
      if (model.value == maxIndex.value && !props.circular) break;
      setModel(maxIndex.value);
      break;
    }
  }
}

function calculateContentStyle() {
  if (!carouselOptionsContainer.value) {
    contentStyle.value = {};
    return;
  }

  const children = carouselOptionsContainer.value.children;
  if (children.length === 0) {
    contentStyle.value = {};
    return;
  }

  let totalSize = 0;
  let totalTransform = 0;

  const child = children[model.value] as HTMLElement;
  if (props.vertical) {
    totalSize = Math.max(totalSize, child.offsetHeight);
  } else {
    totalSize += child.offsetWidth;
    if (0 > model.value) totalSize += gap.value;
  }

  for (let i = 0; i < model.value; i++) {
    const child = children[i] as HTMLElement;
    const rect = child.getBoundingClientRect();
    if (props.vertical) totalTransform += rect.height;
    else totalTransform += rect.width;

    if (model.value > 0) totalTransform += gap.value;
  }

  transform.value = `-${Math.floor(totalTransform)}px`;

  contentStyle.value = {
    width: props.vertical ? "" : `${totalSize}px`,
    height: props.vertical ? `${totalSize}px` : "",
  };
}
</script>

<template>
  <div class="carousel" :tabindex="disabled ? -1 : 0" @keyup="onKeyUp">
    <div class="carousel-content" :class="{ vertical }">
      <div
        class="arrow-icon"
        :class="{ disabled: (model == 0 && !props.circular) || disabled }"
        :tabindex="(model == 0 && !props.circular) || disabled ? -1 : 0"
        @click="setModel(model - 1)"
        @keyup.enter="setModel(model - 1)"
      >
        <Icon
          :name="vertical ? 'keyboard_arrow_up' : 'chevron_left'"
          class="leading-xxs"
        />
      </div>
      <div class="overflow-hidden shrink-0" :style="contentStyle">
        <div
          class="carousel-options"
          ref="carouselOptionsContainer"
          :style="{
            transform: `translate${vertical ? 'Y' : 'X'}(${transform})`,
          }"
        >
          <div
            v-for="(section, sectionIndex) in optionSections"
            :key="sectionIndex"
            class="flex gap-xs"
          >
            <div
              v-for="(option, index) in section"
              :key="index"
              :inert="sectionIndex !== model || disabled"
            >
              <slot
                name="option"
                :option="option"
                :index="index"
              />
            </div>
          </div>
        </div>
      </div>
      <div
        class="arrow-icon"
        :class="{
          disabled: (model >= maxIndex && !props.circular) || disabled,
        }"
        :tabindex="(model >= maxIndex && !props.circular) || disabled ? -1 : 0"
        @click="setModel(model + 1)"
        @keyup.enter="setModel(model + 1)"
      >
        <Icon
          :name="vertical ? 'keyboard_arrow_down' : 'chevron_right'"
          class="leading-xxs"
        />
      </div>
    </div>
    <div class="carousel-indicators">
      <div
        v-for="i in maxIndex + 1"
        :key="i"
        class="carousel-indicator"
        :class="{ active: model == i - 1, disabled }"
        :tabindex="disabled ? -1 : 0"
        @click="setModel(i - 1)"
        @keyup.enter="setModel(i - 1)"
      />
    </div>
  </div>
</template>

<style scoped>
@reference "../../assets/main.css";

.carousel {
  @apply flex flex-col gap-sm w-fit;
}

.arrow-icon {
  @apply h-fit w-fit flex items-center cursor-pointer text-neutral-interaction-default text-2xl hover:text-primary-interaction-hover;
}

.arrow-icon.disabled {
  @apply pointer-events-none text-neutral-interaction-disabled;
}

.carousel-content {
  @apply flex items-center justify-center gap-xs;
}

.carousel-content.vertical {
  @apply flex-col gap-sm;
}

.carousel-options {
  @apply flex items-center justify-center gap-xs transition-transform duration-300 ease-in-out w-max;
}

.vertical .carousel-options {
  @apply flex-col;
}

.carousel-indicators {
  @apply flex items-center justify-center gap-xs w-full;
}

.carousel-indicator {
  @apply w-2xl h-xs rounded-full bg-neutral-surface-disabled cursor-pointer;
}

.carousel-indicator.disabled {
  @apply bg-neutral-interaction-disabled pointer-events-none;
}

.carousel-indicator.active {
  @apply bg-primary-interaction-default;
}
</style>

// src/components/Carousel/Carousel.tsx
import React, { useLayoutEffect, useEffect, useRef, useState } from 'react';
import clsx from 'clsx';
import { useControllable } from '../../hooks/useControllable';
import { Icon } from '../Icon/Icon';
import styles from './Carousel.module.css';

export interface CarouselProps {
  value?: number;
  onChange?: (value: number) => void;
  options: any[];
  visible?: number;
  vertical?: boolean;
  autoplay?: boolean;
  autoplayInterval?: number;
  showArrows?: boolean;
  disabled?: boolean;
  circular?: boolean;
  children?: (option: any, index: number) => React.ReactNode;
  className?: string;
}

export function Carousel({
  value,
  onChange,
  options,
  visible = 1,
  vertical = false,
  autoplay = false,
  autoplayInterval = 3000,
  showArrows = true,
  disabled = false,
  circular = false,
  children,
  className,
}: CarouselProps) {
  const [model, setModel] = useControllable<number>({
    value,
    defaultValue: 0,
    onChange,
  });

  const trackRef = useRef<HTMLDivElement>(null);
  const [transform, setTransform] = useState('-0px');
  const [contentStyle, setContentStyle] = useState<React.CSSProperties>({});

  const totalPages = Math.ceil(options.length / visible);
  const currentIndex = model ?? 0;

  const sections: any[][] = [];
  for (let i = 0; i < options.length; i += visible) {
    sections.push(options.slice(i, i + visible));
  }

  const maxIndex = totalPages - 1;

  function setModelSafe(value: number) {
    if (disabled) return;
    if (value > maxIndex) {
      if (!circular) return;
      value = 0;
    } else if (value < 0) {
      if (!circular) return;
      value = maxIndex;
    }
    setModel(value);
  }

  function calculateContentStyle() {
    if (!trackRef.current) {
      setContentStyle({});
      setTransform('-0px');
      return;
    }

    const children = trackRef.current.children;
    if (children.length === 0) {
      setContentStyle({});
      setTransform('-0px');
      return;
    }

    const gapStr = getComputedStyle(document.documentElement).getPropertyValue('--spacing-xs');
    const gap = parseFloat(gapStr) || 0;

    let totalSize = 0;
    let totalTransformPx = 0;

    const child = children[currentIndex] as HTMLElement;
    if (child) {
      if (vertical) {
        totalSize = Math.max(totalSize, child.offsetHeight);
      } else {
        totalSize += child.offsetWidth;
      }
    }

    for (let i = 0; i < currentIndex; i++) {
      const c = children[i] as HTMLElement;
      const rect = c.getBoundingClientRect();
      if (vertical) totalTransformPx += rect.height;
      else totalTransformPx += rect.width;

      if (currentIndex > 0) totalTransformPx += gap;
    }

    setTransform(`-${Math.floor(totalTransformPx)}px`);
    setContentStyle({
      width: vertical ? '' : `${totalSize}px`,
      height: vertical ? `${totalSize}px` : '',
    });
  }

  useLayoutEffect(() => {
    calculateContentStyle();
  }, [model, options.length, visible]);

  const currentIndexRef = useRef(currentIndex);
  currentIndexRef.current = currentIndex;
  const maxIndexRef = useRef(maxIndex);
  maxIndexRef.current = maxIndex;
  const circularRef = useRef(circular);
  circularRef.current = circular;

  useEffect(() => {
    if (!autoplay || disabled) return;
    const interval = setInterval(() => {
      const prev = currentIndexRef.current;
      const max = maxIndexRef.current;
      const circ = circularRef.current;
      const next = prev + 1;
      if (next > max) {
        setModel(circ ? 0 : prev);
      } else {
        setModel(next);
      }
    }, autoplayInterval);
    return () => clearInterval(interval);
  }, [autoplay, autoplayInterval, options.length, visible, disabled, circular]);

  function goToPrev() {
    setModelSafe(currentIndex - 1);
  }

  function goToNext() {
    setModelSafe(currentIndex + 1);
  }

  const prevDisabled = disabled || (currentIndex === 0 && !circular);
  const nextDisabled = disabled || (currentIndex >= maxIndex && !circular);

  return (
    <div className={clsx(styles.carousel, 'carousel', className)}>
      <div className={clsx(styles.content, vertical && styles.vertical)}>
        {showArrows && (
          <button
            className={clsx(styles.navButton, styles.prevButton, vertical && styles.vertical)}
            onClick={goToPrev}
            aria-label="Previous slide"
            disabled={prevDisabled}
          >
            <Icon name={vertical ? 'expand_less' : 'chevron_left'} className="leading-xxs" />
          </button>
        )}

        <div className={styles.overflow} style={{ width: '100%', overflow: 'hidden', ...contentStyle }}>
          <div
            ref={trackRef}
            className={clsx(styles.track, vertical && styles.vertical)}
            style={{ transform: `translate${vertical ? 'Y' : 'X'}(${transform})` }}
          >
            {sections.map((section, sectionIndex) => (
              <div
                key={sectionIndex}
                className={styles.section}
                {...(sectionIndex !== currentIndex ? { inert: true } : {})}
              >
                {section.map((option, itemIndex) => (
                  <div key={itemIndex} className={styles.slide}>
                    {children?.(option, sectionIndex * visible + itemIndex)}
                  </div>
                ))}
              </div>
            ))}
          </div>
        </div>

        {showArrows && (
          <button
            className={clsx(styles.navButton, styles.nextButton, vertical && styles.vertical)}
            onClick={goToNext}
            aria-label="Next slide"
            disabled={nextDisabled}
          >
            <Icon name={vertical ? 'expand_more' : 'chevron_right'} className="leading-xxs" />
          </button>
        )}
      </div>

      <div className={styles.indicators}>
        {Array.from({ length: totalPages }).map((_, i) => (
          <button
            key={i}
            className={clsx(
              styles.indicator,
              i === currentIndex && styles.indicatorActive,
              disabled && styles.indicatorDisabled
            )}
            disabled={disabled}
            onClick={() => !disabled && setModel(i)}
            aria-label={`Go to slide ${i + 1}`}
          />
        ))}
      </div>
    </div>
  );
}
