// src/components/Dialog/Dialog.tsx
import { useRef } from 'react';
import clsx from 'clsx';
import { Overlay } from '../../utils/components/Overlay';
import { useControllable } from '../../hooks/useControllable';
import { useTransition } from '../../hooks/useTransition';
import { useModalFocus } from '../../hooks/useModalFocus';
import { trapFocus } from '../../utils';
import './Dialog.css';

export interface DialogProps {
  value?: boolean;
  onChange?: (value: boolean) => void;
  width?: string;
  height?: string;
  noOutsideClose?: boolean;
  children?: React.ReactNode;
  className?: string;
  zIndex?: number;
  'aria-label'?: string;
  'aria-labelledby'?: string;
}

export function Dialog({
  value,
  onChange,
  width = 'fit-content',
  height = 'fit-content',
  noOutsideClose = false,
  children,
  className,
  zIndex = 1002,
  'aria-label': ariaLabel,
  'aria-labelledby': ariaLabelledby,
}: DialogProps) {
  const [isOpen, setOpen] = useControllable<boolean>({ value, defaultValue: false, onChange });
  const { isMounted, isActive } = useTransition(isOpen ?? false, { duration: 500 });
  const dialogRef = useRef<HTMLDivElement>(null);

  useModalFocus(dialogRef, isOpen ?? false);

  function handleOverlayClick() {
    if (noOutsideClose) {
      dialogRef.current?.classList.add('no-outside-close-warning');
      setTimeout(() => {
        dialogRef.current?.classList.remove('no-outside-close-warning');
      }, 100);
    } else {
      setOpen(false);
    }
  }

  function handleEscape(e: React.KeyboardEvent<HTMLDivElement>) {
    if (noOutsideClose) return;
    if (e.key !== 'Escape') return;

    e.stopPropagation();
    setOpen(false);
  }

  return (
    <Overlay value={isOpen} zIndex={zIndex} onClick={handleOverlayClick}>
      {isMounted && (
        <div
          ref={dialogRef}
          className={clsx('dialog', isActive && 'active', className)}
          style={{ width, height, zIndex: zIndex }}
          tabIndex={-1}
          role="dialog"
          aria-modal="true"
          aria-label={ariaLabel}
          aria-labelledby={ariaLabelledby}
          onKeyDown={(e) => {
            handleEscape(e);
            trapFocus(e, dialogRef.current);
          }}
        >
          {children}
        </div>
      )}
    </Overlay>
  );
}

// src/components/Dialog/Dialog.vue
<script setup lang="ts">
import { ref, watch } from "vue";
import { useModalFocus } from "#composables";
import { trapFocus } from "../../utils";
import Overlay from "../../utils/components/Overlay.vue";

defineOptions({ inheritAttrs: false });

const props = withDefaults(
  defineProps<{
    modelValue?: boolean;
    width?: string;
    height?: string;
    noOutsideClose?: boolean;
    class?: string,
    zIndex?: number;
  }>(),
  {
    modelValue: false,
    width: "fit-content",
    height: "fit-content",
    noOutsideClose: false,
    class: '',
    zIndex: 1002,
  }
);

const emit = defineEmits<{
  "update:modelValue": [value: any];
}>();

const model = ref(props.modelValue);
const dialog = ref<HTMLElement>();

watch(
  () => props.modelValue,
  (cur) => {
    model.value = cur;
  }
);

useModalFocus(dialog, model);

function closeDialog() {
  if (props.noOutsideClose) {
    dialog.value?.classList.add("no-outside-close-warning");
    setTimeout(() => {
      dialog.value?.classList.remove("no-outside-close-warning");
    }, 100);
  } else {
    model.value = false;
    emit("update:modelValue", false);
  }
}

function onEscape(e: KeyboardEvent) {
  if (props.noOutsideClose) return;

  e.stopPropagation();
  closeDialog();
}
</script>

<template>
  <Teleport to="body">
    <Overlay v-model="model" :z-index="zIndex" @click="closeDialog">
      <Transition name="bounce">
        <div
          v-if="model"
          v-bind="$attrs"
          ref="dialog"
          class="dialog"
          :class="class"
          role="dialog"
          aria-modal="true"
          tabindex="-1"
          :style="{ width: width, height: height, zIndex: zIndex }"
          @keydown.esc="onEscape"
          @keydown="trapFocus($event, dialog)"
        >
          <slot />
        </div>
      </Transition>
    </Overlay>
  </Teleport>
</template>

<style scoped>
@reference "../../assets/main.css";

.dialog {
  @apply fixed top-[50%] left-[50%] bg-neutral-surface-default rounded-base border-xxs border-neutral-default outline-none;
  transform: translate(-50%, -50%) scale(1);
  max-width: calc(100% - var(--spacing-xl));
  max-height: calc(100% - var(--spacing-xl));
}

.bounce-enter-active {
  animation: bounce-in 0.5s;
}

.bounce-leave-active {
  animation: bounce-in 0.5s reverse;
}

.dialog.no-outside-close-warning {
  animation: bounce-warning 0.5s ease;
}

@keyframes bounce-in {
  0% {
    transform: translate(-50%, -50%) scale(0);
    opacity: 0;
  }
  100% {
    transform: translate(-50%, -50%) scale(1);
    opacity: 1;
  }
}

@keyframes bounce-warning {
  0% {
    transform: translate(-50%, -50%) scale(1.1);
  }
  100% {
    transform: translate(-50%, -50%) scale(1);
  }
}
</style>
