// src/components/Tab/Tab.tsx
import clsx from "clsx";
import { useControllable } from "../../hooks/useControllable";
import { Icon } from "../Icon/Icon";
import styles from "./Tab.module.css";
import { isObject } from "#utils/index";

export interface TabProps {
  value?: any;
  onChange?: (value: any) => void;
  options?: Array<
    string | any
  >;
  labelKey?: string;
  valueKey?: string;
  isIcon?: boolean;
  notCard?: boolean;
  getObject?: boolean;
  children?: React.ReactNode;
  className?: string;
}

export function Tab({
  value,
  onChange,
  options = [],
  labelKey = "label",
  valueKey = "label",
  isIcon = false,
  notCard = false,
  getObject = false,
  children,
  className,
}: TabProps) {
  const [model, setModel] = useControllable<any>({
    value,
    defaultValue: options.length ? options[0] : undefined,
    onChange,
  });

  function getValue(option: any) {
    return isObject(option) ? option[valueKey] : option;
  }

  function getLabel(option: any) {
    return isObject(option) ? option[labelKey] : option;
  }

  function handleClick(option: any) {
    setModel(getObject ? option : getValue(option))
  }

  return (
    <div
      className={clsx(
        styles.container,
        "tab",
        notCard && styles.notCard,
        className,
      )}
    >
      <div className="flex font-bold text-sm gap-xs w-fit">
        {options.map((option, index) => (
          <button
            key={index}
            className={clsx(
              styles.tabButton,
              getValue(model) === getValue(option) && styles.active,
            )}
            onClick={() => handleClick(option)}
          >
            {typeof option === "object" && option.icon ? (
              <>
                <Icon name={option.icon} className={styles.icon} />
                <span>{getLabel(option)}</span>
              </>
            ) : isIcon && typeof option === "string" ? (
              <Icon name={option} className={styles.icon} />
            ) : (
              <span>{getLabel(option)}</span>
            )}
          </button>
        ))}
      </div>
      {children}
    </div>
  );
}

// src/components/Tab/Tab.vue
<script setup lang="ts">
import { ref, watch, onBeforeMount } from "vue";
import { isObject } from "../../utils";

const props = withDefaults(
  defineProps<{
    modelValue?: any;
    options: any[];
    labelKey?: string;
    valueKey?: string;
    isIcon?: boolean;
    notCard?: boolean;
  }>(),
  {
    modelValue: undefined,
    labelKey: 'label',
    valueKey: 'value',
    isIcon: false,
    notCard: false,
  }
);

const model = ref(props.modelValue);

onBeforeMount(() => {
  if (!model.value) changeTab(props.options[0]);
});

watch(
  () => props.modelValue,
  (cur) => (model.value = cur)
);

const emit =
  defineEmits<{
    "update:modelValue": [value: any];
  }>();

function changeTab(option: any) {
  model.value = option;
  emit("update:modelValue", option);
}

function getValue(option: any): string {
  return isObject(option) ? option[props.valueKey] : option;
}

function getLabel(option: any): string {
  return isObject(option) ? option[props.labelKey] : option;
}
</script>

<template>
  <div
    class="tab"
    :class="{
      'bg-neutral-surface-highlight': !notCard,
    }"
  >
    <div class="flex font-bold text-sm gap-xs w-fit">
      <button
        v-for="(option, index) in options"
        :key="index"
        class="default-tab"
        :class="{ 'active-tab': getValue(model) == getValue(option) }"
        @click="changeTab(option)"
      >
        <div v-if="isObject(option)" class="flex items-center gap-xxs">
          <Icon :name="option.icon" v-if="option.icon" />
          <h5 v-if="getLabel(option)">{{ getLabel(option) }}</h5>
        </div>
        <div v-else>
          <Icon :name="option" v-if="isIcon" />
          <h5 v-else>{{ option }}</h5>
        </div>
      </button>
    </div>
  </div>
</template>

<style scoped>
@reference "../../assets/main.css";

.tab {
  @apply p-xxs rounded-sm;
}

.default-tab {
  @apply text-neutral-interaction-default py-xs px-xs rounded-xs cursor-pointer hover:text-primary-interaction-hover;

  .icon {
    @apply text-lg;
  }
}

.active-tab {
  @apply shadow-neutral-selected text-neutral-foreground-high bg-neutral-surface-default hover:text-neutral-foreground-high;
}
</style>
