// src/components/Chip/Chip.vue
<script setup lang="ts">
import StatusBadge from "../StatusBadge/StatusBadge.vue";

withDefaults(
  defineProps<{
    labelValue?: string;
    color?: "primary" | "info" | "success" | "warning" | "danger" | "neutral";
    size?: "small" | "medium" | "large";
    loading?: boolean;
    closeable?: boolean;
    icon?: string;
    isAppendedIcon?: boolean;
  }>(),
  {
    labelValue: "",
    color: "primary",
    size: "small",
    loading: false,
    closeable: false,
    icon: "",
    isAppendedIcon: false,
  }
);

const emit = defineEmits<{
  close: [];
}>();
</script>

<template>
  <StatusBadge
    class="chip"
    :label-value="labelValue"
    :color="color"
    :size="size"
    :loading="loading"
    :closeable="closeable"
    :icon="icon"
    :is-appended-icon="isAppendedIcon"
    @close="emit('close')"
  >
    <template #default v-if="labelValue || $slots.default">
      <slot>{{ labelValue }}</slot>
    </template>
  </StatusBadge>
</template>

<style scoped>
@reference "../../assets/main.css";

.chip.status-badge {
  @apply py-2xxs px-xs border-none rounded-sm whitespace-nowrap;
}
</style>

// src/components/Chip/Chip.tsx
import clsx from 'clsx';
import { StatusBadge } from '../StatusBadge/StatusBadge';
import styles from './Chip.module.css';

export interface ChipProps {
  labelValue?: string;
  color?: 'primary' | 'info' | 'success' | 'warning' | 'danger' | 'neutral';
  size?: 'small' | 'medium' | 'large';
  loading?: boolean;
  closeable?: boolean;
  icon?: string;
  isAppendedIcon?: boolean;
  children?: React.ReactNode;
  className?: string;
  onClose?: () => void;
}

export function Chip({
  labelValue = '',
  color = 'primary',
  size = 'small',
  loading = false,
  closeable = false,
  icon = '',
  isAppendedIcon = false,
  children,
  className,
  onClose,
}: ChipProps) {
  return (
    <StatusBadge
      className={clsx(styles.chip, 'chip', className)}
      labelValue={labelValue}
      color={color}
      size={size}
      loading={loading}
      closeable={closeable}
      icon={icon}
      isAppendedIcon={isAppendedIcon}
      onClose={onClose}
    >
      {children || labelValue}
    </StatusBadge>
  );
}
