// src/components/Table/Table.tsx
import React, { useState } from 'react';
import clsx from 'clsx';
import { useControllable } from '../../hooks/useControllable';
import { Pagination } from '../Pagination/Pagination';
import { Skeleton } from '../Skeleton/Skeleton';
import { Checkbox } from '../Checkbox/Checkbox';
import { Icon } from '../Icon/Icon';
import { Select } from '../Select/Select';
import styles from './Table.module.css';

export interface Column {
  label?: string;
  value: string;
  sortable?: boolean;
  width?: string;
  align?: 'flex-start' | 'center' | 'flex-end';
  render?: (value: any, item: any, index: number) => React.ReactNode;
}

export interface TableProps {
  columns: Column[];
  items: any[];
  sortOptions?: { by?: string; desc?: boolean };
  page?: number;
  defaultPage?: number;
  itemsPerPage?: number;
  defaultItemsPerPage?: number;
  numberOfItems?: number;
  renderPaginationInBackEnd?: boolean;
  hideFooter?: boolean;
  isHeaderFixed?: boolean;
  enableSelection?: boolean;
  enableAggregation?: boolean;
  loading?: boolean;
  noShadow?: boolean;
  hasHover?: boolean;
  onPageChange?: (page: number) => void;
  onItemsPerPageChange?: (n: number) => void;
  onSortBy?: (key: string, desc: boolean) => void;
  onPageItems?: (page: number, itemsPerPage: number) => void;
  onSelectAll?: (value: boolean) => void;
  onSelectRow?: (item: any, selected: boolean) => void;
  /** Slot: per-row aggregation cell (Vue: slot name="aggregation") */
  renderAggregation?: (item: any, index: number) => React.ReactNode;
  /** Slot: per-row selection cell (Vue: slot name="select") */
  renderSelect?: (item: any, index: number) => React.ReactNode;
  /** Slot: per-row actions cell (Vue: slot name="actions") */
  renderActions?: (item: any, index: number) => React.ReactNode;
  /** Slot: expandable child rows (Vue: slot name="childs") */
  renderChilds?: (item: any, index: number) => React.ReactNode;
  /** Slot: empty state (Vue: slot name="empty-state") */
  renderEmptyState?: () => React.ReactNode;
  /** Slot: custom footer content in tfoot (Vue: slot name="footer") */
  renderFooter?: () => React.ReactNode;
  /** Slot: items per page label (Vue: slot name="items-per-page") */
  renderItemsPerPage?: () => React.ReactNode;
  /** Slot: showing page text (Vue: slot name="showing-page") */
  renderShowingPage?: (min: number, max: number, total: number) => React.ReactNode;
  children?: React.ReactNode;
  className?: string;
}

function sortItems(items: any[], sortKey: string, desc: boolean): any[] {
  return [...items].sort((a, b) => {
    const aVal = a[sortKey];
    const bVal = b[sortKey];

    if (typeof aVal === 'string' && typeof bVal === 'string') {
      const lowerA = aVal.toLowerCase();
      const lowerB = bVal.toLowerCase();
      return desc ? lowerA.localeCompare(lowerB) : lowerB.localeCompare(lowerA);
    } else if (typeof aVal === 'number' && typeof bVal === 'number') {
      return desc ? aVal - bVal : bVal - aVal;
    } else if (aVal instanceof Date && bVal instanceof Date) {
      return desc ? aVal.getTime() - bVal.getTime() : bVal.getTime() - aVal.getTime();
    } else {
      const strA = String(aVal).toLowerCase();
      const strB = String(bVal).toLowerCase();
      return desc ? strA.localeCompare(strB) : strB.localeCompare(strA);
    }
  });
}

function findSlot(
  children: React.ReactNode,
  SlotType: React.ElementType
): React.ReactNode | null {
  const arr = React.Children.toArray(children);
  const match = arr.find(
    (child) => React.isValidElement(child) && child.type === SlotType
  );
  return match || null;
}

function TableActions({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}

function TableFooter({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}

function TableEmptyState({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}

export function Table({
  columns,
  items,
  sortOptions,
  page: pageProp,
  defaultPage,
  itemsPerPage: itemsPerPageProp,
  defaultItemsPerPage,
  numberOfItems,
  renderPaginationInBackEnd = false,
  hideFooter = false,
  isHeaderFixed = false,
  enableSelection = false,
  enableAggregation = false,
  loading = false,
  noShadow = false,
  hasHover = false,
  onPageChange,
  onItemsPerPageChange,
  onSortBy,
  onPageItems,
  onSelectAll,
  onSelectRow,
  renderAggregation,
  renderSelect,
  renderActions,
  renderChilds,
  renderEmptyState,
  renderFooter,
  renderItemsPerPage,
  renderShowingPage,
  children,
  className,
}: TableProps) {
  const [page, setPage] = useControllable<number>({
    value: pageProp,
    defaultValue: defaultPage ?? 1,
    onChange: onPageChange,
  });

  const [itemsPerPage, setItemsPerPage] = useControllable<number>({
    value: itemsPerPageProp,
    defaultValue: defaultItemsPerPage ?? 10,
    onChange: onItemsPerPageChange,
  });

  const [sortByName, setSortByName] = useState<string | null>(
    sortOptions?.by || null
  );
  const [isDesc, setIsDesc] = useState<Record<string, boolean>>(() => {
    const map: Record<string, boolean> = {};
    columns.forEach((col) => {
      map[col.value] =
        col.value === sortOptions?.by ? !!(sortOptions?.desc) : false;
    });
    return map;
  });
  const [selectedRows, setSelectedRows] = useState<Set<number>>(new Set());
  const [allSelected, setAllSelected] = useState(false);

  const currentPage = page ?? 1;
  const currentItemsPerPage = itemsPerPage ?? 10;

  const sortedItems =
    sortByName
      ? sortItems(items, sortByName, isDesc[sortByName] ?? false)
      : items;

  const totalItems = renderPaginationInBackEnd
    ? (numberOfItems ?? 0)
    : (sortedItems?.length ?? 0);
  const pageCount = Math.ceil(totalItems / currentItemsPerPage);

  const pagedItems = renderPaginationInBackEnd
    ? sortedItems
    : sortedItems.slice(
        (currentPage - 1) * currentItemsPerPage,
        currentPage * currentItemsPerPage
      );

  const min =
    currentPage === 1
      ? 1
      : (currentPage - 1) * currentItemsPerPage + 1;
  const max = (currentPage - 1) * currentItemsPerPage + pagedItems.length;

  let colspan = columns.length;
  if (enableSelection) colspan++;
  if (enableAggregation) colspan++;

  // Legacy compound component slots (fallback)
  const actionsSlot = findSlot(children, TableActions);
  const footerSlot = findSlot(children, TableFooter);
  const emptySlot = findSlot(children, TableEmptyState);

  const hasActions = !!renderActions || !!actionsSlot;
  if (hasActions) colspan++;

  const listPerPage = [5, 10, 20, 50, 100];

  const handleSort = (column: Column) => {
    if (!column.sortable) return;
    const key = column.value;
    const newDesc = sortByName === key ? !isDesc[key] : false;
    setSortByName(key);
    setIsDesc((prev) => ({ ...prev, [key]: newDesc }));
    onSortBy?.(key, newDesc);
  };

  const handleSelectRow = (index: number, item: any) => {
    setSelectedRows((prev) => {
      const next = new Set(prev);
      const wasSelected = next.has(index);
      wasSelected ? next.delete(index) : next.add(index);
      onSelectRow?.(item, !wasSelected);
      return next;
    });
  };

  const handleSelectAll = (value: boolean | null) => {
    const selectAll = !!value;
    setAllSelected(selectAll);
    if (selectAll) {
      setSelectedRows(new Set(pagedItems.map((_, i) => i)));
    } else {
      setSelectedRows(new Set());
    }
    // Mutate item.selected like Vue does
    items?.forEach((item: any) => { item.selected = selectAll; });
    onSelectAll?.(selectAll);
  };

  const handleChangePage = (newPage: number) => {
    setPage(newPage);
    onPageItems?.(newPage, currentItemsPerPage);
  };

  const handleChangeItemsPerPage = (newItemsPerPage: number) => {
    setItemsPerPage(newItemsPerPage || 10);
    setPage(1);
    onPageItems?.(1, newItemsPerPage);
  };

  return (
    <div className={clsx(styles.table, 'table', className)}>
      <div
        className={clsx(
          styles.tableContent,
          noShadow && styles.noShadow,
          isHeaderFixed && styles.headerFixed
        )}
      >
        <table className={styles.tableStyle}>
          {!loading ? (
            <thead>
              <tr>
                {enableAggregation && (
                  <th
                    className={clsx(styles.firstTh, styles.pointerNone)}
                    style={{ width: '2%' }}
                  />
                )}
                {enableSelection && (
                  <th
                    className={clsx(
                      !enableAggregation && styles.firstTh,
                      styles.hoverBg
                    )}
                    style={{ width: '2%' }}
                  >
                    <Checkbox
                      value={allSelected}
                      onChange={handleSelectAll}
                    />
                  </th>
                )}
                {columns.map((col, index) => (
                  <th
                    key={col.value}
                    style={{ width: col.width ?? 'fit-content' }}
                    className={clsx(
                      styles.sortable,
                      index === 0 && !enableSelection && !enableAggregation && styles.firstTh,
                      !columns[index + 1] && !hasActions && styles.lastTh,
                      !col.sortable && styles.pointerNone,
                    )}
                    onClick={() => handleSort(col)}
                  >
                    <div
                      className={styles.thContent}
                      style={{
                        justifyContent: col.align ?? 'flex-start',
                      }}
                    >
                      <p className={styles.thLabel}>{col.label}</p>
                      {col.sortable && (
                        <span
                          className={clsx(
                            styles.sortIcon,
                            isDesc[col.value] && styles.sortIconRotated,
                            col.value === sortByName && styles.sortIconActive
                          )}
                        >
                          <Icon name="arrow_upward" />
                        </span>
                      )}
                    </div>
                  </th>
                ))}
                {hasActions && (
                  <th style={{ flex: 1 }} className={clsx(styles.pointerNone)} />
                )}
              </tr>
            </thead>
          ) : (
            <thead>
              <tr>
                {Array.from({ length: colspan || 3 }).map((_, i) => (
                  <th key={i} className={styles.skeletonCell}>
                    <Skeleton />
                  </th>
                ))}
              </tr>
            </thead>
          )}
          {loading || !pagedItems.length ? (
            <tbody>
              {loading ? (
                Array.from({ length: 10 }).map((_, i) => (
                  <tr key={`skeleton-${i}`}>
                    {Array.from({ length: colspan || 3 }).map((_, j) => (
                      <td key={j} className={styles.skeletonCell}>
                        <Skeleton />
                      </td>
                    ))}
                    {hasActions && (
                      <td className={styles.skeletonCell}>
                        <Skeleton />
                      </td>
                    )}
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={colspan}>
                    {renderEmptyState?.() || emptySlot || null}
                  </td>
                </tr>
              )}
            </tbody>
          ) : (
            <tbody>
              {pagedItems.map((item, rowIndex) => (
                <React.Fragment key={rowIndex}>
                  <tr
                    className={clsx(
                      styles.row,
                      hasHover && styles.rowHover,
                    )}
                  >
                    {enableAggregation && (
                      <td className={styles.cell}>
                        {renderAggregation?.(item, rowIndex)}
                      </td>
                    )}
                    {enableSelection && (
                      <td className={styles.cell}>
                        {renderSelect ? (
                          renderSelect(item, rowIndex)
                        ) : (
                          <Checkbox
                            value={selectedRows.has(rowIndex)}
                            onChange={() => handleSelectRow(rowIndex, item)}
                          />
                        )}
                      </td>
                    )}
                    {columns.map((col) => (
                      <td
                        key={col.value}
                        className={styles.cell}
                        style={{
                          textAlign:
                            col.align === 'center'
                              ? 'center'
                              : col.align === 'flex-end'
                              ? 'right'
                              : 'left',
                        }}
                      >
                        {col.render
                          ? col.render(item[col.value], item, rowIndex)
                          : item[col.value]}
                      </td>
                    ))}
                    {renderActions && (
                      <td className={styles.cell}>
                        {renderActions(item, rowIndex)}
                      </td>
                    )}
                    {!renderActions && actionsSlot && (
                      <td className={styles.cell}>{actionsSlot}</td>
                    )}
                  </tr>
                  {item.expanded && renderChilds && renderChilds(item, rowIndex)}
                </React.Fragment>
              ))}
            </tbody>
          )}
          {(renderFooter || footerSlot) && (
            <tfoot>
              {renderFooter?.() || footerSlot}
            </tfoot>
          )}
        </table>
      </div>
      {!hideFooter && (
        <footer className={styles.footer}>
          <div className={styles.footerLeft}>
            <p className={styles.footerLabel}>
              {renderItemsPerPage?.() || 'Items per page'}
            </p>
            <Select
              value={currentItemsPerPage}
              options={listPerPage}
              onChange={(v: any) => handleChangeItemsPerPage(v)}
            />
          </div>
          <Pagination
            value={currentPage}
            onChange={handleChangePage}
            length={pageCount}
          />
          <div>
            <p className={styles.footerLabel}>
              {renderShowingPage
                ? renderShowingPage(min, max, totalItems)
                : `Showing ${min}-${max} of ${totalItems}`}
            </p>
          </div>
        </footer>
      )}
    </div>
  );
}

Table.Actions = TableActions;
Table.Footer = TableFooter;
Table.EmptyState = TableEmptyState;

// src/components/Table/Table.vue
<script setup lang="ts">
import { ref, watch, onBeforeMount, computed, useSlots } from "vue";

type Column = {
  label?: string;
  value: string;
  sortable?: boolean;
  width?: string;
  align?: string;
};

type SortOptions = {
  by?: string;
  desc?: boolean;
};

const props = withDefaults(
  defineProps<{
    columns: Column[];
    items: any[];
    sortOptions?: SortOptions;
    page?: number;
    itemsPerPage?: number;
    numberOfItems?: number;
    renderPaginationInBackEnd?: boolean;
    hideFooter?: boolean;
    isHeaderFixed?: boolean;
    enableSelection?: boolean;
    enableAggregation?: boolean;
    loading?: boolean;
    noShadow?: boolean;
    hasHover?: boolean;
  }>(),
  {
    page: 1,
    itemsPerPage: 10,
    numberOfItems: 0,
    renderPaginationInBackEnd: false,
    hideFooter: false,
    isHeaderFixed: false,
    enableSelection: false,
    enableAggregation: false,
    loading: false,
    noShadow: false,
    hasHover: false,
  }
);

const emit = defineEmits<{
  "update:page": [value: number];
  "update:itemsPerPage": [value: number];
  sortBy: [key: string, desc: boolean];
  pageItems: [page: number, itemsPerPage: number];
  selectAll: [value: boolean];
}>();
const slots = useSlots();

const sortByName = ref(props.sortOptions?.by || "");
const pagedItems = ref(props.items || []);
const isDesc: any = ref(getAllHeaderKeys());
const itemsPerPageHolder = ref(props.itemsPerPage || 10);
const pageHolder = ref(props.page || 1);
const listPerPage = ref([5, 10, 20, 50, 100]);
const allSelected = ref(false);

const numberPage = computed((): number => {
  if (props.renderPaginationInBackEnd) {
    return Math.ceil(props.numberOfItems / itemsPerPageHolder.value);
  }

  return Math.ceil(props.items?.length / itemsPerPageHolder.value);
});
const min = computed((): number =>
  pageHolder.value === 1
    ? 1
    : (pageHolder.value - 1) * itemsPerPageHolder.value + 1
);
const max = computed(
  (): number =>
    (pageHolder.value - 1) * itemsPerPageHolder.value + pagedItems.value.length
);
const total = computed((): number =>
  props.renderPaginationInBackEnd
    ? props.numberOfItems
    : props.items?.length || 0
);
const colspan = computed((): number => {
  let colspan = props.columns.length;
  if (props.enableSelection) colspan++;
  if (props.enableAggregation) colspan++;
  if (slots.actions) colspan++;
  return colspan;
});

onBeforeMount(() => {
  if (props.renderPaginationInBackEnd) return;

  if (sortByName.value) {
    sortBy(sortByName.value, props.sortOptions?.desc);
  } else {
    pageItems(props.page, props.itemsPerPage);
  }
});

watch(
  () => props.itemsPerPage,
  (newValue) => {
    changeItemsPerPage(newValue, false);
  }
);

watch(
  () => props.page,
  (newValue) => {
    changePage(newValue, false);
  }
);

watch(
  () => props.items,
  () => {
    pagedItems.value = props.items;

    if (!props.renderPaginationInBackEnd)
      sortBy(sortByName.value, isDesc.value[sortByName.value], false);
  },
  { deep: true, immediate: true }
);

function getAllHeaderKeys(): { [key: string]: boolean } {
  const result: any = {};
  props.columns.forEach((header: any) => {
    if (header.value == sortByName.value) {
      result[header.value] = !!props.sortOptions?.desc;
    } else {
      result[header.value] = false;
    }
  });
  return result;
}

function changePage(page: number, emitEvent = true) {
  pageHolder.value = page;
  if (emitEvent) emit("update:page", page);
  pageItems(page, itemsPerPageHolder.value);
}

function changeItemsPerPage(itemsPerPage: number, emitEvent = true) {
  itemsPerPageHolder.value = itemsPerPage || 10;
  pageHolder.value = 1;

  if (emitEvent) emit("update:itemsPerPage", itemsPerPage);
  emit("update:page", 1);

  sortBy(sortByName.value, isDesc.value[sortByName.value]);
}

function sortBy(key: string, isDesc = true, emitEvent = true) {
  if (props.renderPaginationInBackEnd) {
    if (emitEvent) emit("sortBy", key, isDesc);
  } else {
    sortByName.value = key;
    pagedItems.value = props.items?.sort((a: any, b: any) => {
      const valueA = a[key];
      const valueB = b[key];

      if (typeof valueA === "string" && typeof valueB === "string") {
        const lowerA = valueA.toLowerCase();
        const lowerB = valueB.toLowerCase();
        return isDesc
          ? lowerA.localeCompare(lowerB)
          : lowerB.localeCompare(lowerA);
      } else if (typeof valueA === "number" && typeof valueB === "number") {
        return isDesc ? valueA - valueB : valueB - valueA;
      } else if (valueA instanceof Date && valueB instanceof Date) {
        return isDesc
          ? valueA.getTime() - valueB.getTime()
          : valueB.getTime() - valueA.getTime();
      } else {
        const stringA = String(valueA);
        const stringB = String(valueB);
        const lowerA = stringA.toLowerCase();
        const lowerB = stringB.toLowerCase();
        return isDesc
          ? lowerA.localeCompare(lowerB)
          : lowerB.localeCompare(lowerA);
      }
    });
  }
  pageItems(pageHolder.value, itemsPerPageHolder.value);
}

function pageItems(page: number, itemsPerPage: number) {
  if (props.renderPaginationInBackEnd) {
    emit("pageItems", page, itemsPerPage);
  } else {
    const startIndex = (page - 1) * itemsPerPage;
    const endIndex = startIndex + itemsPerPage;
    pagedItems.value = props.items?.slice(startIndex, endIndex);
  }
}

function selectAll(value: boolean | null) {
  emit("selectAll", !!value);
  props.items?.map((item: any) => (item.selected = value));
  pagedItems.value = props.items;
}
</script>

<template>
  <div class="table">
    <div
      class="table-content"
      :class="{ 'header-fixed-table': isHeaderFixed, 'no-shadow': noShadow }"
    >
      <table class="table-style">
        <thead v-if="!loading">
          <tr>
            <th
              v-if="enableAggregation"
              :disabled="!pagedItems.length"
              class="first-th pointer-events-none"
              :style="{ width: '2%' }"
            />
            <th
              v-if="enableSelection"
              :disabled="!pagedItems.length"
              class="hover:bg-neutral-surface-default"
              :class="{ 'first-th': !enableAggregation }"
              :style="{ width: '2%' }"
            >
              <Checkbox v-model="allSelected" @update:model-value="selectAll" />
            </th>
            <th
              v-for="(header, index) in columns"
              :key="index"
              class="cursor-pointer"
              :class="{
                'first-th': index === 0 && !enableSelection && !enableAggregation,
                'last-th': !columns[index + 1] && !$slots.actions,
                'pointer-events-none': !header.sortable,
              }"
              :style="{ width: header.width ? header.width : 'fit-content' }"
              @click="
                sortBy(
                  header.value,
                  (isDesc[header.value] = !isDesc[header.value])
                )
              "
            >
              <div
                class="flex w-full items-center gap-xs text-neutral-interaction-default"
                :style="{
                  'justify-content': header.align ? header.align : 'flex-start',
                }"
              >
                <p class="truncate">{{ header.label }}</p>
                <span
                  v-if="header.sortable"
                  class="icon"
                  :class="{
                    'rotate-180': isDesc[header.value],
                    'icon-active': header.value == sortByName,
                  }"
                >
                  <Icon name="arrow_upward" />
                </span>
              </div>
            </th>
            <th
              v-if="$slots.actions"
              style="flex: 1"
              class="pointer-events-none"
            />
          </tr>
        </thead>
        <thead v-else>
          <tr>
            <th
              v-for="header in colspan || 3"
              :key="header"
              class="skeleton-table-cell"
            >
              <Skeleton />
            </th>
          </tr>
        </thead>
        <tbody v-if="loading || !pagedItems.length">
          <tr v-if="loading" v-for="index in 10" :key="index">
            <td
              v-for="header in colspan || 3"
              :key="header"
              class="skeleton-table-cell"
            >
              <Skeleton />
            </td>
            <td v-if="$slots.actions" class="skeleton-table-cell">
              <Skeleton />
            </td>
          </tr>
          <tr v-else-if="!pagedItems.length">
            <td colspan="100%">
              <slot name="empty-state" />
            </td>
          </tr>
        </tbody>
        <tbody v-else>
          <template v-for="(item, index) in pagedItems" :key="index">
            <tr
              class="[&>*]:py-sm [&>*]:px-lg text-neutral-foreground-low"
              :class="{ 'hover:bg-primary-surface-default': hasHover }"
            >
              <slot
                v-if="enableAggregation"
                name="aggregation"
                :item="item"
                :index="index"
              />
              <slot
                v-if="enableSelection"
                name="select"
                :item="item"
                :index="index"
              />
              <slot
                v-for="header in columns"
                :key="header.value"
                :name="header.value"
                :item="item"
                :index="index"
              />
              <slot
                v-if="$slots.actions"
                name="actions"
                :item="item"
                :index="index"
              />
            </tr>
            <slot
              name="childs"
              :item="item"
              :index="index"
              v-if="item.expanded"
            />
          </template>
        </tbody>
        <tfoot v-if="$slots.footer">
          <slot name="footer" />
        </tfoot>
      </table>
    </div>
    <footer
      class="flex items-center justify-between mt-base text-neutral-foreground-low flex-wrap"
      v-if="!hideFooter"
    >
      <div class="flex items-center gap-xs">
        <p class="text-sm">
          <slot name="items-per-page"> Items per page </slot>
        </p>
        <Select
          v-model="itemsPerPageHolder"
          :options="listPerPage"
          @update:model-value="changeItemsPerPage"
        >
          {{ itemsPerPageHolder }}
        </Select>
      </div>
      <Pagination
        v-model="pageHolder"
        :length="numberPage"
        @update:model-value="changePage"
      />
      <div>
        <p class="text-sm">
          <slot name="showing-page" :min="min" :max="max" :total="total">
            Showing {{ min }}-{{ max }} of {{ total }}
          </slot>
        </p>
      </div>
    </footer>
  </div>
</template>

<style scoped>
@reference "../../assets/main.css";

.table {
  @apply block w-full max-w-full;
}

.table-content {
  @apply min-w-full max-w-full overflow-x-auto rounded-xl bg-neutral-surface-default border-xxs border-neutral-default shadow-neutral-selected;
}

.table-content.no-shadow {
  @apply shadow-none border-none;
}

.table-content.header-fixed-table {
  @apply overflow-y-auto max-h-[35em];

  .table-style thead {
    @apply top-none sticky;
  }
}

.icon {
  @apply h-fit w-fit flex items-center transition-transform ease-in-out duration-300;

  .icon {
    @apply text-lg;
  }
}

.table-style {
  @apply w-full rounded-xl bg-neutral-surface-default;

  thead {
    @apply border-b-xxs border-b-neutral-default;
  }

  tbody {
    @apply divide-y-xxs divide-neutral-default w-full;
  }

  tr {
    @apply rounded-xl;
  }

  th {
    @apply py-base px-lg hover:bg-neutral-surface-highlight;

    .icon.icon-active {
      @apply text-primary-interaction-default opacity-100;
    }

    .icon {
      @apply opacity-0;
      transition: opacity 0.2s ease, transform 0.3s ease;
    }
  }

  th:hover .icon {
    @apply opacity-100;
  }
}

.first-th {
  @apply rounded-ss-xl;
}

.last-th {
  @apply rounded-se-xl;
}

.skeleton-table-cell {
  @apply p-base;
}

.skeleton-table-cell .skeleton {
  @apply h-sm w-full;
}
</style>
