// src/components/Tooltip/Tooltip.vue
<script setup lang="ts">
import {
  ref,
  nextTick,
  computed,
} from "vue";

const props = withDefaults(
  defineProps<{
    labelValue?: string;
    position?: "top" | "bottom" | "left" | "right";
  }>(),
  {
    labelValue: "",
    position: "right",
  }
);

const isHovering = ref(false);
const content = ref<HTMLElement>();
const tooltip = ref<HTMLElement>();

const computedPadding = computed((): number => {
  if (
    document.readyState === "complete" ||
    document.readyState === "interactive"
  ) {
    return Number(
      (
        (content.value as any)
          ?.computedStyleMap()
          .get("--spacing-xxs")
          ?.toString() || "4px"
      ).replace("px", "")
    );
  }
  return 4;
});

async function showTooltip() {
  isHovering.value = true;
  await nextTick();

  if (!content.value || !tooltip.value) return;

  const rect = (content.value.firstElementChild || content.value).getBoundingClientRect();
  const viewportWidth = window.innerWidth;

  calculatePosition(rect, tooltip.value);

  const closeHandler = () => {
    isHovering.value = false;
    document.removeEventListener("wheel", closeHandler);
  };

  document.addEventListener("wheel", closeHandler);

  const tooltipRect = tooltip.value.getBoundingClientRect();
  const tooltipContent = tooltip.value.querySelector(
    ".tooltip-content"
  ) as HTMLElement;
  if (!tooltipContent) return;

  tooltipContent.style.maxWidth = "none";
  tooltipContent.style.wordBreak = "normal";
  tooltipContent.style.whiteSpace = "normal";

  if (tooltipRect.left + tooltipRect.width > viewportWidth) {
    const triangleWidth = tooltipRect.width - tooltipContent.offsetWidth;
    tooltipContent.style.maxWidth = `${
      viewportWidth - tooltipRect.left - computedPadding.value - triangleWidth
    }px`;
    tooltipContent.style.wordBreak = "break-all";
    tooltipContent.style.whiteSpace = "wrap";
    calculatePosition(rect, tooltip.value);
  }
}

function calculatePosition(rect: DOMRect, tooltip: HTMLElement) {
  if (props.position === "left" || props.position === "right") {
    const horizontalPosition =
      props.position === "left"
        ? rect.left - tooltip.offsetWidth - computedPadding.value
        : rect.right + computedPadding.value;

    tooltip.style.left = `${Math.max(0, horizontalPosition)}px`;
    tooltip.style.top = `${
      rect.top + rect.height / 2 - tooltip.offsetHeight / 2
    }px`;
  } else {
    const verticalPosition =
      props.position === "top" ? rect.top - tooltip.offsetHeight : rect.bottom;

    tooltip.style.top = `${Math.max(0, verticalPosition)}px`;
    tooltip.style.left = `${
      rect.left + rect.width / 2 - tooltip.offsetWidth / 2
    }px`;
  }
}
</script>

<template>
  <div ref="content" @mouseenter="showTooltip" @mouseleave="isHovering = false">
    <Teleport to="body">
      <Transition name="opacity">
        <div
          v-if="isHovering"
          class="tooltip"
          ref="tooltip"
          :class="[position]"
        >
          <div class="tooltip-triangle" />
          <div class="tooltip-content">
            <slot name="label">
              {{ labelValue }}
            </slot>
          </div>
        </div>
      </Transition>
    </Teleport>
    <slot />
  </div>
</template>

<style scoped>
@reference "../../assets/main.css";

.opacity-enter-active,
.opacity-leave-active {
  @apply transition-opacity duration-500 ease-out;
}

.opacity-enter-from,
.opacity-leave-to {
  @apply opacity-0;
}

.tooltip {
  @apply z-[1004] fixed flex items-center;

  .tooltip-triangle {
    @apply w-0 h-0 border-[9px] border-r-0 border-[9px] border-l-[11px] border-l-negative border-transparent relative;
  }

  .tooltip-content {
    @apply flex items-center justify-center bg-negative p-xs rounded-base font-normal text-neutral-foreground-negative text-xs w-fit whitespace-nowrap;
  }
}

.right {
  @apply flex-row;

  .tooltip-triangle {
    @apply rotate-180 right-[-2px];
  }
}

.left {
  @apply flex-row-reverse;

  .tooltip-triangle {
    @apply left-[-2px];
  }
}

.top {
  @apply flex-col-reverse;

  .tooltip-triangle {
    @apply rotate-90 top-[-5px];
  }
}

.bottom {
  @apply flex-col;

  .tooltip-triangle {
    @apply rotate-[-90deg] bottom-[-5px];
  }
}
</style>

// src/components/Tooltip/Tooltip.tsx
import { useState, useRef, useEffect, useCallback } from 'react';
import { createPortal } from 'react-dom';
import clsx from 'clsx';
import { useTransition } from '../../hooks/useTransition';
import styles from './Tooltip.module.css';

export interface TooltipProps {
  labelValue?: string;
  position?: 'top' | 'bottom' | 'left' | 'right';
  children?: React.ReactNode;
  className?: string;
}

export function Tooltip({
  labelValue = '',
  position = 'right',
  children,
  className,
}: TooltipProps) {
  const [isHovering, setIsHovering] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);
  const tooltipRef = useRef<HTMLDivElement>(null);

  const { isMounted, isActive } = useTransition(isHovering, { duration: 500 });

  const calculatePosition = useCallback(
    (rect: DOMRect, el: HTMLElement) => {
      const padding = 4;
      if (position === 'left' || position === 'right') {
        const horizontalPosition =
          position === 'left'
            ? rect.left - el.offsetWidth - padding
            : rect.right + padding;
        el.style.left = `${Math.max(0, horizontalPosition)}px`;
        el.style.top = `${rect.top + rect.height / 2 - el.offsetHeight / 2}px`;
      } else {
        const verticalPosition =
          position === 'top' ? rect.top - el.offsetHeight : rect.bottom;
        el.style.top = `${Math.max(0, verticalPosition)}px`;
        el.style.left = `${rect.left + rect.width / 2 - el.offsetWidth / 2}px`;
      }
    },
    [position]
  );

  useEffect(() => {
    if (!isMounted || !contentRef.current || !tooltipRef.current) return;

    const rect = (
      contentRef.current.firstElementChild || contentRef.current
    ).getBoundingClientRect();
    calculatePosition(rect, tooltipRef.current);

    const tooltipEl = tooltipRef.current;
    const viewportWidth = window.innerWidth;
    const tooltipRect = tooltipEl.getBoundingClientRect();
    const tooltipContent = tooltipEl.querySelector(
      `.${styles.tooltipContent}`
    ) as HTMLElement;

    if (tooltipContent) {
      tooltipContent.style.maxWidth = 'none';
      tooltipContent.style.wordBreak = 'normal';
      tooltipContent.style.whiteSpace = 'normal';

      if (tooltipRect.left + tooltipRect.width > viewportWidth) {
        const triangleWidth = tooltipRect.width - tooltipContent.offsetWidth;
        tooltipContent.style.maxWidth = `${
          viewportWidth - tooltipRect.left - 4 - triangleWidth
        }px`;
        tooltipContent.style.wordBreak = 'break-all';
        tooltipContent.style.whiteSpace = 'wrap';
        calculatePosition(rect, tooltipEl);
      }
    }

    const closeHandler = () => setIsHovering(false);
    document.addEventListener('wheel', closeHandler);
    return () => document.removeEventListener('wheel', closeHandler);
  }, [isMounted, calculatePosition]);

  return (
    <div
      ref={contentRef}
      onMouseEnter={() => setIsHovering(true)}
      onMouseLeave={() => setIsHovering(false)}
      className={className}
    >
      {isMounted &&
        createPortal(
          <div
            ref={tooltipRef}
            className={clsx(
              styles.tooltip,
              styles[position],
              isActive && styles.active
            )}
          >
            <div className={styles.tooltipTriangle} />
            <div className={styles.tooltipContent}>{labelValue}</div>
          </div>,
          document.body
        )}
      {children}
    </div>
  );
}

Tooltip.Label = function TooltipLabel({
  children,
}: {
  children?: React.ReactNode;
}) {
  return <>{children}</>;
};
