// src/components/ProgressBar/ProgressBar.vue
<script setup lang="ts">
import { computed } from "vue";
import { blendColors } from "../../utils";

const props = withDefaults(
  defineProps<{
    modelValue?: number;
    size?: "small" | "medium" | "large";
    type?:
      | "primary"
      | "info"
      | "success"
      | "warning"
      | "danger"
      | "neutral";
    color?: string;
    icon?: string;
    infoMessage?: string;
    steps?: number;
    animationType?: "indeterminate" | "query" | undefined;
    displayPercentage?: "center" | "bar" | undefined;
    neutralBackground?: boolean;
  }>(),
  {
    modelValue: 0,
    size: "medium",
    type: "primary",
    color: "",
    icon: "",
    infoMessage: "",
    steps: 0,
    animationType: undefined,
    displayPercentage: undefined,
    neutralBackground: false,
  }
);

const progressWidth = computed((): string => {
  let value = props.modelValue * 100;
  if (props.steps) value = (props.modelValue / props.steps) * 100;
  else if (props.animationType) value = 50;

  return Math.max(0, Math.min(100, value)) + "%";
});

const background = computed((): string => {
  if (props.neutralBackground || !props.color) return "";
  return blendColors(props.color);
});

const component = computed((): string => {
  if (props.infoMessage) return "Tooltip";
  return "div";
});
</script>

<template>
  <div
    class="progress-bar"
    :class="[size, type, { 'neutral-bg': neutralBackground }]"
    :style="{ background: background }"
    v-if="!steps"
  >
    <div class="progress-holder">
      <div
        class="progress-fill"
        :class="[size, animationType]"
        :style="{ background: color, width: progressWidth }"
      >
        <label
          v-if="displayPercentage == 'bar' && !animationType"
          class="progress-label"
        >
          {{ progressWidth }}
        </label>
      </div>
      <label
        v-if="displayPercentage == 'center' && !animationType"
        class="progress-label absolute"
      >
        {{ progressWidth }}
      </label>
    </div>
    <component
      v-if="!animationType && (icon || $slots['icon-slot'])"
      class="progress-icon"
      :is="component"
      :label-value="infoMessage"
      position="bottom"
      :style="{
        left: progressWidth,
        color: color,
      }"
    >
      <slot name="icon-slot">
        <Icon :name="icon" />
      </slot>
    </component>
  </div>
  <div
    class="step-bar flex flex-row gap-xs"
    :class="[size, type, { 'neutral-bg': neutralBackground }]"
    v-else
  >
    <div
      v-for="step in props.steps"
      :key="step"
      class="step"
      :style="{
        background: step <= modelValue ? color : background,
        width: 100 / props.steps + '%',
      }"
      :class="{
        filled: step <= modelValue,
        'neutral-bg': neutralBackground,
      }"
    />
  </div>
</template>

<style scoped>
@reference "../../assets/main.css";

.progress-bar,
.step-bar .step {
  @apply flex items-center rounded-lg bg-primary-surface-highlight justify-start relative;
}

.small {
  @apply h-xs;

  .progress-label {
    @apply text-xxs;
  }

  .progress-icon .icon {
    @apply text-base;
  }
}

.medium {
  @apply h-sm;

  .progress-label {
    @apply text-xs;
  }

  .progress-icon .icon {
    @apply text-2xl;
  }
}

.large {
  @apply h-base;

  .progress-label {
    @apply text-sm;
  }

  .progress-icon .icon {
    @apply text-4xl;
  }
}

.progress-holder {
  @apply flex items-center overflow-hidden w-full rounded-base;
}

.progress-label {
  @apply h-fit w-full flex flex-row justify-center text-neutral-foreground-negative;
}

.progress-fill {
  @apply flex items-center justify-center bg-primary-foreground-low rounded-lg overflow-hidden;
  transition: width 0.5s ease-in-out;
}

.step-bar .step {
  transition: background-color 0.5s linear;
}

.step-bar .step.filled {
  @apply bg-primary-foreground-low;
}

.progress-bar.neutral-bg,
.step.neutral-bg {
  @apply bg-neutral-surface-disabled;
}

.progress-icon {
  @apply flex items-center absolute text-primary-foreground-low;
}

.info {
  @apply bg-informative-surface-highlight;

  .progress-fill {
    @apply bg-informative-foreground-low;
  }

  .step-bar .step.filled {
    @apply bg-informative-foreground-low;
  }

  .progress-icon {
    @apply text-informative-foreground-low;
  }
}

.success {
  @apply bg-success-surface-highlight;

  .progress-fill {
    @apply bg-success-foreground-low;
  }

  .step-bar .step.filled {
    @apply bg-success-foreground-low;
  }

  .progress-icon {
    @apply text-success-foreground-low;
  }
}

.warning {
  @apply bg-warning-surface-highlight;

  .progress-fill {
    @apply bg-warning-foreground-low;
  }

  .step-bar .step.filled {
    @apply bg-warning-foreground-low;
  }

  .progress-icon {
    @apply text-warning-foreground-low;
  }
}

.danger {
  @apply bg-danger-surface-highlight;

  .progress-fill {
    @apply bg-danger-foreground-low;
  }

  .step-bar .step.filled {
    @apply bg-danger-foreground-low;
  }

  .progress-icon {
    @apply text-danger-foreground-low;
  }
}

.neutral {
  @apply bg-neutral-surface-highlight;

  .progress-fill {
    @apply bg-neutral-foreground-low;
  }

  .step-bar .step.filled {
    @apply bg-neutral-foreground-low;
  }

  .progress-icon {
    @apply text-neutral-foreground-low;
  }
}

.progress-fill.indeterminate {
  animation: indeterminate 2s ease-in-out infinite;
  transform-origin: 100%;
}

.progress-fill.query {
  animation: query 2.7s ease-in-out infinite;
  transform-origin: 100%;
}

@keyframes query {
  0% {
    transform: translateX(-100%);
  }
  50% {
    transform: translateX(200%);
  }
  100% {
    transform: translateX(-100%);
  }
}

@keyframes indeterminate {
  0% {
    transform: translateX(-100%);
  }
  60% {
    transform: translateX(200%);
  }
  100% {
    transform: translateX(200%);
  }
}
</style>

// src/components/ProgressBar/ProgressBar.tsx
import clsx from 'clsx';
import { Icon } from '../Icon/Icon';
import { Tooltip } from '../Tooltip/Tooltip';
import { blendColors } from '../../utils';
import styles from './ProgressBar.module.css';

export interface ProgressBarProps {
  value?: number;
  size?: 'small' | 'medium' | 'large';
  type?: 'primary' | 'info' | 'success' | 'warning' | 'danger' | 'neutral';
  color?: string;
  icon?: string;
  infoMessage?: string;
  steps?: number;
  animationType?: 'indeterminate' | 'query' | undefined;
  displayPercentage?: 'center' | 'bar' | undefined;
  neutralBackground?: boolean;
  iconSlot?: React.ReactNode;
  children?: React.ReactNode;
  className?: string;
}

export function ProgressBar({
  value = 0,
  size = 'medium',
  type = 'primary',
  color = '',
  icon = '',
  infoMessage = '',
  steps = 0,
  animationType,
  displayPercentage,
  neutralBackground = false,
  iconSlot,
  className,
}: ProgressBarProps) {
  // Compute progress width
  const computeProgressWidth = (): string => {
    let val = value * 100;
    if (steps) val = (value / steps) * 100;
    else if (animationType) val = 50;
    return Math.max(0, Math.min(100, val)) + '%';
  };

  const progressWidth = computeProgressWidth();

  const background = (): string => {
    if (neutralBackground || !color) return '';
    return blendColors(color);
  };

  const showIcon = !animationType && (icon || iconSlot);

  const iconContent = (
    <>{iconSlot ?? <Icon name={icon} />}</>
  );

  // Step bar mode
  if (steps) {
    return (
      <div
        className={clsx(
          styles.stepBar,
          'flex flex-row gap-xs',
          styles[size],
          styles[type],
          neutralBackground && styles.neutralBg,
          className
        )}
      >
        {Array.from({ length: steps }, (_, i) => i + 1).map((step) => (
          <div
            key={step}
            className={clsx(
              styles.step,
              step <= value && styles.filled,
              neutralBackground && styles.neutralBg
            )}
            style={{
              background: step <= value ? color : background(),
              width: `${100 / steps}%`,
            }}
          />
        ))}
      </div>
    );
  }

  // Bar mode
  return (
    <div
      className={clsx(
        styles.progressBar,
        styles[size],
        styles[type],
        neutralBackground && styles.neutralBg,
        className
      )}
      style={{ background: background() }}
    >
      <div className={styles.progressHolder}>
        <div
          className={clsx(styles.progressFill, styles[size], animationType && styles[animationType])}
          style={{ background: color, width: progressWidth }}
        >
          {displayPercentage === 'bar' && !animationType && (
            <label className={styles.progressLabel}>{progressWidth}</label>
          )}
        </div>
        {displayPercentage === 'center' && !animationType && (
          <label className={clsx(styles.progressLabel, 'absolute')}>{progressWidth}</label>
        )}
      </div>
      {showIcon && (
        infoMessage ? (
          <Tooltip
            className={styles.progressIcon}
            labelValue={infoMessage}
            position="bottom"
          >
            {iconContent}
          </Tooltip>
        ) : (
          <div
            className={styles.progressIcon}
            style={{ left: progressWidth, color }}
          >
            {iconContent}
          </div>
        )
      )}
    </div>
  );
}
