// src/components/Image/Image.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from "vue";
import Icon from "../Icon/Icon.vue";
import Overlay from "../../utils/components/Overlay.vue";

interface ImageProps {
  src?: string;
  alt?: string;
  width?: string | number;
  height?: string | number;
  icon?: string;
  preview?: boolean;
}

const props = withDefaults(defineProps<ImageProps>(), {
  icon: "visibility",
  preview: false,
});

const emit = defineEmits<{
  show: [];
  hide: [];
}>();

const isHovering = ref(false);
const previewVisible = ref(false);
const rotate = ref(0);
const scale = ref(1);
const tools = ref([
  {
    icon: "rotate_left",
    label: "Rotate Left",
    click: rotateLeft,
  },
  {
    icon: "rotate_right",
    label: "Rotate Right",
    click: rotateRight,
  },
  {
    icon: "zoom_out",
    label: "Zoom Out",
    disabled: () => scale.value <= 0.5,
    click: zoomOut,
  },
  {
    icon: "zoom_in",
    label: "Zoom In",
    disabled: () => scale.value >= 1.5,
    click: zoomIn,
  },
  {
    icon: "close",
    label: "Close",
    click: hidePreview,
  },
]);

const imageStyle = computed(() => {
  const style: Record<string, string> = {};
  if (props.width) {
    style.width =
      typeof props.width === "number" ? `${props.width}px` : props.width;
  }
  if (props.height) {
    style.height =
      typeof props.height === "number" ? `${props.height}px` : props.height;
  }
  return style;
});

const previewImageStyle = computed(() => ({
  transform: `rotate(${rotate.value}deg) scale(${scale.value})`,
  transition: "transform 0.15s",
}));

onMounted(() => {
  window.addEventListener("keydown", onKeyDown);
});

onUnmounted(() => {
  window.removeEventListener("keydown", onKeyDown);
  document.body.style.overflow = "";
});

function showPreview() {
  previewVisible.value = true;
  emit("show");
  document.body.style.overflow = "hidden";
}

function hidePreview() {
  previewVisible.value = false;
  emit("hide");
  rotate.value = 0;
  scale.value = 1;
  document.body.style.overflow = "";
}

function rotateRight() {
  rotate.value += 90;
}

function rotateLeft() {
  rotate.value -= 90;
}

function zoomIn() {
  scale.value = Math.min(scale.value + 0.1, 1.5);
}

function zoomOut() {
  scale.value = Math.max(scale.value - 0.1, 0.5);
}

function closePreview() {
  hidePreview();
}

function onKeyDown(event: KeyboardEvent) {
  if (!previewVisible.value) return;

  switch (event.code) {
    case "Escape":
      hidePreview();
      break;
  }
}
</script>

<template>
  <span
    class="image"
    @mouseenter="isHovering = true"
    @mouseleave="isHovering = false"
  >
    <slot name="image">
      <img :src="src" :alt="alt" :style="imageStyle" class="image-content" />
    </slot>

    <div v-if="preview" class="cursor-pointer" @click="showPreview">
      <Overlay
        class="image-preview-overlay"
        :model-value="isHovering"
        :z-index="1"
      >
        <div v-if="isHovering" class="image-preview-overlay-content">
          <slot name="image-overlay">
            <Icon :name="icon" />
          </slot>
        </div>
      </Overlay>
    </div>

    <Teleport to="body">
      <Overlay v-model="previewVisible" :z-index="1000" @click="closePreview">
        <Transition name="bounce">
          <div
            class="preview-modal image-preview-container"
            v-if="previewVisible"
          >
            <slot name="preview">
              <img
                :src="src"
                :alt="alt"
                :style="previewImageStyle"
                class="image-preview"
              />
            </slot>
          </div>
        </Transition>
        <Transition name="fade-in">
          <div
            class="preview-modal image-preview-toolbar"
            v-if="previewVisible"
            role="dialog"
            aria-modal
          >
            <Button
              v-for="tool in tools"
              :key="tool.icon"
              :icon="tool.icon"
              :aria-label="tool.label"
              :disabled="tool.disabled ? tool.disabled() : false"
              class="tool"
              color="neutral"
              variant="plain"
              round
              @click="tool.click"
            />
          </div>
        </Transition>
      </Overlay>
    </Teleport>
  </span>
</template>

<style scoped>
@reference "../../assets/main.css";

.image {
  @apply relative inline-block;
}

.image-content {
  @apply max-w-full h-auto;
}

::deep(.image-preview-overlay.background-div) {
  @apply absolute w-full h-full cursor-pointer;
}

.image-preview-overlay-content {
  @apply z-[2] absolute inset-none flex items-center justify-center;
}

.image-preview-overlay-content .icon {
  @apply text-2xl text-neutral-foreground-negative;
}

.preview-modal {
  @apply z-[1001] fixed w-fit h-fit;
}

.image-preview-toolbar {
  @apply top-lg right-lg flex gap-xs bg-emphasis p-xxs rounded-base;
}

.tool {
  @apply h-fit;
}

.image-preview-container {
  @apply top-[50%] left-[50%] flex items-center justify-center;
  transition: transform 0.5s ease;
  transform: translate(-50%, -50%);
  max-width: calc(100% - var(--spacing-xl));
  max-height: calc(100% - var(--spacing-xl));
}

.image-preview {
  @apply max-w-full max-h-[80vh] object-contain;
}

.fade-in-enter-active,
.fade-in-leave-active {
  transition: opacity 0.15s ease-out;
}

.fade-in-enter-from,
.fade-in-leave-to {
  opacity: 0;
}

.fade-in-enter-to,
.fade-in-leave-from {
  opacity: 1;
}

.bounce-enter-active {
  animation: bounce-in 0.5s;
}

.bounce-leave-active {
  animation: bounce-in 0.5s reverse;
}

@keyframes bounce-in {
  0% {
    transform: translate(-50%, -50%) scale(0);
    opacity: 0;
  }
  100% {
    transform: translate(-50%, -50%) scale(1);
    opacity: 1;
  }
}
</style>

// src/components/Image/Image.tsx
import { useState, useEffect, useRef } from 'react';
import { createPortal } from 'react-dom';
import clsx from 'clsx';
import { Button } from '../Button/Button';
import { Icon } from '../Icon/Icon';
import { useTransition } from '../../hooks/useTransition';
import styles from './Image.module.css';

export interface ImageProps {
  src?: string;
  alt?: string;
  width?: string | number;
  height?: string | number;
  icon?: string;
  preview?: boolean;
  className?: string;
  onShow?: () => void;
  onHide?: () => void;
}

export function Image({
  src,
  alt,
  width,
  height,
  icon = 'visibility',
  preview = false,
  className,
  onShow,
  onHide,
}: ImageProps) {
  const [isHovering, setIsHovering] = useState(false);
  const [isPreviewOpen, setIsPreviewOpen] = useState(false);
  const [rotate, setRotate] = useState(0);
  const [scale, setScale] = useState(1);

  const { isMounted, isActive } = useTransition(isPreviewOpen, { duration: 150 });

  const imageStyle: React.CSSProperties = {};
  if (width) {
    imageStyle.width = typeof width === 'number' ? `${width}px` : width;
  }
  if (height) {
    imageStyle.height = typeof height === 'number' ? `${height}px` : height;
  }

  const previewImageStyle: React.CSSProperties = {
    transform: `rotate(${rotate}deg) scale(${scale})`,
    transition: 'transform 0.15s',
  };

  function showPreview() {
    setIsPreviewOpen(true);
    document.body.style.overflow = 'hidden';
    onShow?.();
  }

  function hidePreview() {
    setIsPreviewOpen(false);
    document.body.style.overflow = '';
    setRotate(0);
    setScale(1);
    onHide?.();
  }

  function rotateLeft() {
    setRotate((r) => r - 90);
  }

  function rotateRight() {
    setRotate((r) => r + 90);
  }

  function zoomIn() {
    setScale((s) => Math.min(s + 0.1, 1.5));
  }

  function zoomOut() {
    setScale((s) => Math.max(s - 0.1, 0.5));
  }

  useEffect(() => {
    function onKeyDown(event: KeyboardEvent) {
      if (!isPreviewOpen) return;
      if (event.code === 'Escape') {
        hidePreview();
      }
    }
    document.addEventListener('keydown', onKeyDown);
    return () => {
      document.removeEventListener('keydown', onKeyDown);
    };
  }, [isPreviewOpen]);

  useEffect(() => {
    return () => {
      document.body.style.overflow = '';
    };
  }, []);

  const tools = [
    {
      icon: 'rotate_left',
      label: 'Rotate Left',
      disabled: false,
      onClick: rotateLeft,
    },
    {
      icon: 'rotate_right',
      label: 'Rotate Right',
      disabled: false,
      onClick: rotateRight,
    },
    {
      icon: 'zoom_out',
      label: 'Zoom Out',
      disabled: scale <= 0.5,
      onClick: zoomOut,
    },
    {
      icon: 'zoom_in',
      label: 'Zoom In',
      disabled: scale >= 1.5,
      onClick: zoomIn,
    },
    {
      icon: 'close',
      label: 'Close',
      disabled: false,
      onClick: hidePreview,
    },
  ];

  const backdropRef = useRef<HTMLDivElement>(null);

  function handleBackdropClick(e: React.MouseEvent<HTMLDivElement>) {
    if (e.target === backdropRef.current) {
      hidePreview();
    }
  }

  return (
    <span
      className={clsx(styles.image, 'image', className)}
      onMouseEnter={() => setIsHovering(true)}
      onMouseLeave={() => setIsHovering(false)}
    >
      <img src={src} alt={alt} style={imageStyle} className={styles.imageContent} />

      {preview && (
        <div
          className={clsx(styles.imagePreviewOverlay, isHovering && styles.imagePreviewOverlayVisible)}
          onClick={showPreview}
        >
          <div className={styles.imagePreviewOverlayContent}>
            <Icon name={icon} />
          </div>
        </div>
      )}

      {isMounted &&
        createPortal(
          <div
            ref={backdropRef}
            className={clsx(styles.backdrop, isActive && styles.backdropActive)}
            onClick={handleBackdropClick}
          >
            <div
              className={clsx(
                styles.previewModal,
                styles.imagePreviewContainer,
                isActive && styles.previewImageActive
              )}
            >
              <img
                src={src}
                alt={alt}
                style={previewImageStyle}
                className={styles.imagePreview}
              />
            </div>

            <div
              className={clsx(
                styles.previewModal,
                styles.imagePreviewToolbar,
                isActive && styles.toolbarActive
              )}
              role="dialog"
              aria-modal
            >
              {tools.map((tool) => (
                <Button
                  key={tool.icon}
                  icon={tool.icon}
                  aria-label={tool.label}
                  disabled={tool.disabled}
                  className={styles.tool}
                  color="neutral"
                  variant="plain"
                  round
                  onClick={tool.onClick}
                />
              ))}
            </div>
          </div>,
          document.body
        )}
    </span>
  );
}
