// src/components/Accordion/Accordion.vue
<script setup lang="ts">
import {
  ref,
  onMounted,
  onBeforeUnmount,
  onUpdated,
  computed,
  watch,
} from "vue";

const props = withDefaults(
  defineProps<{
    modelValue: boolean;
    duration?: number;
    noShadow?: boolean;
  }>(),
  {
    modelValue: false,
    duration: 150,
    noShadow: false,
  }
);

const emit = defineEmits<{
  "update:modelValue": [value: boolean];
}>();

const model = ref(props.modelValue);
let card = ref<HTMLDivElement>();
let content = ref<HTMLDivElement>();
const resizeObserver = new ResizeObserver(resize);
const mutationObserver = new MutationObserver(resize);

watch(
  () => props.modelValue,
  () => {
    model.value = props.modelValue;
    resize();
  }
);

const parsedDuration = computed((): number => {
  try {
    const rounded = Math.floor(props.duration);

    return Math.min(Math.max(rounded, 150), 1000);
  } catch (error) {
    return 150;
  }
});

onMounted(() => {
  if (card.value) resizeObserver.observe(card.value, { box: "border-box" });
  if (content.value) {
    resizeObserver.observe(content.value, { box: "border-box" });
    mutationObserver.observe(content.value, {
      childList: true,
      subtree: true,
      attributes: true,
      attributeFilter: ["data-max-height"],
    });
  }
});

onUpdated(resize);

onBeforeUnmount(() => {
  if (resizeObserver) resizeObserver.disconnect();
  if (mutationObserver) mutationObserver.disconnect();
});

async function resize() {
  if (!content.value) return;

  content.value.style.maxHeight = model.value
    ? `${content.value.scrollHeight}px`
    : "0px";

  if (content.value.style.maxHeight != content.value.dataset.maxHeight)
    content.value.dataset.maxHeight = content.value.style.maxHeight;
}

function changeModel() {
  model.value = !model.value;
  emit("update:modelValue", model.value);
}
</script>

<template>
  <Card class="accordion" :class="{ 'no-shadow': noShadow }">
    <div class="w-full flex flex-col" ref="card">
      <div
        class="accordion-header"
        :class="[
          $slots.header ? 'justify-between' : 'justify-end', 
          { 'rounded-b-base': !model }
        ]"
        @click="changeModel"
      >
        <span v-if="$slots.header" class="flex-1">
          <slot name="header" />
        </span>
        <div
          class="flex items-center w-fit h-fit transition-transform ease-in-out duration-300 text-2xl leading-xxs"
          :class="{ 'rotate-180': model }"
        >
          <Icon
            name="expand_more"
            class="text-neutral-interaction-default font-bold"
            tabindex="0"
            aria-label="Expand"
            :aria-expanded="!!model"
            @keydown.space.prevent
            @keyup.enter.space="changeModel"
          />
        </div>
      </div>
      <div
        class="transition-[padding]"
        :class="{ 'px-base pt-xxs pb-xs': model }"
        :style="{ 'transition-duration': `${parsedDuration}ms` }"
      >
        <Transition name="content">
          <div
            ref="content"
            v-show="model"
            class="transition-[max-height] ease-in-out"
            :class="{ 'overflow-hidden': !model }"
            :style="{ 'transition-duration': `${parsedDuration}ms` }"
            data-max-height="0px"
          >
            <slot />
          </div>
        </Transition>
      </div>
    </div>
  </Card>
</template>

<style scoped>
@reference "../../assets/main.css";

.accordion {
  @apply bg-neutral-surface-default w-full;
}

.accordion:not(.no-shadow) {
  @apply shadow-neutral-default rounded-base;
}

.accordion.no-shadow {
  @apply border-none shadow-none;
}

.accordion .accordion-header {
  @apply flex items-center w-full px-base py-xs text-base cursor-pointer rounded-t-base transition-colors duration-300 hover:bg-neutral-surface-hover;
}
</style>

// src/components/Accordion/Accordion.tsx
import { useRef, useEffect, useLayoutEffect } from "react";
import clsx from "clsx";
import { useControllable } from "../../hooks/useControllable";
import { onEnterOrSpace, preventSpaceScroll } from "../../utils";
import styles from "./Accordion.module.css";
import { Icon } from "../Icon";
import { Card } from "../Card";

export interface AccordionProps {
  value?: boolean;
  onChange?: (value: boolean) => void;
  duration?: number;
  noShadow?: boolean;
  disabled?: boolean;
  header?: React.ReactNode;
  children?: React.ReactNode;
  className?: string;
}

export function Accordion({
  value,
  onChange,
  duration = 300,
  noShadow = false,
  disabled = false,
  header,
  children,
  className,
}: AccordionProps) {
  const [isExpanded, setExpanded] = useControllable<boolean>({
    value,
    defaultValue: false,
    onChange,
  });
  const clampedDuration = Math.min(1000, Math.max(150, duration ?? 300));

  const cardRef = useRef<HTMLDivElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);
  const isExpandedRef = useRef(isExpanded);

  isExpandedRef.current = isExpanded;

  useLayoutEffect(() => {
    if (!isExpanded && contentRef.current) {
      contentRef.current.style.maxHeight = "0px";
    }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  function resize() {
    if (!contentRef.current) return;
    contentRef.current.style.maxHeight = isExpandedRef.current
      ? `${contentRef.current.scrollHeight}px`
      : "0px";
  }

  useEffect(() => {
    const cardEl = cardRef.current;
    const contentEl = contentRef.current;

    const resizeObs = new ResizeObserver(() => resize());
    const mutationObs = new MutationObserver(() => resize());

    if (cardEl) resizeObs.observe(cardEl, { box: "border-box" });
    if (contentEl) {
      resizeObs.observe(contentEl, { box: "border-box" });
      mutationObs.observe(contentEl, {
        childList: true,
        subtree: true,
        attributes: true,
        attributeFilter: ["data-max-height"],
      });
    }

    return () => {
      resizeObs.disconnect();
      mutationObs.disconnect();
    };
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    resize();
  });

  function handleToggle() {
    if (!disabled) {
      setExpanded(!isExpanded);
    }
  }

  return (
    <Card
      className={clsx(
        styles.accordion,
        "accordion",
        noShadow && styles.noShadow,
        className,
      )}
    >
      <div ref={cardRef} className="w-full flex flex-col">
        <div
          className={clsx(
            styles.header,
            disabled && styles.disabled,
            isExpanded && styles.expanded,
          )}
          onClick={handleToggle}
        >
          {header && <span className={styles.headerText}>{header}</span>}
          <Icon
            className={clsx(styles.chevron, isExpanded && styles.expanded)}
            name="expand_more"
            tabIndex={disabled ? -1 : 0}
            aria-label="Expand"
            aria-expanded={isExpanded}
            onKeyDown={preventSpaceScroll}
            onKeyUp={onEnterOrSpace(handleToggle)}
          />
        </div>
        <div
          className={clsx(
            styles.contentContainer,
            isExpanded && styles.expanded,
          )}
          style={{ transitionDuration: `${clampedDuration}ms` }}
        >
          <div
            ref={contentRef}
            className={styles.content}
            style={{ transitionDuration: `${clampedDuration}ms` }}
          >
            {children}
          </div>
        </div>
      </div>
    </Card>
  );
}
