// src/components/Tree/Tree.vue
<script setup lang="ts">
import { ref, watch, onBeforeMount } from "vue";
import { type Option as OptionType } from "#utils/types/DropOption";
import { isObject } from "../../utils";
import Option from "./Option.vue";

type ModelValue =
  | string
  | number
  | boolean
  | object
  | Array<string | number | boolean | object | OptionType>
  | OptionType
  | undefined;

const props = withDefaults(
  defineProps<{
    modelValue?: ModelValue;
    options: OptionType[];
    labelKey?: string;
    valueKey?: string;
    getObject?: boolean;
    multiple?: boolean;
    disabled?: boolean;
  }>(),
  {
    modelValue: undefined,
    options: () => [] as OptionType[],
    labelKey: "label",
    valueKey: "value",
    getObject: false,
    multiple: false,
    disabled: false,
  }
);

const emit = defineEmits<{
  "update:modelValue": [value: ModelValue];
}>();

const model = ref<ModelValue>(undefined);

watch(() => props.modelValue, checkValidModel, { immediate: true, deep: true });
watch(
  () => props.multiple,
  () => {
    checkValidModel();
    updateModel();
  },
  { immediate: true }
);
watch(
  () => props.getObject,
  () => {
    model.value = undefined;
    updateModel();
  },
  { immediate: true }
);

onBeforeMount(() => {
  checkValidModel();
  updateModel();
});

function checkValidModel() {
  if (props.multiple) {
    if (!props.modelValue) model.value = [];
    else if (!Array.isArray(props.modelValue)) model.value = [props.modelValue];
    else model.value = [...props.modelValue];
  } else if (Array.isArray(props.modelValue)) model.value = props.modelValue[0];
  else model.value = props.modelValue;
}

function updateModel() {
  emit("update:modelValue", model.value);
}

function getOption(option: OptionType) {
  return props.getObject ? option : getValue(option);
}

function getValue(option: OptionType) {
  return isObject(option) ? (option as any)[props.valueKey] : option;
}

function getParent(value: OptionType, options = props.options): OptionType | undefined {
  return options?.find((option: OptionType) => {
    if (!option.options || !option.options.length) return false;

    const founded = option.options.find(
      (x: OptionType) => getValue(x) === getValue(value)
    );
    if (founded) return founded;

    return getParent(value, option.options);
  });
}

function parseModel(value: OptionType, add = false) {
  let originalValue = value;
  value = getOption(value);

  if (props.multiple && Array.isArray(model.value)) {
    if (props.getObject) {
      const parent = getParent(originalValue);
      if (!parent)
        parseOption(originalValue, model.value as Array<OptionType>, add);
      else
        updateSelection(
          originalValue,
          parent,
          model.value as Array<OptionType>,
          add
        );
      model.value = model.value.filter((x: OptionType) => x.options?.length);
    } else {
      const index = model.value.findIndex(
        (x: any) => getValue(x) === getValue(value)
      );

      if (index != -1) model.value.splice(index, 1);
      else if (!originalValue.options?.length) model.value.push(value);

      if (originalValue.options?.length) {
        originalValue.options.forEach((option: OptionType) => {
          parseModel(option, add);
        });
      }
    }
  } else model.value = value;
}

function updateSelection(
  option: OptionType,
  parent: OptionType,
  model: Array<OptionType>,
  add: boolean
) {
  if (!parent.options) return;

  const isLevel = parent.options.findIndex((x) => getValue(x) === getValue(option));

  let index = model.findIndex((x) => getValue(x) === getValue(parent));
  if ((!model.length || index == -1) && add) {
    index = model.length;
    model.push({
      ...parent,
      options: [] as OptionType[],
    });
  }

  if (isLevel == -1) {
    const newParent = getParent(option, parent.options);
    if (model[index]?.options && newParent)
      updateSelection(option, newParent, model[index].options!, add);

    return;
  }

  parseOption(option, model[index].options!, add);

  if (
    index !== -1 &&
    model[index]?.options &&
    !model[index]?.options?.length &&
    !add
  )
    model.splice(index, 1);
}

function parseOption(option: OptionType, options: OptionType[], add: boolean) {
  const index = options.findIndex((x) => getValue(x) === getValue(option));
  if (index != -1) options.splice(index, 1);

  if (add) options.push(JSON.parse(JSON.stringify(option)));
}

function setModel(value: OptionType, add = false) {
  parseModel(value, add);
  updateModel();
}
</script>

<template>
  <div class="tree">
    <Option
      v-for="option in options"
      :key="getValue(option)"
      :model-value="model"
      :option="option"
      :get-object="getObject"
      :label-key="labelKey"
      :value-key="valueKey"
      :multiple="multiple"
      :disabled="disabled"
      @update:model-value="setModel"
    />
  </div>
</template>

// src/components/Tree/Tree.tsx
import { createContext, useContext, useState } from 'react';
import clsx from 'clsx';
import { type Option as DropOption } from '../../utils/types/DropOption';
import { useControllable } from '../../hooks/useControllable';
import { Checkbox } from '../Checkbox/Checkbox';
import { Icon } from '../Icon/Icon';
import styles from './Tree.module.css';

interface TreeContextValue {
  selectedValue: any;
  onSelect: (option: DropOption, add: boolean) => void;
  expandedNodes: Set<any>;
  onToggleExpand: (nodeKey: any) => void;
  labelKey: string;
  valueKey: string;
  getObject: boolean;
  multiple: boolean;
  disabled: boolean;
}

const TreeContext = createContext<TreeContextValue | null>(null);

function getRawValue(option: DropOption, valueKey: string): any {
  return typeof option === 'object' && option !== null ? (option as any)[valueKey] : option;
}

function getParent(
  value: DropOption,
  options: DropOption[],
  valueKey: string
): DropOption | undefined {
  return options?.find((option: DropOption) => {
    if (!option.options || !option.options.length) return false;

    const found = option.options.find(
      (x: DropOption) => getRawValue(x, valueKey) === getRawValue(value, valueKey)
    );
    if (found) return found;

    return getParent(value, option.options, valueKey);
  });
}

function parseOptionMut(option: DropOption, options: DropOption[], add: boolean, valueKey: string) {
  const index = options.findIndex((x) => getRawValue(x, valueKey) === getRawValue(option, valueKey));
  if (index !== -1) options.splice(index, 1);
  if (add) options.push(JSON.parse(JSON.stringify(option)));
}

function updateSelectionMut(
  option: DropOption,
  parent: DropOption,
  modelArr: DropOption[],
  add: boolean,
  valueKey: string
) {
  if (!parent.options) return;

  const isLevel = parent.options.findIndex(
    (x) => getRawValue(x, valueKey) === getRawValue(option, valueKey)
  );

  let index = modelArr.findIndex((x) => getRawValue(x, valueKey) === getRawValue(parent, valueKey));

  if ((!modelArr.length || index === -1) && add) {
    index = modelArr.length;
    modelArr.push({ ...parent, options: [] as DropOption[] });
  }

  if (isLevel === -1) {
    const newParent = getParent(option, parent.options, valueKey);
    if (modelArr[index]?.options && newParent) {
      updateSelectionMut(option, newParent, modelArr[index].options!, add, valueKey);
    }
    return;
  }

  parseOptionMut(option, modelArr[index].options!, add, valueKey);

  if (
    index !== -1 &&
    modelArr[index]?.options &&
    !modelArr[index]?.options?.length &&
    !add
  ) {
    modelArr.splice(index, 1);
  }
}

function updateSelection(
  option: DropOption,
  add: boolean,
  currentSelection: any[],
  valueKey: string,
  getObject: boolean
): any[] {
  const arr = [...currentSelection];

  if (getObject) {
    const topParent = (() => {
      for (const sel of arr) {
        if (sel.options) {
          const found = (sel.options as DropOption[]).find(
            (x: DropOption) => getRawValue(x, valueKey) === getRawValue(option, valueKey)
          );
          if (found) return sel as DropOption;
        }
      }
      return undefined;
    })();

    if (!topParent) {
      parseOptionMut(option, arr as DropOption[], add, valueKey);
    } else {
      updateSelectionMut(option, topParent, arr as DropOption[], add, valueKey);
    }
    return arr.filter((x: any) => x.options?.length);
  } else {
    const rawOptionValue = getRawValue(option, valueKey);
    const index = arr.findIndex((x: any) => getRawValue(x, valueKey) === rawOptionValue);

    if (index !== -1) {
      arr.splice(index, 1);
    } else if (!option.options?.length) {
      arr.push(rawOptionValue);
    }

    if (option.options?.length) {
      option.options.forEach((child: DropOption) => {
        const childResult = updateSelection(child, add, arr, valueKey, getObject);
        arr.length = 0;
        childResult.forEach((v) => arr.push(v));
      });
    }

    return arr;
  }
}

function getAllLeafValues(options: DropOption[], valueKey: string): any[] {
  const values: any[] = [];
  for (const opt of options) {
    if (opt.options?.length) {
      values.push(...getAllLeafValues(opt.options, valueKey));
    } else {
      values.push((opt as any)[valueKey]);
    }
  }
  return values;
}

function checkIsSelected(selectedValue: any, nodeValue: any, ctx: TreeContextValue, option?: DropOption): boolean | null {
  if (ctx.multiple) {
    if (!Array.isArray(selectedValue)) return false;

    const isValueMatch = (v: any) => {
      if (ctx.getObject && typeof v === 'object' && v !== null) {
        return (v as any)[ctx.valueKey] === nodeValue;
      }
      const raw = typeof v === 'object' && v !== null ? (v as any)[ctx.valueKey] : v;
      return raw === nodeValue;
    };

    const directMatch = selectedValue.some(isValueMatch);
    if (directMatch) return true;

    if (option?.options?.length) {
      const childValues = getAllLeafValues(option.options, ctx.valueKey);
      const isChildSelected = (cv: any) =>
        selectedValue.some((v: any) => {
          if (ctx.getObject && typeof v === 'object' && v !== null) {
            return (v as any)[ctx.valueKey] === cv;
          }
          const raw = typeof v === 'object' && v !== null ? (v as any)[ctx.valueKey] : v;
          return raw === cv;
        });

      const someSelected = childValues.some(isChildSelected);
      const allSelected = childValues.length > 0 && childValues.every(isChildSelected);
      if (allSelected) return true;
      if (someSelected) return null;
    }

    return false;
  } else {
    if (ctx.getObject && typeof selectedValue === 'object' && selectedValue !== null) {
      return (selectedValue as any)[ctx.valueKey] === nodeValue;
    }
    return selectedValue === nodeValue;
  }
}

function TreeNode({ option, depth = 0 }: { option: DropOption; depth?: number }) {
  const ctx = useContext(TreeContext)!;
  const nodeValue = (option as any)[ctx.valueKey];
  const nodeLabel = (option as any)[ctx.labelKey];
  const isExpanded = ctx.expandedNodes.has(nodeValue);
  const hasChildren = Boolean(option.options && option.options.length > 0);
  const isSelected = checkIsSelected(ctx.selectedValue, nodeValue, ctx, option);

  return (
    <div className={styles.treeOption} style={{ paddingLeft: depth * 16 }}>
      <div
        className={clsx(
          styles.nodeRow,
          isSelected === true && styles.selected,
          ctx.multiple && styles.multiple,
          (ctx.disabled || option.disabled) && styles.disabled
        )}
        onClick={() => {
          if (!ctx.disabled && !option.disabled) {
            ctx.onSelect(option, !isSelected);
          }
        }}
      >
        {hasChildren && (
          <Icon
            name="keyboard_arrow_right"
            className={clsx(styles.expandIcon, isExpanded && styles.expandIconOpen)}
            onClick={(e: any) => {
              e.stopPropagation();
              ctx.onToggleExpand(nodeValue);
            }}
          />
        )}
        {ctx.multiple && (
          <Checkbox
            value={isSelected}
            onChange={() => {}}
            disabled={ctx.disabled || option.disabled}
            allowIndeterminate
          />
        )}
        {option.icon && (
          <Icon name={option.icon} className={styles.nodeIcon} />
        )}
        <span className={clsx(styles.nodeLabel)}>
          {nodeLabel}
        </span>
      </div>
      {isExpanded && hasChildren &&
        option.options!.map((child) => (
          <TreeNode key={(child as any)[ctx.valueKey]} option={child} depth={depth + 1} />
        ))
      }
    </div>
  );
}

export interface TreeProps {
  value?: any;
  defaultValue?: any;
  onChange?: (value: any) => void;
  options: DropOption[];
  labelKey?: string;
  valueKey?: string;
  getObject?: boolean;
  multiple?: boolean;
  disabled?: boolean;
  className?: string;
}

export function Tree({
  value,
  defaultValue,
  onChange,
  options,
  labelKey = 'label',
  valueKey = 'value',
  getObject = false,
  multiple = false,
  disabled = false,
  className,
}: TreeProps) {
  const [selectedValue, setSelectedValue] = useControllable<any>({
    value,
    defaultValue: defaultValue ?? (multiple ? [] : undefined),
    onChange,
  });

  const [expandedNodes, setExpandedNodes] = useState<Set<any>>(new Set());

  const handleToggle = (nodeKey: any) => {
    setExpandedNodes((prev) => {
      const next = new Set(prev);
      if (next.has(nodeKey)) {
        next.delete(nodeKey);
      } else {
        next.add(nodeKey);
      }
      return next;
    });
  };

  const handleSelect = (option: DropOption, add: boolean) => {
    if (multiple) {
      const newSelection = updateSelection(
        option,
        add,
        selectedValue ?? [],
        valueKey,
        getObject
      );
      setSelectedValue(newSelection);
    } else {
      const newValue = getObject ? option : (option as any)[valueKey];
      setSelectedValue(newValue);
    }
  };

  return (
    <TreeContext.Provider
      value={{
        selectedValue,
        onSelect: handleSelect,
        expandedNodes,
        onToggleExpand: handleToggle,
        labelKey,
        valueKey,
        getObject,
        multiple,
        disabled,
      }}
    >
      <div className={clsx(styles.tree, 'tree', className)}>
        {options.map((option) => (
          <TreeNode key={(option as any)[valueKey]} option={option} />
        ))}
      </div>
    </TreeContext.Provider>
  );
}
