// src/components/ToggleGroup/ToggleGroup.vue
<script setup lang="ts">
import Group from "../../utils/components/Group.vue";
import Toggle from "../Toggle/Toggle.vue";
import { focusByArrowKey, getFocusableItems, isObject } from "../../utils";
import { ref, watch } from "vue";

const props = withDefaults(
  defineProps<{
    modelValue?: any;
    vertical?: boolean;
    disabled?: boolean;
    options: any[];
    type?: "default" | "secondary";
    labelKey?: string;
    valueKey?: string;
    getObject?: boolean;
  }>(),
  {
    modelValue: null,
    vertical: false,
    disabled: false,
    type: "default",
    labelKey: "label",
    valueKey: "value",
    getObject: false,
  }
);

const emit = defineEmits<{
  "update:modelValue": [value: any];
}>();

const model = ref<any>(getValue(props.modelValue));

watch(
  () => props.modelValue,
  (newVal) => {
    model.value = getValue(newVal);
  }
);

function setModel(value: string) {
  let valueToEmit = value;
  model.value = value;
  if (props.getObject) {
    const object = props.options.find((option: any) => getValue(option) === value);
    valueToEmit = object;
  }
  emit("update:modelValue", valueToEmit);
}

function getLabel(value: any): string {
  return isObject(value) ? value[props.labelKey] : value;
}

function getValue(option: any): any {
  return isObject(option) ? option[props.valueKey] : option;
}

function getDisabled(option: any): boolean {
  return isObject(option) ? option.disabled : false;
}

function onKeyDown(event: KeyboardEvent) {
  focusByArrowKey(
    event,
    getFocusableItems(event.currentTarget as HTMLElement, ".toggle"),
    props.vertical ? "vertical" : "horizontal"
  );
}
</script>

<template>
  <Group
    v-model="model"
    :vertical="vertical"
    :disabled="disabled"
    class="toggle-group"
    role="group"
    @update:model-value="setModel"
    @keydown="onKeyDown"
  >
    <Toggle
      v-for="option in options"
      :key="getValue(option)"
      :group-value="getValue(option)"
      :disabled="getDisabled(option)"
      :type="type"
    >
      {{ getLabel(option) }}
    </Toggle>
  </Group>
</template>

<style scoped>
@reference "../../assets/main.css";

.toggle-group.hor .toggle.default {
  @apply border-r-none first:rounded-l-sm last:rounded-r-sm last:border-r-xxs;
}

.toggle-group.vert .toggle.default {
  @apply border-b-none first:rounded-t-sm last:rounded-b-sm last:border-b-xxs;
}

.toggle-group.hor .toggle.secondary {
  @apply ml-xs first:ml-none;
}

.toggle-group.vert .toggle.secondary {
  @apply mt-xs first:mt-none;
}
</style>

// src/components/ToggleGroup/ToggleGroup.tsx
import { createContext } from 'react';
import clsx from 'clsx';
import { useControllable } from '../../hooks/useControllable';
import { isObject, focusByArrowKey, getFocusableItems } from '../../utils';
import { Toggle } from '../Toggle/Toggle';
import styles from './ToggleGroup.module.css';

export interface ToggleGroupContextValue {
  selected: any;
  disabled: boolean;
  type: 'default' | 'secondary';
  select: (value: any) => void;
}

export const ToggleGroupContext = createContext<ToggleGroupContextValue | null>(null);

export interface ToggleGroupProps {
  value?: any;
  onChange?: (value: any) => void;
  vertical?: boolean;
  disabled?: boolean;
  type?: 'default' | 'secondary';
  options?: Array<any>;
  labelKey?: string;
  valueKey?: string;
  getObject?: boolean;
  children?: React.ReactNode;
  className?: string;
}

export function ToggleGroup({
  value,
  onChange,
  vertical = false,
  disabled = false,
  type = 'default',
  options,
  labelKey = 'label',
  valueKey = 'value',
  getObject = false,
  children,
  className,
}: ToggleGroupProps) {
  const [currentValue, setCurrentValue] = useControllable<any>({ value, onChange });

  function getLabel(option: any): string {
    return isObject(option) ? option[labelKey] : option;
  }

  function getValue(option: any): any {
    return isObject(option) ? option[valueKey] : option;
  }

  function getOptionDisabled(option: any): boolean {
    return isObject(option) ? option.disabled : false;
  }

  function select(selectedValue: any) {
    let valueToEmit = selectedValue;
    if (getObject && options) {
      const obj = options.find((opt: any) => getValue(opt) === selectedValue);
      if (obj !== undefined) valueToEmit = obj;
    }
    setCurrentValue(valueToEmit);
  }

  const contextValue: ToggleGroupContextValue = {
    selected: currentValue,
    disabled,
    type,
    select,
  };

  function handleKeyDown(e: React.KeyboardEvent<HTMLDivElement>) {
    const items = getFocusableItems(e.currentTarget, '[role="button"]');
    focusByArrowKey(e, items, vertical ? 'vertical' : 'horizontal');
  }

  return (
    <ToggleGroupContext.Provider value={contextValue}>
      <div
        role="group"
        className={clsx(
          styles.toggleGroup,
          'toggle-group',
          vertical && styles.vertical,
          type === 'default' && styles.default,
          type === 'secondary' && !vertical && styles.secondary,
          type === 'secondary' && vertical && styles.secondaryVertical,
          className
        )}
        onKeyDown={handleKeyDown}
      >
        {options
          ? options.map((opt: any) => (
              <Toggle key={getValue(opt)} groupValue={getValue(opt)} disabled={getOptionDisabled(opt)}>
                {getLabel(opt)}
              </Toggle>
            ))
          : children}
      </div>
    </ToggleGroupContext.Provider>
  );
}
